(function(){
  'use strict';
  function safe(v){var t=v==null?'':String(v);return typeof window.esc==='function'?window.esc(t):t.replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function customer(){if(!window.state||!state.selectedUnit||!Array.isArray(state.dues))return null;return state.dues.find(function(c){return(c.unit+'::'+c.sno)===state.selectedUnit})||null}
  function money(v){return typeof window.fmtAED==='function'?window.fmtAED(v):'AED '+Number(v||0).toLocaleString('en-AE',{maximumFractionDigits:0})}
  function day(v){if(!v)return null;var d=v instanceof Date?new Date(v.getTime()):new Date(v);if(isNaN(d.getTime()))return null;d.setHours(0,0,0,0);return d}
  function date(v){if(!v)return'';return typeof window.fmtDate==='function'?window.fmtDate(v):day(v).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
  function settled(s){var st=String(s&&s.status||'').trim().toLowerCase();return st==='paid'||st==='settled'||st==='completed'||st==='complete'}
  function overdue(c,today){var a=[];(c&&c.stages||[]).forEach(function(s){if(!s||s.carryForwardManaged===true||settled(s))return;var due=Number(s.due),paid=Number(s.paid)||0,d=day(s.dueDate),rem=due-paid;if(!isFinite(due)||rem<=1000||!d||d>=today)return;a.push({label:String(s.label||'Installment'),remaining:rem,dueDate:d,days:Math.max(1,Math.floor((today-d)/86400000))})});a.sort(function(a,b){return a.dueDate-b.dueDate});return a}
  function action(c){var t=new Date();t.setHours(0,0,0,0);var o=overdue(c,t);if(o.length){var total=o.reduce(function(s,x){return s+x.remaining},0),old=o[0],labels=o.map(function(x){return x.label});if(o.length===1)return{status:'Overdue',tone:'danger',message:'Collect '+money(total)+' for '+labels[0]+' now. It was due on '+date(old.dueDate)+'.',stage:labels[0],by:date(old.dueDate),due:old.days+' days overdue'};return{status:'Overdue',tone:'danger',message:'Collect '+money(total)+' total overdue for '+labels.join(' + ')+'.',stage:'Multiple installments',by:date(old.dueDate),due:old.days+' days overdue'}}var amt=Number(c&&c.upAmt),stage=String(c&&c.upStage||''),d=day(c&&c.upDate);if(!isFinite(amt)||amt<=1000)return{status:'Up to date',tone:'good',message:'No installment payment action is currently required.',stage:'No pending stage',by:'—',due:'—'};if(!d)return{status:'Date needed',tone:'warn',message:'Next installment is '+money(amt)+'.',stage:stage||'Next installment',by:'Not set',due:'—'};var n=Math.round((d-t)/86400000),dt=date(d);if(n<0)return{status:'Overdue',tone:'danger',message:'Collect '+money(amt)+' for '+(stage||'the next installment')+' now. It was due on '+dt+'.',stage:stage||'Next installment',by:dt,due:Math.abs(n)+' days overdue'};return{status:n===0?'Due today':n<=7?'Due soon':'Upcoming',tone:n===0?'danger':n<=7?'warn':'neutral',message:'Next installment is '+money(amt)+' due on '+dt+'.',stage:stage||'Next installment',by:dt,due:n===0?'Today':n+' days'}}
  function icon(k){var c='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"';if(k==='layers')return'<svg '+c+'><path d="m12 2 9 5-9 5-9-5 9-5z"/><path d="m3 12 9 5 9-5"/><path d="m3 17 9 5 9-5"/></svg>';if(k==='hourglass')return'<svg '+c+'><path d="M6 2h12M6 22h12M8 2v5c0 2 1.5 3.5 4 5-2.5 1.5-4 3-4 5v5M16 2v5c0 2-1.5 3.5-4 5 2.5 1.5 4 3 4 5v5"/></svg>';return'<svg '+c+'><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></svg>'}
  function styles(){if(document.getElementById('actionRequiredStyles'))return;var s=document.createElement('style');s.id='actionRequiredStyles';s.textContent='.action-required-card{position:relative;border:1px solid var(--paper-line);border-left:6px solid var(--slate,#45566B);border-radius:16px;margin:0 0 16px;background:var(--paper);overflow:hidden}.action-required-card[data-tone="danger"]{border-left-color:var(--rust)}.action-required-card[data-tone="warn"]{border-left-color:var(--amber)}.action-required-card[data-tone="good"]{border-left-color:var(--sage)}.action-required-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 18px 8px}.action-required-title{font:700 10px/1.1 "IBM Plex Mono",monospace;letter-spacing:.095em;text-transform:uppercase;color:var(--amber,#9C5A12)}.action-required-status-wrap{display:inline-flex;align-items:center;gap:7px;border:1.3px solid currentColor;border-radius:999px;padding:6px 10px}.action-required-status-icon svg{width:15px;height:15px}.action-required-status{font:700 11px/1 Inter,sans-serif}.action-required-message{margin:0!important;padding:13px 18px 18px;font:700 18px/1.28 Inter,sans-serif;color:var(--ink)}.action-required-divider{height:1px;background:var(--paper-line);margin:0 18px}.action-required-meta{display:grid;grid-template-columns:1.22fr 1fr .82fr;padding:0 18px}.action-required-meta-block{display:flex;align-items:center;gap:11px;min-width:0;min-height:74px;padding:12px 13px 12px 0}.action-required-meta-block+.action-required-meta-block{border-left:1px solid var(--paper-line);padding-left:15px}.action-required-meta-icon{width:36px;height:36px;border-radius:11px;display:flex;align-items:center;justify-content:center;flex:none}.action-required-meta-icon svg{width:22px;height:22px}.action-required-meta-label{font:700 10.4px/1.18 Inter,sans-serif;margin-bottom:5px}.action-required-meta-value{font:500 10.8px/1.18 Inter,sans-serif;overflow-wrap:anywhere}@media(max-width:520px){.action-required-card{border-left-width:5px;border-radius:14px}.action-required-head{padding:12px 14px 6px}.action-required-message{padding:10px 14px 14px;font-size:15px}.action-required-divider{margin:0 14px}.action-required-meta{padding:0 14px;grid-template-columns:1.25fr 1fr .8fr}.action-required-meta-block{gap:8px;min-height:62px;padding:9px 8px 9px 0}.action-required-meta-block+.action-required-meta-block{padding-left:9px}.action-required-meta-icon{width:30px;height:30px}.action-required-meta-icon svg{width:18px;height:18px}}';document.head.appendChild(s)}
  function renderCard(card,a){styles();card.setAttribute('data-tone',a.tone);card.innerHTML='<div class="action-required-head"><span class="action-required-title">Action Required</span><span class="action-required-status-wrap"><span class="action-required-status-icon">'+icon('calendar')+'</span><span class="action-required-status">'+safe(a.status)+'</span></span></div><p class="action-required-message">'+safe(a.message)+'</p><div class="action-required-divider"></div><div class="action-required-meta"><div class="action-required-meta-block"><span class="action-required-meta-icon">'+icon('layers')+'</span><span><div class="action-required-meta-label">Stage</div><div class="action-required-meta-value">'+safe(a.stage)+'</div></span></div><div class="action-required-meta-block"><span class="action-required-meta-icon">'+icon('calendar')+'</span><span><div class="action-required-meta-label">By</div><div class="action-required-meta-value">'+safe(a.by)+'</div></span></div><div class="action-required-meta-block"><span class="action-required-meta-icon">'+icon('hourglass')+'</span><span><div class="action-required-meta-label">Due In</div><div class="action-required-meta-value">'+safe(a.due)+'</div></span></div></div>'}
  window.sunblissRenderActionRequiredCard=renderCard;
  function render(){if(!window.state||state.view!=='detail')return;var c=customer(),detail=document.querySelector('.detail');if(!c||!detail)return;var card=document.getElementById('actionRequiredCard');if(!card){card=document.createElement('section');card.id='actionRequiredCard';card.className='action-required-card';var badges=detail.querySelector('.badges');if(badges&&badges.parentNode)badges.parentNode.insertBefore(card,badges.nextSibling);else detail.insertBefore(card,detail.firstChild)}renderCard(card,action(c));document.querySelectorAll('.detail .notice .notice-body').forEach(function(n){if(String(n.textContent||'').trim().toLowerCase().indexOf('next due:')===0)n.remove()})}
  function install(){if(!window.state||typeof window.renderDetail!=='function'){setTimeout(install,50);return}if(window.__sunblissActionRequiredInstalled)return;window.__sunblissActionRequiredInstalled=true;var old=window.renderDetail;window.renderDetail=function(){var x=old.apply(this,arguments);render();return x};if(state.view==='detail')render()}
  install();
})();