(function(){
'use strict';
if(window.__sunblissCeoProfessionalCleanV3Installed)return;
window.__sunblissCeoProfessionalCleanV3Installed=true;
var PARAM='ceo-preview',timer=null,observer=null,busy=false;
function text(v){return v==null?'':String(v)}
function mode(){try{return new URLSearchParams(location.search).get(PARAM)==='1'||(window.state&&state.userRole==='ceo')}catch(_e){return false}}
function styles(){if(document.getElementById('ceoProfessionalCleanV3Styles'))return;var s=document.createElement('style');s.id='ceoProfessionalCleanV3Styles';s.textContent=[
'body.ceo-mode.ceo-pro3{background:var(--ink-2)!important;color:var(--ink)!important}',
'body.ceo-mode.ceo-pro3 #app{max-width:640px!important;margin:0 auto!important;padding:0 0 82px!important;background:transparent!important;box-shadow:none!important}',
'body.ceo-mode.ceo-pro3 .ceo-shell{background:transparent!important;min-height:100vh!important}',
'body.ceo-mode.ceo-pro3 .ceo-content{margin-top:0!important;padding:16px 16px 30px!important;background:var(--paper)!important;border-radius:22px 22px 0 0!important;min-height:calc(100vh - 210px)!important;position:relative!important;z-index:3!important}',
'.ceo-pro3-intro{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin:1px 1px 14px}.ceo-pro3-intro-copy{min-width:0}.ceo-pro3-eyebrow{font:600 9px/1.2 IBM Plex Mono,monospace;letter-spacing:.12em;text-transform:uppercase;color:var(--gold-deep);margin:0 0 5px}.ceo-pro3-title{font:650 22px/1.08 Fraunces,serif;color:var(--ink);margin:0;letter-spacing:-.01em}.ceo-pro3-sub{font-size:10px;line-height:1.45;color:var(--muted);margin:5px 0 0;max-width:390px}.ceo-pro3-readonly{flex:none;display:inline-flex;align-items:center;gap:5px;border:1px solid var(--paper-line);border-radius:999px;background:var(--paper-dim);padding:5px 8px;font:600 8px/1 IBM Plex Mono,monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}.ceo-pro3-readonly:before{content:"";width:5px;height:5px;border-radius:50%;background:var(--sage)}',
'body.ceo-mode.ceo-pro3 .ceo-kpi-grid{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;margin:0 0 10px!important;background:transparent!important}',
'body.ceo-mode.ceo-pro3 .ceo-card{background:var(--paper)!important;border:1px solid var(--paper-line)!important;border-radius:13px!important;box-shadow:none!important}',
'body.ceo-mode.ceo-pro3 .ceo-kpi{min-height:94px!important;padding:13px 31px 12px 13px!important;position:relative!important;cursor:pointer!important;transition:background .14s ease,border-color .14s ease,transform .14s ease!important}',
'body.ceo-mode.ceo-pro3 .ceo-kpi:hover{background:#fbf8ef!important;border-color:#cfc2a2!important}body.ceo-mode.ceo-pro3 .ceo-kpi:active{transform:scale(.995)!important}',
'body.ceo-mode.ceo-pro3 .ceo-kpi-label{font:600 8.5px/1.2 IBM Plex Mono,monospace!important;letter-spacing:.08em!important;color:var(--muted)!important;margin:0 0 8px!important}',
'body.ceo-mode.ceo-pro3 .ceo-kpi-value{font:650 19px/1.1 Fraunces,serif!important;color:var(--ink)!important;margin:0!important}',
'body.ceo-mode.ceo-pro3 .ceo-kpi[data-tone="good"] .ceo-kpi-value{color:var(--sage)!important}body.ceo-mode.ceo-pro3 .ceo-kpi[data-tone="danger"] .ceo-kpi-value{color:var(--rust)!important}',
'body.ceo-mode.ceo-pro3 .ceo-kpi-sub{font-size:9px!important;line-height:1.35!important;color:var(--muted)!important;margin-top:5px!important;padding-right:0!important}',
'body.ceo-mode.ceo-pro3 .ceo-clean-arrow{right:11px!important;bottom:auto!important;top:50%!important;transform:translateY(-50%)!important;font-size:20px!important;color:#a79d87!important}',
'body.ceo-mode.ceo-pro3 .ceo-clean-actions{display:block!important;margin:0 0 10px!important;border:1px solid var(--paper-line)!important;border-radius:13px!important;background:var(--paper)!important;overflow:hidden!important;box-shadow:none!important}',
'body.ceo-mode.ceo-pro3 .ceo-clean-action{width:100%!important;border:0!important;border-top:1px solid var(--paper-line)!important;border-radius:0!important;background:var(--paper)!important;box-shadow:none!important;padding:11px 12px!important;grid-template-columns:31px 1fr 15px!important;gap:9px!important;min-height:55px!important;transform:none!important}',
'body.ceo-mode.ceo-pro3 .ceo-clean-action:first-child{border-top:0!important}body.ceo-mode.ceo-pro3 .ceo-clean-action:hover{background:#fbf8ef!important;box-shadow:none!important;transform:none!important}',
'body.ceo-mode.ceo-pro3 .ceo-clean-action .ic{width:31px!important;height:31px!important;border-radius:9px!important;background:var(--paper-dim)!important;color:var(--gold-deep)!important;border:1px solid var(--paper-line)!important}',
'body.ceo-mode.ceo-pro3 .ceo-clean-action .ic svg{width:15px!important;height:15px!important}body.ceo-mode.ceo-pro3 .ceo-clean-action strong{font-size:10.2px!important;color:var(--ink)!important}body.ceo-mode.ceo-pro3 .ceo-clean-action span{font-size:8.7px!important;color:var(--muted)!important;margin-top:3px!important}body.ceo-mode.ceo-pro3 .ceo-clean-action .go{font-size:18px!important;color:#aaa08a!important;margin-top:0!important}',
'body.ceo-mode.ceo-pro3 #ceoCleanPulse{display:none!important}',
'body.ceo-mode.ceo-pro3 .ceo-section{margin-top:10px!important}',
'body.ceo-mode.ceo-pro3 .ceo-section-head{padding:13px 13px 9px!important;align-items:center!important}',
'body.ceo-mode.ceo-pro3 .ceo-section-title{font:650 15px/1.2 Fraunces,serif!important;color:var(--ink)!important}',
'body.ceo-mode.ceo-pro3 .ceo-section-sub{font-size:9px!important;line-height:1.4!important;color:var(--muted)!important;margin-top:3px!important}',
'body.ceo-mode.ceo-pro3 .ceo-section-link{font-size:9px!important;color:var(--gold-deep)!important;background:transparent!important;border:0!important;border-radius:0!important;padding:4px 0!important;font-weight:700!important}',
'body.ceo-mode.ceo-pro3 .ceo-decision-row{padding:11px 31px 11px 13px!important;border-top:1px solid var(--paper-line)!important;background:var(--paper)!important;position:relative!important;cursor:pointer!important;transform:none!important}',
'body.ceo-mode.ceo-pro3 .ceo-decision-row:hover{background:#fbf8ef!important;transform:none!important}body.ceo-mode.ceo-pro3 .ceo-decision-row:before{display:none!important}body.ceo-mode.ceo-pro3 .ceo-decision-row:after{content:"›";position:absolute;right:11px;top:50%;transform:translateY(-50%);font-size:20px;color:#aaa08a}',
'body.ceo-mode.ceo-pro3 .ceo-unit{font:700 10.5px IBM Plex Mono,monospace!important;color:var(--gold-deep)!important}body.ceo-mode.ceo-pro3 .ceo-decision-name{font-size:10.2px!important;margin-top:4px!important}body.ceo-mode.ceo-pro3 .ceo-tag{font-size:7.4px!important;padding:4px 6px!important;border-color:#dfcfaa!important;background:#fbf6e8!important;color:#7d5a18!important}',
'body.ceo-mode.ceo-pro3 .ceo-decision-note{font-size:9px!important;line-height:1.42!important;color:var(--muted)!important;margin-top:5px!important;display:-webkit-box!important;-webkit-line-clamp:2!important;-webkit-box-orient:vertical!important;overflow:hidden!important}',
'body.ceo-mode.ceo-pro3 .ceo-decision-meta{font-size:8.5px!important;margin-top:7px!important;color:var(--muted)!important}body.ceo-mode.ceo-pro3 .ceo-decision-meta strong{color:var(--rust)!important}',
'body.ceo-mode.ceo-pro3 .ceo-v2-rec{display:none!important}',
'body.ceo-mode.ceo-pro3 .ceo-metric-block{padding:7px 13px 12px!important}body.ceo-mode.ceo-pro3 .ceo-metric-row{padding:7px 0!important;border-color:var(--paper-line)!important}body.ceo-mode.ceo-pro3 .ceo-metric-label{font-size:9.4px!important;color:var(--muted)!important}body.ceo-mode.ceo-pro3 .ceo-metric-value{font-size:9.8px!important;color:var(--ink)!important}',
'body.ceo-mode.ceo-pro3 .ceo-progress{height:6px!important;background:#e5ddca!important}body.ceo-mode.ceo-pro3 .ceo-progress>span{background:var(--sage)!important}',
'body.ceo-mode.ceo-pro3 .ceo-cash-grid{gap:6px!important;padding:0 13px 12px!important}body.ceo-mode.ceo-pro3 .ceo-cash-box{border-radius:9px!important;padding:9px 10px!important;background:var(--paper-dim)!important;border-color:var(--paper-line)!important;cursor:pointer!important}body.ceo-mode.ceo-pro3 .ceo-cash-label{font-size:8.2px!important}body.ceo-mode.ceo-pro3 .ceo-cash-value{font-size:10.5px!important}',
'body.ceo-mode.ceo-pro3 .ceo-attention>div{padding:9px 8px!important;background:var(--paper)!important}body.ceo-mode.ceo-pro3 .ceo-attention strong{font-size:10.7px!important}body.ceo-mode.ceo-pro3 .ceo-attention span{font-size:7.8px!important}',
'body.ceo-mode.ceo-pro3 .ceo-page-title{padding:1px 1px 12px!important}body.ceo-mode.ceo-pro3 .ceo-page-title h2{font:650 20px/1.1 Fraunces,serif!important;color:var(--ink)!important}body.ceo-mode.ceo-pro3 .ceo-page-title p{font-size:9.5px!important;line-height:1.45!important;color:var(--muted)!important;margin-top:5px!important}',
'body.ceo-mode.ceo-pro3 .ceo-aging{gap:7px!important;padding:0 13px 12px!important}body.ceo-mode.ceo-pro3 .ceo-aging-box{border-radius:9px!important;padding:9px!important;border-color:var(--paper-line)!important}body.ceo-mode.ceo-pro3 .ceo-aging-box span{font-size:8.2px!important}body.ceo-mode.ceo-pro3 .ceo-aging-box strong{font-size:10.2px!important}',
'body.ceo-mode.ceo-pro3 .ceo-list-row{padding:10px 13px!important;border-color:var(--paper-line)!important}body.ceo-mode.ceo-pro3 .ceo-list-title{font-size:9.8px!important}body.ceo-mode.ceo-pro3 .ceo-list-sub{font-size:8.5px!important}body.ceo-mode.ceo-pro3 .ceo-list-value{font-size:9.6px!important}',
'body.ceo-mode.ceo-pro3 .ceo-search{border-radius:11px!important;padding:10px 12px!important;background:var(--paper-dim)!important;border-color:var(--paper-line)!important;box-shadow:none!important}body.ceo-mode.ceo-pro3 .ceo-search input{font-size:14px!important}',
'body.ceo-mode.ceo-pro3 .ceo-search-card{border-radius:11px!important;padding:10px 29px 10px 11px!important;margin-bottom:7px!important;border-color:var(--paper-line)!important;background:var(--paper)!important;box-shadow:none!important;position:relative!important}body.ceo-mode.ceo-pro3 .ceo-search-card:after{content:"›";position:absolute;right:10px;top:50%;transform:translateY(-50%);font-size:19px;color:#aaa08a}',
'body.ceo-mode.ceo-pro3 .ceo-search-unit{font-size:10.2px!important;color:var(--gold-deep)!important}body.ceo-mode.ceo-pro3 .ceo-search-name{font-size:10px!important}body.ceo-mode.ceo-pro3 .ceo-search-meta{font-size:8.5px!important}',
'body.ceo-mode.ceo-pro3 .ceo-bottom{width:min(620px,calc(100% - 16px))!important;bottom:8px!important;border-radius:15px!important;background:rgba(15,26,38,.97)!important;border-color:rgba(237,230,214,.13)!important;box-shadow:0 8px 26px rgba(0,0,0,.26)!important}body.ceo-mode.ceo-pro3 .ceo-nav-btn{padding:9px 3px 8px!important;font-size:8px!important;color:rgba(237,230,214,.55)!important}body.ceo-mode.ceo-pro3 .ceo-nav-btn svg{width:16px!important;height:16px!important}body.ceo-mode.ceo-pro3 .ceo-nav-btn.active{color:#e2b157!important;background:rgba(198,151,46,.055)!important}',
'body.ceo-mode.ceo-pro3 .ceo-overlay{background:rgba(9,17,23,.48)!important}body.ceo-mode.ceo-pro3 .ceo-detail{background:var(--paper)!important;border-radius:18px 18px 0 0!important}body.ceo-mode.ceo-pro3 .ceo-detail-head{background:rgba(246,241,228,.96)!important;border-color:var(--paper-line)!important}body.ceo-mode.ceo-pro3 .ceo-detail-stat{background:var(--paper)!important;border-color:var(--paper-line)!important;border-radius:10px!important}body.ceo-mode.ceo-pro3 .ceo-note{background:#fbf6e8!important;border-color:#dfcfaa!important;color:#62563f!important}body.ceo-mode.ceo-pro3 .ceo-tx{background:var(--paper)!important;border-color:var(--paper-line)!important}',
'.ceo-pro3-hide{display:none!important}',
'@media(max-width:390px){body.ceo-mode.ceo-pro3 .ceo-content{padding-left:13px!important;padding-right:13px!important}.ceo-pro3-title{font-size:20px}.ceo-pro3-readonly{font-size:7.4px;padding:5px 7px}body.ceo-mode.ceo-pro3 .ceo-kpi-value{font-size:18px!important}}'
].join('');document.head.appendChild(s)}
function findSection(title){return Array.prototype.slice.call(document.querySelectorAll('.ceo-overview .ceo-section')).find(function(s){var h=s.querySelector('.ceo-section-title');return h&&text(h.textContent).trim().toLowerCase()===title.toLowerCase()})||null}
function actualHeader(){var h=document.querySelector('.ceo-top');if(!h)return;h.className='topbar';h.removeAttribute('style')}
function intro(){var page=document.querySelector('.ceo-overview'),grid=page&&page.querySelector('.ceo-kpi-grid');if(!page||!grid||document.getElementById('ceoPro3Intro'))return;var d=document.createElement('div');d.id='ceoPro3Intro';d.className='ceo-pro3-intro';d.innerHTML='<div class="ceo-pro3-intro-copy"><p class="ceo-pro3-eyebrow">Executive View</p><h1 class="ceo-pro3-title">Executive Overview</h1><p class="ceo-pro3-sub">A focused view of sales, collections and management matters requiring attention.</p></div><span class="ceo-pro3-readonly">Read only</span>';page.insertBefore(d,grid)}
function simplify(){var portfolio=findSection('Portfolio'),snapshot=findSection('Management Snapshot');if(portfolio)portfolio.classList.add('ceo-pro3-hide');if(snapshot)snapshot.classList.add('ceo-pro3-hide');var decisionTitle=Array.prototype.slice.call(document.querySelectorAll('.ceo-overview .ceo-section-title')).find(function(h){return /Decision/.test(text(h.textContent))});if(decisionTitle){var s=decisionTitle.closest('.ceo-section'),sub=s&&s.querySelector('.ceo-section-sub');decisionTitle.textContent='Management Attention';if(sub)sub.textContent='Cases requiring management review are separated from routine CRM follow-ups.'}var collections=findSection('Collections');if(collections){var sub=collections.querySelector('.ceo-section-sub');if(sub)sub.textContent='Current month progress and upcoming scheduled collections.'}}
function focusLabels(){var actions=document.getElementById('ceoCleanActions');if(!actions||actions.dataset.v3==='1')return;actions.dataset.v3='1';var first=actions.querySelector('[data-route="decisions"] strong'),second=actions.querySelector('[data-route="collections"] strong'),third=actions.querySelector('[data-route="portfolio"] strong');if(first)first.textContent='Management Decisions';if(second)second.textContent='Collections & Cash Flow';if(third)third.textContent='Sales & Portfolio'}
function enhance(){if(!mode()||busy)return;var shell=document.querySelector('.ceo-shell');if(!shell)return;busy=true;try{styles();document.body.classList.remove('ceo-v2','ceo-clean');document.body.classList.add('ceo-pro3');actualHeader();intro();simplify();focusLabels()}finally{busy=false}}
function schedule(){clearTimeout(timer);timer=setTimeout(enhance,35)}
function attach(){var app=document.getElementById('app');if(!app||observer)return;observer=new MutationObserver(schedule);observer.observe(app,{childList:true,subtree:true});schedule();setTimeout(enhance,180);setTimeout(enhance,520)}
var prior=window.render;if(typeof prior==='function')window.render=function(){var r=prior.apply(this,arguments);if(mode())schedule();return r};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach);else attach();
})();