(function(){
  'use strict';
  if(window.__sunblissCreditNotesInsightsInstalled)return;window.__sunblissCreditNotesInsightsInstalled=true;
  function install(){
    var A=window.__sunblissCreditNoteApi;
    if(!A||typeof window.renderInsights!=='function'){setTimeout(install,50);return;}
    function owner(note){return A.allCustomers().find(function(c){return A.text(c.sno)===A.text(note.unitId);})||{name:'',unit:''};}
    function filtered(){var from=A.text(state.creditNoteFilterFrom||''),to=A.text(state.creditNoteFilterTo||'');return(state.creditNotes||[]).filter(function(n){var d=A.text(n.issueDate);return(!from||d>=from)&&(!to||d<=to);});}
    function section(){
      var notes=state.creditNotes||[];if(!notes.length)return null;var rows=filtered(),all=notes.reduce(function(s,n){return s+(Number(n.amount)||0);},0),period=rows.reduce(function(s,n){return s+(Number(n.amount)||0);},0),to=A.text(state.creditNoteFilterTo||''),running=notes.filter(function(n){return!to||A.text(n.issueDate)<=to;}).reduce(function(s,n){return s+(Number(n.amount)||0);},0),months={};
      rows.forEach(function(n){var key=A.text(n.issueDate).slice(0,7)||'Undated';if(!months[key])months[key]={key:key,total:0,count:0};months[key].total+=Number(n.amount)||0;months[key].count++;});
      var el=document.createElement('div');el.className='credit-note-portfolio';el.id='creditNotePortfolio';el.innerHTML='<p class="section-label" style="margin:0 0 10px">Credit notes</p><div class="credit-note-portfolio-summary"><div><small>All time</small><strong>'+A.safe(A.money(all))+'</strong></div><div><small>Selected period</small><strong>'+A.safe(A.money(period))+'</strong></div><div><small>'+A.safe(to?'Running through '+A.dateLabel(to):'Running total to date')+'</small><strong>'+A.safe(A.money(running))+'</strong></div></div><div class="credit-note-filter-grid"><label class="brand-field">From<input type="date" id="creditNoteFrom" value="'+A.safe(state.creditNoteFilterFrom||'')+'" /></label><label class="brand-field">To<input type="date" id="creditNoteTo" value="'+A.safe(state.creditNoteFilterTo||'')+'" /></label><button class="btn-paper" type="button" id="creditNoteClear" style="margin:0">Clear</button></div><div class="stat-sub" style="margin:0 0 7px">'+rows.length+' credit note'+(rows.length===1?'':'s')+' in this period.</div>';
      var monthRows=Object.keys(months).sort().reverse().map(function(k){return months[k];});if(monthRows.length){var box=document.createElement('div');box.innerHTML='<p class="section-label" style="margin:10px 0 3px">By month</p>';monthRows.forEach(function(r){var item=document.createElement('div'),label=r.key;if(/^\d{4}-\d{2}$/.test(r.key)){var p=r.key.split('-');label=new Date(Number(p[0]),Number(p[1])-1,1).toLocaleDateString('en-US',{month:'short',year:'numeric'});}item.className='credit-note-month-row';item.innerHTML='<span>'+A.safe(label)+' · '+r.count+' note'+(r.count===1?'':'s')+'</span><strong>'+A.safe(A.money(r.total))+'</strong>';box.appendChild(item);});el.appendChild(box);}
      if(rows.length){var detail=document.createElement('div');detail.innerHTML='<p class="section-label" style="margin:13px 0 3px">Issued in period</p>';rows.slice().sort(function(a,b){return A.text(b.issueDate).localeCompare(A.text(a.issueDate))||Number(b.id||0)-Number(a.id||0);}).forEach(function(n){var c=owner(n),item=document.createElement('div');item.className='credit-note-portfolio-row';item.innerHTML='<div><div>'+A.safe(A.dateLabel(n.issueDate))+' · '+A.safe(c.unit||'Unit')+' · '+A.safe(n.stageLabel||'Installment')+'</div><div class="meta">'+A.safe(c.name||'')+(n.reason?' · '+A.safe(n.reason):'')+(n.reference?' · Ref '+A.safe(n.reference):'')+'</div></div><strong>'+A.safe(A.money(n.amount))+'</strong>';detail.appendChild(item);});el.appendChild(detail);}return el;
    }
    function decorate(){if(!window.state||state.view!=='insights'||!(state.creditNotes||[]).length)return;var o=document.querySelector('.overview');if(!o||document.getElementById('creditNotePortfolio'))return;var s=section();if(!s)return;o.insertBefore(s,o.firstChild);var f=document.getElementById('creditNoteFrom'),t=document.getElementById('creditNoteTo'),c=document.getElementById('creditNoteClear');if(f)f.addEventListener('change',function(){state.creditNoteFilterFrom=f.value;renderInsights();});if(t)t.addEventListener('change',function(){state.creditNoteFilterTo=t.value;renderInsights();});if(c)c.addEventListener('click',function(){state.creditNoteFilterFrom='';state.creditNoteFilterTo='';renderInsights();});}
    var base=window.renderInsights;window.renderInsights=function(){var out=base.apply(this,arguments);decorate();return out;};
    decorate();
  }
  install();
})();