(function(){
'use strict';
if(window.__sunblissDesktopExecutiveShellPreviewInstalled)return;
window.__sunblissDesktopExecutiveShellPreviewInstalled=true;

var MQ='(min-width:1024px)';
var observer=null,timer=null;
function desktop(){return window.matchMedia?window.matchMedia(MQ).matches:window.innerWidth>=1024}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function icon(name){
 var p={overview:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',units:'<path d="M4 20V8l8-4 8 4v12"/><path d="M9 20v-5h6v5M8 10h1M12 10h1M16 10h1"/>',insights:'<path d="M4 19V5"/><path d="M4 19h16"/><path d="M7 15l4-5 3 3 5-7"/>',tasks:'<path d="M9 6h11M9 12h11M9 18h11"/><path d="M4 6l1 1 2-2M4 12l1 1 2-2M4 18l1 1 2-2"/>',search:'<circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/>',add:'<path d="M12 5v14M5 12h14"/>'};
 return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(p[name]||p.overview)+'</svg>';
}
function styles(){
 if(document.getElementById('sunblissDesktopExecutiveShellPreviewStyles'))return;
 var s=document.createElement('style');s.id='sunblissDesktopExecutiveShellPreviewStyles';s.textContent=`
#sunblissDesktopSidebar,#sunblissDesktopUtility{display:none}
@media(min-width:1024px){
 body.sunbliss-desktop-exec-preview{background:#0c1018!important;background-image:radial-gradient(900px 500px at 12% -10%,rgba(198,151,46,.08),transparent 60%),radial-gradient(800px 480px at 100% 0%,rgba(92,174,166,.055),transparent 58%)!important;overflow-x:hidden}
 body.sunbliss-desktop-exec-preview #app{max-width:none!important;width:100%!important;margin:0!important;padding:20px 24px 120px 284px!important;contain:none!important;}
 #sunblissDesktopSidebar{display:flex;position:fixed;left:20px;top:20px;bottom:20px;width:240px;z-index:1150;flex-direction:column;padding:18px 14px;border:1px solid rgba(255,255,255,.06);border-radius:18px;background:linear-gradient(180deg,#121721 0%,#0f141d 100%);box-shadow:0 18px 44px rgba(0,0,0,.27);color:#f6f2e9}
 .sb-desk-brand{padding:4px 7px 20px;border-bottom:1px solid rgba(255,255,255,.07)}
 .sb-desk-brand-row{display:flex;align-items:center;gap:11px}.sb-desk-mark{width:37px;height:37px;display:grid;place-items:center;border-radius:11px;background:linear-gradient(145deg,#d2aa59,#9c7329);color:#10151e;font:750 17px/1 Georgia,serif;box-shadow:0 7px 18px rgba(198,151,46,.18)}
 .sb-desk-company{font:650 15px/1.1 Georgia,serif;letter-spacing:.045em;color:#e4b65d}.sb-desk-sub{margin-top:4px;font-size:7.5px;letter-spacing:.16em;color:#8d95a5}
 .sb-desk-project{margin:17px 5px 8px;padding:10px 11px;border-radius:11px;background:#191f2b;border:1px solid rgba(255,255,255,.06)}
 .sb-desk-project span{display:block;font-size:8px;letter-spacing:.09em;text-transform:uppercase;color:#778093}.sb-desk-project strong{display:block;margin-top:4px;font-size:11.5px;color:#e9edf4;font-weight:600}
 .sb-desk-nav-label{margin:16px 8px 7px;font-size:8px;letter-spacing:.12em;text-transform:uppercase;color:#667084}
 .sb-desk-nav{display:flex;flex-direction:column;gap:5px}.sb-desk-nav button{appearance:none;border:0;background:transparent;color:#8f98aa;border-radius:10px;min-height:43px;padding:0 11px;display:flex;align-items:center;gap:11px;text-align:left;font:550 11.5px/1 Inter,system-ui,sans-serif;cursor:pointer}
 .sb-desk-nav button svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.75;stroke-linecap:round;stroke-linejoin:round;flex:none}.sb-desk-nav button:hover{background:#1a202c;color:#e9edf4}.sb-desk-nav button.active{background:linear-gradient(90deg,rgba(198,151,46,.18),rgba(198,151,46,.07));color:#e7bc67;box-shadow:inset 3px 0 0 #c6972e}
 .sb-desk-nav button.sb-desk-add{margin-top:7px;background:#c6972e;color:#111722;font-weight:700}.sb-desk-nav button.sb-desk-add:hover{background:#d3a641;color:#111722}
 .sb-desk-side-foot{margin-top:auto;padding:13px 8px 3px;border-top:1px solid rgba(255,255,255,.07);font-size:8.5px;line-height:1.55;color:#636d80}.sb-desk-side-foot b{display:block;color:#949dad;font-weight:600}
 body.sunbliss-desktop-exec-preview .topbar.sunbliss-professional-header{width:100%!important;min-height:112px!important;margin:0!important;padding:18px 26px!important;border-radius:17px!important;border:1px solid rgba(255,255,255,.065)!important;background:linear-gradient(120deg,#121824 0%,#151c28 62%,#111821 100%)!important;box-shadow:0 14px 36px rgba(0,0,0,.22)!important;overflow:hidden!important}
 body.sunbliss-desktop-exec-preview .topbar.sunbliss-professional-header::after{display:none!important}body.sunbliss-desktop-exec-preview .topbar.sunbliss-professional-header::before{width:210px!important;height:210px!important;right:-80px!important;bottom:-142px!important;opacity:.7!important}
 body.sunbliss-desktop-exec-preview .sb-pro-top,body.sunbliss-desktop-exec-preview .sb-pro-main{max-width:none!important;width:100%!important;margin-left:0!important;margin-right:0!important}
 body.sunbliss-desktop-exec-preview .sb-pro-top{position:absolute!important;right:22px!important;top:18px!important;min-height:38px!important;width:auto!important}.sunbliss-desktop-exec-preview .sb-pro-brand{display:none!important}.sunbliss-desktop-exec-preview .sb-pro-actions{gap:8px!important}.sunbliss-desktop-exec-preview .sb-pro-signout{height:34px!important;border-radius:9px!important;font-size:9px!important;padding:0 11px!important}
 body.sunbliss-desktop-exec-preview .sb-pro-main{margin-top:0!important}.sunbliss-desktop-exec-preview .sb-pro-welcome{font-size:9.5px!important;margin:0 0 3px!important;color:#7f899b!important}.sunbliss-desktop-exec-preview .sb-pro-name{font-size:24px!important;letter-spacing:-.025em!important}.sunbliss-desktop-exec-preview .sb-pro-role{min-height:24px!important;font-size:8px!important;padding:0 8px!important}.sunbliss-desktop-exec-preview .sb-pro-project-row{margin-top:8px!important}.sunbliss-desktop-exec-preview .sb-pro-project{font-size:10.5px!important;color:#cbd1dc!important}.sunbliss-desktop-exec-preview .sb-pro-project-icon{width:25px!important;height:25px!important;border-radius:7px!important}.sunbliss-desktop-exec-preview .sb-pro-project-icon svg{width:13px!important;height:13px!important}.sunbliss-desktop-exec-preview .sb-pro-sync{height:25px!important;font-size:8px!important;border-radius:8px!important}
 #sunblissDesktopUtility{display:flex;width:100%;min-height:64px;margin:12px 0;align-items:center;gap:14px;padding:10px 12px 10px 16px;border:1px solid rgba(255,255,255,.06);border-radius:15px;background:#111722;box-shadow:0 10px 28px rgba(0,0,0,.16)}
 .sb-desk-search{position:relative;flex:1;max-width:640px}.sb-desk-search svg{position:absolute;left:14px;top:50%;transform:translateY(-50%);width:16px;height:16px;fill:none;stroke:#717b8d;stroke-width:2;pointer-events:none}.sb-desk-search input{width:100%;height:42px;border:1px solid #252d3b;border-radius:10px;background:#191f2b;color:#f2f5f8;padding:0 14px 0 40px;outline:none;font:500 12px Inter,system-ui,sans-serif}.sb-desk-search input::placeholder{color:#717a8b}.sb-desk-search input:focus{border-color:#8f7138;box-shadow:0 0 0 3px rgba(198,151,46,.08)}
 .sb-desk-utility-right{margin-left:auto;display:flex;align-items:center;gap:10px}.sb-desk-date{font-size:9px;line-height:1.4;color:#798396;text-align:right}.sb-desk-date strong{display:block;color:#d5dae3;font-size:10px}.sb-desk-mode{display:inline-flex;align-items:center;gap:6px;min-height:34px;padding:0 10px;border:1px solid #293140;border-radius:9px;background:#181e29;color:#98a2b4;font-size:8.5px;font-weight:600}.sb-desk-mode:before{content:'';width:6px;height:6px;border-radius:50%;background:#65c8b8;box-shadow:0 0 0 3px rgba(101,200,184,.08)}
 body.sunbliss-desktop-exec-preview main#main{width:100%!important;max-width:none!important;margin:0!important;min-height:calc(100vh - 228px)!important;border-radius:18px!important;overflow:visible!important;background:#f3efe5!important;box-shadow:0 14px 40px rgba(0,0,0,.22)!important}
 body.sunbliss-desktop-exec-preview .overview{padding:25px 27px 40px!important}.sb-desk-pagehead{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin:0 0 18px}.sb-desk-pagehead-copy h2{margin:0;color:#17202c;font:650 23px/1.1 Fraunces,Georgia,serif}.sb-desk-pagehead-copy p{margin:6px 0 0;color:#77705f;font-size:10.5px;line-height:1.45}.sb-desk-pagehead-badge{display:inline-flex;align-items:center;gap:6px;border:1px solid #d7ceb8;border-radius:999px;background:#ece5d5;padding:6px 9px;color:#6f6756;font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.05em}.sb-desk-pagehead-badge:before{content:'';width:6px;height:6px;border-radius:50%;background:#3f7a57}
 body.sunbliss-desktop-exec-preview .overview>.btn-paper#btnPrintReport{float:right!important;margin:-48px 0 18px!important;position:relative!important;z-index:3!important;background:#1a202b!important;border-color:#2a3240!important;color:#f4f6f9!important}
 body.sunbliss-desktop-exec-preview .stat-hero{clear:both!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important;padding:10px!important;background:#151b25!important;border:1px solid #262e3c!important;border-radius:15px!important;margin:0 0 22px!important;box-shadow:0 8px 22px rgba(15,26,38,.12)!important}
 body.sunbliss-desktop-exec-preview .stat-cell{min-height:105px!important;padding:17px 17px!important;background:#1d2330!important;border-radius:11px!important;color:#f4f6f9!important}.sunbliss-desktop-exec-preview .stat-cell.clickable:hover{background:#222a38!important}.sunbliss-desktop-exec-preview .stat-label{color:#929bad!important;font-size:8.5px!important}.sunbliss-desktop-exec-preview .stat-value{color:#f5f7fa!important;font-size:21px!important}.sunbliss-desktop-exec-preview .stat-sub{color:#9ea8b8!important;font-size:9px!important}.sunbliss-desktop-exec-preview .stat-cell.wide{grid-column:1/-1!important;min-height:auto!important;padding:12px 16px!important}.sunbliss-desktop-exec-preview .stat-cell .bar{background:#2d3441!important}.sunbliss-desktop-exec-preview .stat-cell .bar-fill{background:#70c7b8!important}.sunbliss-desktop-exec-preview .bar-caption{color:#8e98aa!important}.sunbliss-desktop-exec-preview .bar-caption b{color:#e8ecf2!important}
 body.sunbliss-desktop-exec-preview .section-label{margin:24px 2px 9px!important;font-size:9px!important;color:#7a725f!important;letter-spacing:.09em!important}.sunbliss-desktop-exec-preview .pipeline{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important;margin:0 0 18px!important}.sunbliss-desktop-exec-preview .pill-stat{min-width:0!important;padding:12px 13px!important;background:#faf7f0!important;border-color:#dcd3bd!important;border-radius:11px!important;box-shadow:0 3px 10px rgba(15,26,38,.035)!important}.sunbliss-desktop-exec-preview .pill-stat:hover{background:#fff!important}.sunbliss-desktop-exec-preview .pill-stat-num{font-size:17px!important}.sunbliss-desktop-exec-preview .cf-select-wrap{max-width:440px!important}.sunbliss-desktop-exec-preview .cf-summary{max-width:820px!important;border-radius:11px!important}.sunbliss-desktop-exec-preview .cf-tile{padding:14px!important}
 body.sunbliss-desktop-exec-preview #scheduledActionsOverview{margin-top:28px!important;padding:0 15px 15px!important;border-radius:14px!important;background:#faf7f0!important;box-shadow:0 5px 18px rgba(15,26,38,.045)!important}.sunbliss-desktop-exec-preview #scheduledActionsOverview .scheduled-overview-list{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:9px!important}.sunbliss-desktop-exec-preview #scheduledActionsOverview .scheduled-overview-row{min-height:80px!important;background:#f1ebdd!important}
 body.sunbliss-desktop-exec-preview .controls{padding:24px 27px 12px!important}.sunbliss-desktop-exec-preview .controls:before{content:'Customer & Unit Directory';display:block;margin:0 0 5px;color:#17202c;font:650 22px/1.15 Fraunces,Georgia,serif}.sunbliss-desktop-exec-preview .controls:after{content:'Search, filter and open any customer record from one desktop workspace.';display:block;margin:0 0 16px;color:#77705f;font-size:10px}.sunbliss-desktop-exec-preview .filter-toggle{max-width:320px!important}.sunbliss-desktop-exec-preview .list{padding:3px 24px 36px!important}.sunbliss-desktop-exec-preview .row-btn{gap:16px!important;padding:13px 14px!important;margin-bottom:7px!important;border:1px solid #ddd4bf!important;border-radius:10px!important;background:#faf7f0!important}.sunbliss-desktop-exec-preview .row-btn:hover{background:#fff!important;box-shadow:0 4px 12px rgba(15,26,38,.045)!important}.sunbliss-desktop-exec-preview .row-unit{min-width:72px!important;text-align:center!important}.sunbliss-desktop-exec-preview .row-amt{min-width:170px!important;max-width:220px!important}
 body.sunbliss-desktop-exec-preview .detail{max-width:none!important;margin:0!important;padding:25px 28px 42px!important}.sunbliss-desktop-exec-preview .d-name{font-size:25px!important}.sunbliss-desktop-exec-preview .money-grid{max-width:920px!important}.sunbliss-desktop-exec-preview .ledger-scroll{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important;overflow:visible!important;scroll-snap-type:none!important}.sunbliss-desktop-exec-preview .stage-card{width:auto!important;min-width:0!important;flex:none!important;background:#faf7f0!important}.sunbliss-desktop-exec-preview .tx-list{border:1px solid #ddd4bf!important;border-radius:11px!important;overflow:hidden!important;background:#faf7f0!important}.sunbliss-desktop-exec-preview .tx-row{padding:12px 14px!important}
 body.sunbliss-desktop-exec-preview .insights{padding:24px 28px 42px!important}.sunbliss-desktop-exec-preview .insights:before{content:'Management Insights';display:block;margin:0 0 5px;color:#17202c;font:650 22px/1.15 Fraunces,Georgia,serif}.sunbliss-desktop-exec-preview .stage-scroll .stage-tbl{min-width:760px!important}.sunbliss-desktop-exec-preview .insights svg{max-width:100%!important;height:auto!important}
 body.sunbliss-desktop-exec-preview #sunblissDockSearchPanel{top:94px!important;width:min(620px,calc(100vw - 340px))!important;left:calc(50% + 130px)!important}
}
@media(min-width:1380px){body.sunbliss-desktop-exec-preview #app{padding-right:32px!important}.sunbliss-desktop-exec-preview .ledger-scroll{grid-template-columns:repeat(5,minmax(0,1fr))!important}}
@media(min-width:1700px){.sunbliss-desktop-exec-preview .ledger-scroll{grid-template-columns:repeat(6,minmax(0,1fr))!important}}
`;
 document.head.appendChild(s)
}
function clickDock(selector){var el=document.querySelector('.tabs '+selector);if(el){el.click();return true}return false}
function route(view){return clickDock('.tab[data-view="'+view+'"]')}
function openTasks(){if(!route('overview'))return;setTimeout(function(){var n=document.getElementById('scheduledActionsOverview');if(n)n.scrollIntoView({behavior:'smooth',block:'start'})},90)}
function openAdd(){var b=document.querySelector('.tabs .dock-add');if(b)b.click()}
function openSearch(){var input=document.getElementById('sunblissDesktopSearch');if(input){try{input.focus({preventScroll:true})}catch(_e){input.focus()}}}
function syncSearch(value){
 if(window.state&&state.view!=='list')route('list');
 setTimeout(function(){var internal=document.getElementById('searchInput');if(!internal)return;if(internal.value!==value)internal.value=value;internal.dispatchEvent(new Event('input',{bubbles:true}))},45)
}
function sidebar(){
 var side=document.getElementById('sunblissDesktopSidebar');if(side)return side;
 side=document.createElement('aside');side.id='sunblissDesktopSidebar';side.setAttribute('aria-label','Desktop CRM navigation');
 side.innerHTML='<div class="sb-desk-brand"><div class="sb-desk-brand-row"><div class="sb-desk-mark">P</div><div><div class="sb-desk-company">PURVANCHAL</div><div class="sb-desk-sub">REAL ESTATE DEVELOPERS LLC</div></div></div></div><div class="sb-desk-project"><span>Active project</span><strong>Sunbliss Residences</strong></div><div class="sb-desk-nav-label">Workspace</div><div class="sb-desk-nav"><button data-route="overview">'+icon('overview')+'<span>Overview</span></button><button data-route="list">'+icon('units')+'<span>Units & Customers</span></button><button data-route="insights">'+icon('insights')+'<span>Insights</span></button><button data-route="tasks">'+icon('tasks')+'<span>Scheduled Actions</span></button><button data-route="search">'+icon('search')+'<span>Search</span></button><button class="sb-desk-add" data-route="add">'+icon('add')+'<span>Add Customer</span></button></div><div class="sb-desk-side-foot"><b>CRM Desktop Workspace</b>Optimized for management review and daily collections operations.</div>';
 side.querySelectorAll('button[data-route]').forEach(function(b){b.addEventListener('click',function(){var r=this.getAttribute('data-route');if(r==='tasks')openTasks();else if(r==='search')openSearch();else if(r==='add')openAdd();else route(r)})});
 document.body.appendChild(side);return side
}
function utility(){
 var app=document.getElementById('app'),header=app&&app.querySelector('.topbar');if(!app||!header)return null;
 var bar=document.getElementById('sunblissDesktopUtility');if(bar&&bar.parentNode===app)return bar;if(bar)bar.remove();
 bar=document.createElement('div');bar.id='sunblissDesktopUtility';
 var d=new Date(),date=d.toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short',year:'numeric'});
 bar.innerHTML='<div class="sb-desk-search">'+icon('search')+'<input id="sunblissDesktopSearch" type="search" autocomplete="off" placeholder="Search unit or customer name…" aria-label="Search unit or customer name"></div><div class="sb-desk-utility-right"><div class="sb-desk-date"><strong>'+esc(date)+'</strong>Sunbliss CRM workspace</div><div class="sb-desk-mode">Desktop View</div></div>';
 header.insertAdjacentElement('afterend',bar);
 var input=bar.querySelector('#sunblissDesktopSearch');input.addEventListener('input',function(){syncSearch(input.value)});
 return bar
}
function pageHeads(){
 var ov=document.querySelector('.overview');if(ov&&!ov.querySelector('.sb-desk-pagehead')){var h=document.createElement('div');h.className='sb-desk-pagehead';h.innerHTML='<div class="sb-desk-pagehead-copy"><h2>Portfolio Overview</h2><p>Sales, collections, compliance and follow-up activity at a glance.</p></div><span class="sb-desk-pagehead-badge">Live CRM</span>';ov.insertBefore(h,ov.firstChild)}
}
function syncActive(){
 var side=document.getElementById('sunblissDesktopSidebar');if(!side)return;var view=window.state&&state.view?state.view:'overview';if(view==='detail')view=(state.detailFrom==='overview'?'overview':'list');side.querySelectorAll('button[data-route]').forEach(function(b){var r=b.getAttribute('data-route');b.classList.toggle('active',r===view)})
}
function apply(){
 styles();var on=desktop();document.body.classList.toggle('sunbliss-desktop-exec-preview',on);if(!on)return;sidebar();utility();pageHeads();syncActive()
}
function schedule(){clearTimeout(timer);timer=setTimeout(apply,35)}
function init(){styles();apply();var app=document.getElementById('app');if(app&&window.MutationObserver&&!observer){observer=new MutationObserver(schedule);observer.observe(app,{childList:true,subtree:true})}window.addEventListener('resize',schedule,{passive:true});setTimeout(apply,200);setTimeout(apply,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
