(function(){
'use strict';
if(window.__sunblissDesktopReferenceExactV2)return;
window.__sunblissDesktopReferenceExactV2=true;
var MQ='(min-width:1024px)',timer=null,tasks=[],taskLoad=null,lastTaskLoad=0;
function desktop(){return window.matchMedia?window.matchMedia(MQ).matches:window.innerWidth>=1024}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function n(v){v=Number(v);return isFinite(v)?v:0}
function pct(v){return (Math.round(n(v)*10)/10).toFixed(1)+'%'}
function money(v){v=Math.abs(n(v));if(v>=1000000)return 'AED '+(Math.round(v/100000)/10).toFixed(1)+'M';if(v>=1000)return 'AED '+(Math.round(v/100)/10).toFixed(1)+'K';return 'AED '+Math.round(v).toLocaleString('en-AE')}
function icon(name){var p={
 building:'<path d="M5 21V7l7-3v17M12 21V9l7 2v10M2 21h20M8 10h1M8 14h1M15 13h1M15 17h1"/>',
 sales:'<ellipse cx="12" cy="6" rx="6" ry="3"/><path d="M6 6v6c0 1.7 2.7 3 6 3s6-1.3 6-3V6M6 12v5c0 1.7 2.7 3 6 3s6-1.3 6-3v-5"/>',
 hand:'<path d="M4 13h4l2 3h7a3 3 0 0 0 3-3v-1h-7l-2-2H7M4 13v7M15 4h4v5h-4zM16 6h2"/>',
 invoice:'<path d="M6 2h9l4 4v16H6zM14 2v5h5M9 11h7M9 15h5M9 19h4"/>',
 collection:'<path d="M4 18V7M4 18h16M7 14l3-4 3 2 4-6M17 6h3v3"/>',
 doc:'<path d="M6 2h9l4 4v16H6zM14 2v5h5M9 11h7M9 15h7"/>',
 sofa:'<path d="M5 12V9a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v3M4 12h16a2 2 0 0 1 2 2v5H2v-5a2 2 0 0 1 2-2zM5 19v2M19 19v2"/>',
 activity:'<circle cx="7" cy="8" r="2"/><circle cx="17" cy="8" r="2"/><path d="M3 18c0-3 2-5 4-5s4 2 4 5M13 18c0-3 2-5 4-5s4 2 4 5"/>',
 insights:'<path d="M4 19V12M9 19V7M14 19v-4M19 19V4"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18M8 14h3M13 14h3M8 17h3"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 arrow:'<path d="M5 12h14M14 7l5 5-5 5"/>',
 light:'<path d="M9 18h6M10 22h4M8 14a6 6 0 1 1 8 0c-1 1-1 2-1 3H9c0-1 0-2-1-3z"/>',
 bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',
 user:'<circle cx="12" cy="8" r="3"/><path d="M5 21c0-4 3-7 7-7s7 3 7 7"/>',
 register:'<path d="M5 3h14v18H5zM8 7h8M8 11h8M8 15h5"/>'
};return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(p[name]||p.doc)+'</svg>'}
function style(){if(document.getElementById('sunblissDesktopReferenceExactV2Styles'))return;var s=document.createElement('style');s.id='sunblissDesktopReferenceExactV2Styles';s.textContent=`
#sbRefOverviewV2{display:none}
@media(min-width:1024px){
 body.sunbliss-ref-desktop #app{padding-left:216px!important}
 #sbRefSidebar{width:216px!important;background:linear-gradient(180deg,var(--ink-2),#0b1a29)!important;border-right:1px solid rgba(198,151,46,.30)!important}
 .sb-ref-brand{height:145px!important;padding:19px 16px 17px!important}.sb-ref-brand strong{font-size:25px!important}.sb-ref-brand small{font-size:8px!important;letter-spacing:.18em!important}
 .sb-ref-nav{padding:0!important;gap:0!important}.sb-ref-nav button{height:51px!important;border-radius:0!important;padding:0 28px!important;gap:15px!important;font-size:13px!important}.sb-ref-nav button.active{background:rgba(237,230,214,.10)!important}.sb-ref-nav button.active:before{left:0!important;width:5px!important}.sb-ref-nav .sb-ref-add{margin:17px 16px 0!important;width:calc(100% - 32px)!important;height:44px!important;border-radius:10px!important;padding:0 17px!important}.sb-ref-side-bottom{margin:0 17px 0!important;margin-top:auto!important;padding:26px 7px 28px!important}
 body.sunbliss-ref-desktop .topbar.sunbliss-professional-header{height:214px!important;min-height:214px!important;padding:22px 26px 16px 45px!important;background:linear-gradient(110deg,#0b2035 0%,var(--ink-2) 56%,#0c2134 100%)!important}
 body.sunbliss-ref-desktop .topbar.sunbliss-professional-header:after{left:45px!important;right:66%!important;top:92px!important}
 body.sunbliss-ref-desktop .sb-pro-top{min-height:55px!important}.sb-pro-brand-name{font-size:29px!important}.sb-pro-brand-sub{font-size:8px!important;margin-top:7px!important}.sb-pro-main{margin-top:18px!important}.sb-pro-name{font-size:32px!important}.sb-pro-welcome{font-size:12px!important}.sb-pro-role{min-height:29px!important}.sb-pro-project-row{margin-top:11px!important}.sb-pro-project{font-size:13px!important}.sb-pro-project-icon{width:32px!important;height:32px!important}
 body.sunbliss-ref-desktop .sb-pro-sync{display:none!important}.sb-v2-sync{height:38px;display:flex;align-items:center;gap:7px;padding:0 13px;color:var(--cream-text);font:500 11px/1 Inter,sans-serif;border-right:1px solid rgba(237,230,214,.32);white-space:nowrap}.sb-v2-sync svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.8}.sb-pro-actions{right:0!important;top:-3px!important;gap:12px!important}.sb-pro-signout{height:38px!important;border-radius:8px!important;padding:0 16px!important;background:rgba(15,26,38,.22)!important}.sb-v2-tagline{position:absolute;right:34px;top:94px;z-index:3;width:124px;text-align:center;color:rgba(237,230,214,.78);font:italic 20px/1.05 cursive;transform:rotate(-5deg);text-shadow:0 2px 10px rgba(0,0,0,.25)}.sb-dubai-skyline{right:82px!important;width:48%!important;height:78%!important;bottom:-4px!important;opacity:.43!important}.sb-dubai-skyline:after{content:'';position:absolute;left:30%;right:0;bottom:0;height:30%;background:radial-gradient(ellipse at 72% 100%,rgba(198,151,46,.28),transparent 55%);pointer-events:none}
 body.sunbliss-ref-desktop main#main{min-height:calc(100vh - 214px)!important}.overview>:not(#sbRefOverview){display:none!important}.overview>#sbRefOverviewV2{display:block!important}#sbRefOverview{display:none!important}body.sunbliss-ref-desktop .overview{padding:0 25px 30px!important;background:#fff!important}
 #sbRefOverviewV2{padding:17px 0 0!important}.sb-v2-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.sb-v2-card{background:#fff;border:1px solid var(--paper-line);border-radius:10px;box-shadow:0 3px 14px rgba(15,26,38,.055)}
 .sb-v2-kpi{height:110px;display:grid;grid-template-columns:58px minmax(0,1fr) auto;align-items:center;gap:13px;padding:14px 17px;cursor:pointer}.sb-v2-kpi.units{background:linear-gradient(90deg,rgba(198,151,46,.055),rgba(198,151,46,.018))}.sb-v2-kpi.sales{background:linear-gradient(90deg,rgba(69,86,107,.045),rgba(69,86,107,.012))}.sb-v2-kpi.collected{background:linear-gradient(90deg,rgba(63,122,87,.055),rgba(63,122,87,.015))}.sb-v2-kpi.outstanding{background:linear-gradient(90deg,rgba(174,59,43,.045),rgba(174,59,43,.012))}.sb-v2-kpi-icon{width:50px;height:50px;border-radius:50%;display:grid;place-items:center}.sb-v2-kpi-icon svg{width:27px;height:27px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.units .sb-v2-kpi-icon{color:var(--gold-deep);background:rgba(198,151,46,.13)}.sales .sb-v2-kpi-icon{color:var(--slate);background:rgba(69,86,107,.11)}.collected .sb-v2-kpi-icon{color:var(--sage);background:rgba(63,122,87,.11)}.outstanding .sb-v2-kpi-icon{color:var(--rust);background:rgba(174,59,43,.10)}.sb-v2-kpi-label{font:700 10px/1.1 Inter,sans-serif;letter-spacing:.035em;text-transform:uppercase;color:var(--ink);margin-bottom:7px}.sb-v2-kpi-value{font:650 23px/1 Inter,sans-serif;letter-spacing:-.03em;color:var(--ink);white-space:nowrap}.sb-v2-kpi-sub{font:500 10.5px/1.2 Inter,sans-serif;color:var(--muted);margin-top:7px;white-space:nowrap}.sb-v2-trend{text-align:right;align-self:center;font:700 11px/1.25 Inter,sans-serif;color:var(--sage);white-space:nowrap}.sb-v2-trend.bad{color:var(--rust)}.sb-v2-trend small{display:block;margin-top:5px;font:500 8.5px/1 Inter,sans-serif;color:var(--muted)}
 .sb-v2-collection{height:111px;margin-top:12px;padding:13px 19px 14px}.sb-v2-head{height:28px;display:flex;align-items:flex-start;justify-content:space-between;gap:12px;border-bottom:1px solid rgba(220,210,182,.55);margin-bottom:10px}.sb-v2-title{display:flex;align-items:center;gap:9px;font:700 12px/1 Inter,sans-serif;color:var(--ink)}.sb-v2-title svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}.sb-v2-view{border:0;background:transparent;color:#3972a5;padding:1px 0;font:600 9.5px/1 Inter,sans-serif;cursor:pointer;display:flex;align-items:center;gap:5px}.sb-v2-view svg{width:13px;height:13px;fill:none;stroke:currentColor;stroke-width:1.8}.sb-v2-select{height:28px;border:1px solid var(--paper-line);background:#fff;border-radius:8px;padding:0 30px 0 10px;font:500 10px/1 Inter,sans-serif;color:var(--ink)}.sb-v2-bar{height:12px;border-radius:99px;background:rgba(198,151,46,.19);overflow:hidden}.sb-v2-bar i{display:block;height:100%;background:var(--sage);border-radius:99px}.sb-v2-bar-cap{display:flex;justify-content:space-between;margin-top:9px;font:500 10.5px/1 Inter,sans-serif;color:var(--muted)}.sb-v2-bar-cap b{font-size:13px}.sb-v2-bar-cap .good b{color:var(--sage)}.sb-v2-bar-cap .bad b{color:var(--rust)}
 .sb-v2-status-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;margin-top:12px}.sb-v2-status{height:121px;padding:13px 17px}.sb-v2-status .sb-v2-head{margin-bottom:6px}.sb-v2-status-body{height:65px;display:grid;grid-template-columns:repeat(3,1fr);align-items:center}.sb-v2-status-body.two{grid-template-columns:1fr 1fr}.sb-v2-status-cell{padding:3px 13px;border-left:1px solid rgba(220,210,182,.58);cursor:pointer}.sb-v2-status-cell:first-child{border-left:0}.sb-v2-status-cell strong{display:flex;align-items:center;gap:8px;font:650 18px/1 Inter,sans-serif;color:var(--ink)}.sb-v2-status-cell span{display:block;margin-top:7px;font:500 9.5px/1 Inter,sans-serif;color:var(--muted);white-space:nowrap}.sb-v2-dot{width:7px;height:7px;border-radius:50%;background:var(--muted);flex:none}.sb-v2-dot.good{background:var(--sage)}.sb-v2-dot.warn{background:#d3a021}.sb-v2-furn strong{justify-content:center}.sb-v2-furn span{text-align:center}
 .sb-v2-bottom{display:grid;grid-template-columns:1.45fr .95fr .95fr;gap:12px;margin-top:12px}.sb-v2-panel{height:225px;padding:13px 17px;overflow:hidden}.sb-v2-list{margin-top:-2px}.sb-v2-row{min-height:39px;display:grid;grid-template-columns:30px minmax(0,1fr) auto;align-items:center;gap:8px;border-bottom:1px solid rgba(220,210,182,.50);font:500 10.5px/1.25 Inter,sans-serif;color:var(--ink)}.sb-v2-row:last-child{border-bottom:0}.sb-v2-mini{width:28px;height:28px;border-radius:8px;display:grid;place-items:center}.sb-v2-mini svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8}.sb-v2-mini.green{background:rgba(63,122,87,.11);color:var(--sage)}.sb-v2-mini.blue{background:rgba(69,86,107,.11);color:var(--slate)}.sb-v2-mini.gold{background:rgba(198,151,46,.12);color:var(--gold-deep)}.sb-v2-mini.red{background:rgba(174,59,43,.10);color:var(--rust)}.sb-v2-time{font:500 9.5px/1 Inter,sans-serif;color:var(--muted);white-space:nowrap}.sb-v2-count{font:700 11px/1 Inter,sans-serif;color:var(--ink);min-width:18px;text-align:right}.sb-v2-action-row{min-height:40px;display:grid;grid-template-columns:18px minmax(0,1fr) auto;align-items:center;gap:8px;border-bottom:1px solid rgba(220,210,182,.50);font:500 10.5px/1.25 Inter,sans-serif;color:var(--ink)}.sb-v2-action-row:last-child{border-bottom:0}.sb-v2-box{width:14px;height:14px;border:1px solid #9da4aa;border-radius:3px;background:#fff;cursor:pointer}.sb-v2-priority{padding:7px 8px;border-radius:7px;font:700 8.5px/1 Inter,sans-serif}.sb-v2-priority.high{color:var(--rust);background:rgba(174,59,43,.10)}.sb-v2-priority.medium{color:var(--amber);background:rgba(156,90,18,.10)}.sb-v2-priority.low{color:var(--sage);background:rgba(63,122,87,.10)}.sb-v2-empty{padding:24px 4px;color:var(--muted);font:500 10.5px/1.45 Inter,sans-serif}
 @media(max-width:1180px){.sb-v2-kpi{grid-template-columns:48px 1fr;gap:10px}.sb-v2-trend{display:none}.sb-v2-kpi-icon{width:44px;height:44px}.sb-v2-kpi-value{font-size:19px}.sb-v2-status{padding-left:12px;padding-right:12px}.sb-v2-status-cell{padding-left:8px;padding-right:8px}.sb-v2-bottom{grid-template-columns:1.3fr 1fr 1fr}}
}
`;document.head.appendChild(s)}
function currentStats(){try{if(typeof window.portfolioStats==='function')return window.portfolioStats()}catch(e){}var dues=window.state&&Array.isArray(state.dues)?state.dues:[],sales=0,recv=0;dues.forEach(function(c){sales+=n(c.total);recv+=n(c.received)});return{units:dues.length,totalSales:sales,totalReceived:recv,totalOutstanding:sales-recv,collectedPct:sales?recv/sales*100:0,outstandingPct:sales?(sales-recv)/sales*100:0,spaCounts:{signed:0,drafted:0,none:0},oqoodCounts:{completed:0,pending:0,other:0,none:0},furnitureCounts:{furnished:0,unfurnished:0}}}
function trend(cur,prev,bad){if(!prev||!n(prev))return '<span class="sb-v2-trend'+(bad?' bad':'')+'">—<small>vs last month</small></span>';var d=(n(cur)-n(prev))/Math.abs(n(prev))*100;return '<span class="sb-v2-trend'+((bad&&d>0)||(!bad&&d<0)?' bad':'')+'">'+(d>=0?'↗ +':'↘ ')+Math.abs(Math.round(d))+'%<small>vs last month</small></span>'}
function dateObj(v){if(!v)return null;var d=v instanceof Date?v:new Date(v);return isNaN(d.getTime())?null:d}
function dayStart(d){d=new Date(d);d.setHours(0,0,0,0);return d}
function quick(k){var now=dayStart(new Date()),end=new Date(now);end.setDate(end.getDate()+7);var due=0,over=0;(window.state&&state.dues||[]).forEach(function(c){(c.stages||[]).forEach(function(s){var rem=n(s.outAmt);if(rem<=1)return;var d=dateObj(s.revisedDueDate||s.revised_due_date||s.dueDate||s.due_date);if(!d)return;d=dayStart(d);if(d<now)over++;else if(d<=end)due++})});var spa=k.spaCounts||{},oq=k.oqoodCounts||{};return{due:due,overdue:over,spa:n(spa.drafted)+n(spa.none),oqood:n(oq.pending)+n(oq.none)+n(oq.other)}}
function activityTime(v){var d=dateObj(v);if(!d)return '';var now=new Date(),a=dayStart(d),b=dayStart(now),diff=Math.round((b-a)/86400000),time=d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});if(diff===0)return 'Today '+time;if(diff===1)return 'Yesterday '+time;return d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}
function recentRows(){var rows=(window.state&&Array.isArray(state.recent)?state.recent:[]).slice().sort(function(a,b){var da=dateObj(a.date),db=dateObj(b.date);return (db?db.getTime():0)-(da?da.getTime():0)}).slice(0,4);if(!rows.length)return '<div class="sb-v2-empty">No recent activity is available yet.</div>';return rows.map(function(t,i){var cls=i===0?'green':'blue';return '<div class="sb-v2-row"><span class="sb-v2-mini '+cls+'">'+icon(i===0?'sales':'doc')+'</span><span>Payment received from Unit '+esc(t.unit||'—')+' · '+esc(t.name||'Customer')+'</span><span class="sb-v2-time">'+esc(activityTime(t.date))+'</span></div>'}).join('')}
function todayIso(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
async function loadTasks(force){if(!desktop()||!window.sb)return[];if(taskLoad)return taskLoad;if(!force&&Date.now()-lastTaskLoad<15000)return tasks;taskLoad=sb.from('scheduled_actions').select('id,unit_id,action_label,due_date,priority,status').eq('status','pending').eq('due_date',todayIso()).order('priority',{ascending:true}).order('id',{ascending:true}).then(function(r){taskLoad=null;lastTaskLoad=Date.now();if(!r.error)tasks=r.data||[];return tasks}).catch(function(){taskLoad=null;return tasks});return taskLoad}
function unitName(id){var c=(window.state&&Array.isArray(state.dues)?state.dues:[]).find(function(x){return Number(x&&x.sno)===Number(id)});return c?c.unit:''}
function actionRows(){if(!tasks.length)return '<div class="sb-v2-empty">No actions are scheduled for today.</div>';return tasks.slice(0,4).map(function(t){var p=String(t.priority||'Medium').toLowerCase(),u=unitName(t.unit_id);return '<div class="sb-v2-action-row"><button class="sb-v2-box" data-task="'+esc(t.id)+'" aria-label="Open scheduled action"></button><span>'+esc(t.action_label)+(u?' · Unit '+esc(u):'')+'</span><span class="sb-v2-priority '+esc(p)+'">'+esc(t.priority||'Medium')+'</span></div>'}).join('')}
function proxy(id){var el=document.getElementById(id);if(el)el.click()}
function goTasks(){var b=document.querySelector('#sbRefSidebar [data-action="tasks"]');if(b)b.click()}
function header(){if(!desktop())return;var h=document.querySelector('.topbar.sunbliss-professional-header');if(!h)return;var actions=h.querySelector('.sb-pro-actions');if(actions&&!actions.querySelector('.sb-v2-sync')){var d=document.createElement('div');d.className='sb-v2-sync';d.innerHTML=icon('clock')+'<span>Synced '+esc((window.state&&state.syncedAt)||'Just now')+'</span>';actions.insertBefore(d,actions.firstChild)}var t=h.querySelector('.sb-v2-tagline');if(!t){t=document.createElement('div');t.className='sb-v2-tagline';t.innerHTML='Building<br>Better<br>Tomorrows';h.appendChild(t)}}
function bind(root){root.querySelectorAll('[data-proxy]').forEach(function(el){el.onclick=function(){proxy(el.getAttribute('data-proxy'))}});root.querySelectorAll('[data-view]').forEach(function(el){el.onclick=function(){var v=el.getAttribute('data-view');if(v==='tasks')goTasks();else proxy(v)}});root.querySelectorAll('[data-task]').forEach(function(el){el.onclick=goTasks})}
function render(){if(!desktop())return;style();header();var host=document.querySelector('.overview');if(!host)return;var k=currentStats(),spa=k.spaCounts||{},oq=k.oqoodCounts||{},f=k.furnitureCounts||{},q=quick(k),prev=window.state&&state.prevSnapshot||null;var old=document.getElementById('sbRefOverviewV2');if(old)old.remove();var html='<div id="sbRefOverviewV2">'+
 '<div class="sb-v2-kpis">'+
  '<section class="sb-v2-card sb-v2-kpi units" data-proxy="btnUnitsSold"><span class="sb-v2-kpi-icon">'+icon('building')+'</span><div><div class="sb-v2-kpi-label">Units Sold</div><div class="sb-v2-kpi-value">'+esc(k.units)+'</div><div class="sb-v2-kpi-sub">Total units sold</div></div>'+trend(k.units,prev&&prev.units,false)+'</section>'+
  '<section class="sb-v2-card sb-v2-kpi sales" data-proxy="btnSalesValue"><span class="sb-v2-kpi-icon">'+icon('sales')+'</span><div><div class="sb-v2-kpi-label">Sales Value</div><div class="sb-v2-kpi-value">'+esc(money(k.totalSales))+'</div><div class="sb-v2-kpi-sub">Total sales value</div></div>'+trend(k.totalSales,prev&&prev.totalSales,false)+'</section>'+
  '<section class="sb-v2-card sb-v2-kpi collected" data-proxy="btnCollected"><span class="sb-v2-kpi-icon">'+icon('hand')+'</span><div><div class="sb-v2-kpi-label">Collected</div><div class="sb-v2-kpi-value">'+esc(money(k.totalReceived))+'</div><div class="sb-v2-kpi-sub">'+esc(pct(k.collectedPct))+' of sales</div></div>'+trend(k.totalReceived,prev&&prev.totalReceived,false)+'</section>'+
  '<section class="sb-v2-card sb-v2-kpi outstanding" data-proxy="btnOutstanding"><span class="sb-v2-kpi-icon">'+icon('invoice')+'</span><div><div class="sb-v2-kpi-label">Outstanding</div><div class="sb-v2-kpi-value">'+esc(money(k.totalOutstanding))+'</div><div class="sb-v2-kpi-sub">'+esc(pct(k.outstandingPct))+' of sales</div></div>'+trend(k.totalOutstanding,prev&&prev.totalOutstanding,true)+'</section>'+
 '</div>'+
 '<section class="sb-v2-card sb-v2-collection"><div class="sb-v2-head"><div class="sb-v2-title">'+icon('collection')+'<span>Collection Overview</span></div><select class="sb-v2-select" aria-label="Collection metric"><option>Sales Value</option></select></div><div class="sb-v2-bar"><i style="width:'+Math.min(n(k.collectedPct),100)+'%"></i></div><div class="sb-v2-bar-cap"><span class="good"><b>'+esc(pct(k.collectedPct))+'</b> Collected</span><span class="bad"><b>'+esc(pct(k.outstandingPct))+'</b> Outstanding</span></div></section>'+
 '<div class="sb-v2-status-grid">'+
  '<section class="sb-v2-card sb-v2-status"><div class="sb-v2-head"><div class="sb-v2-title">'+icon('doc')+'<span>SPA STATUS</span></div><button class="sb-v2-view" data-proxy="btnSpaSigned">View all '+icon('arrow')+'</button></div><div class="sb-v2-status-body"><div class="sb-v2-status-cell" data-proxy="btnSpaSigned"><strong><i class="sb-v2-dot good"></i>'+esc(spa.signed||0)+'</strong><span>Signed</span></div><div class="sb-v2-status-cell" data-proxy="btnSpaDrafted"><strong><i class="sb-v2-dot warn"></i>'+esc(spa.drafted||0)+'</strong><span>Drafted</span></div><div class="sb-v2-status-cell" data-proxy="btnSpaNotStarted"><strong><i class="sb-v2-dot"></i>'+esc(spa.none||0)+'</strong><span>Not started</span></div></div></section>'+
  '<section class="sb-v2-card sb-v2-status"><div class="sb-v2-head"><div class="sb-v2-title">'+icon('doc')+'<span>OQOOD STATUS</span></div><button class="sb-v2-view" data-proxy="btnOqoodCompleted">View all '+icon('arrow')+'</button></div><div class="sb-v2-status-body"><div class="sb-v2-status-cell" data-proxy="btnOqoodCompleted"><strong><i class="sb-v2-dot good"></i>'+esc(oq.completed||0)+'</strong><span>Completed</span></div><div class="sb-v2-status-cell" data-proxy="btnOqoodPending"><strong><i class="sb-v2-dot warn"></i>'+esc(oq.pending||0)+'</strong><span>Pending</span></div><div class="sb-v2-status-cell" data-proxy="btnOqoodNotStarted"><strong><i class="sb-v2-dot"></i>'+esc(n(oq.none)+n(oq.other))+'</strong><span>Not started</span></div></div></section>'+
  '<section class="sb-v2-card sb-v2-status"><div class="sb-v2-head"><div class="sb-v2-title">'+icon('sofa')+'<span>FURNISHING TYPE</span></div><button class="sb-v2-view" data-proxy="btnFurnished">View all '+icon('arrow')+'</button></div><div class="sb-v2-status-body two sb-v2-furn"><div class="sb-v2-status-cell" data-proxy="btnFurnished"><strong>'+esc(f.furnished||0)+'</strong><span>Fully Furnished</span></div><div class="sb-v2-status-cell" data-proxy="btnUnfurnished"><strong>'+esc(f.unfurnished||0)+'</strong><span>Semi Furnished</span></div></div></section>'+
 '</div>'+
 '<div class="sb-v2-bottom">'+
  '<section class="sb-v2-card sb-v2-panel"><div class="sb-v2-head"><div class="sb-v2-title">'+icon('activity')+'<span>Recent Activity</span></div><button class="sb-v2-view" data-proxy="btnUnitsSold">View all '+icon('arrow')+'</button></div><div class="sb-v2-list">'+recentRows()+'</div></section>'+
  '<section class="sb-v2-card sb-v2-panel"><div class="sb-v2-head"><div class="sb-v2-title">'+icon('insights')+'<span>Quick Insights</span></div></div><div class="sb-v2-list"><div class="sb-v2-row"><span class="sb-v2-mini gold">'+icon('light')+'</span><span>Payments due within next 7 days</span><b class="sb-v2-count">'+q.due+'</b></div><div class="sb-v2-row"><span class="sb-v2-mini red">'+icon('bell')+'</span><span>Overdue payments require attention</span><b class="sb-v2-count">'+q.overdue+'</b></div><div class="sb-v2-row"><span class="sb-v2-mini blue">'+icon('user')+'</span><span>Customers pending SPA signature</span><b class="sb-v2-count">'+q.spa+'</b></div><div class="sb-v2-row"><span class="sb-v2-mini green">'+icon('register')+'</span><span>Customers pending Oqood registration</span><b class="sb-v2-count">'+q.oqood+'</b></div></div></section>'+
  '<section class="sb-v2-card sb-v2-panel"><div class="sb-v2-head"><div class="sb-v2-title">'+icon('calendar')+'<span>Today\'s Actions</span></div><button class="sb-v2-view" data-view="tasks">View all '+icon('arrow')+'</button></div><div id="sbV2Actions" class="sb-v2-list">'+actionRows()+'</div></section>'+
 '</div></div>';host.insertAdjacentHTML('afterbegin',html);var root=document.getElementById('sbRefOverviewV2');bind(root);loadTasks(false).then(function(){var a=document.getElementById('sbV2Actions');if(a){a.innerHTML=actionRows();bind(a)}})}
function schedule(ms){clearTimeout(timer);timer=setTimeout(render,ms==null?0:ms)}
function install(){style();var ready=window.state&&typeof window.renderOverview==='function'&&typeof window.renderMain==='function';if(!ready){setTimeout(install,80);return}if(!window.renderOverview.__sbExactV2){var ro=window.renderOverview;window.renderOverview=function(){var x=ro.apply(this,arguments);schedule(0);return x};window.renderOverview.__sbExactV2=true}if(!window.renderMain.__sbExactV2){var rm=window.renderMain;window.renderMain=function(){var x=rm.apply(this,arguments);schedule(0);return x};window.renderMain.__sbExactV2=true}window.addEventListener('resize',function(){schedule(80)});window.addEventListener('pageshow',function(){loadTasks(true).then(function(){schedule(0)})});schedule(0);setTimeout(function(){schedule(0)},150);setTimeout(function(){schedule(0)},600)}
install();
})();