(function(){
'use strict';
if(window.__sunblissDetailActionUnificationInstalled)return;
window.__sunblissDetailActionUnificationInstalled=true;
var timer=null,token=0,busy=false,mutating=false;
function text(v){return v==null?'':String(v)}
function norm(v){return text(v).toLowerCase().replace(/instalment/g,'installment').replace(/\(spa\)/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function current(){if(!window.state||state.view!=='detail'||!state.selectedUnit||!Array.isArray(state.dues))return null;return state.dues.find(function(c){return c&&(text(c.unit)+'::'+text(c.sno))===text(state.selectedUnit)})||null}
function idsFromTask(t){var out=[];if(t&&t.schedule_id!=null)out.push(Number(t.schedule_id));var m=text(t&&t.auto_key).match(/\|schedules?:([0-9,]+)/);if(m)m[1].split(',').forEach(function(v){var n=Number(v);if(n>0&&out.indexOf(n)<0)out.push(n)});return out}
function isAutomaticPayment(t){if(!t||t.status!=='pending'||text(t.source).toLowerCase()==='manual'||text(t.auto_kind).toLowerCase()==='extension_active')return false;var s=norm([t.auto_kind,t.action_label,t.note,t.auto_key].join(' '));return idsFromTask(t).length>0||/(payment|installment|demand|reminder|outstanding|overdue|receipt|collection|charges)/.test(s)}
function stageMatches(cardText,row){var stage=norm(row&&row.stage_name);if(!stage)return false;var card=norm(cardText);if(card.indexOf(stage)>=0)return true;if(stage.indexOf('dld')>=0&&stage.indexOf('admin')>=0&&card.indexOf('dld admin fees')>=0)return true;return false}
function removeLegacyBar(){var bar=document.getElementById('actionRequiredFollowupBar');if(bar)bar.remove()}
function restoreUnified(section,exceptId){if(!section)return;section.querySelectorAll('.scheduled-task-card[data-unified-action="true"]').forEach(function(el){if(exceptId!=null&&text(el.getAttribute('data-task-id'))===text(exceptId))return;el.style.display='';el.removeAttribute('data-unified-action')})}
function updateSection(section){if(!section)return;var visible=[].slice.call(section.querySelectorAll('.scheduled-task-card')).filter(function(el){return el.style.display!=='none'});if(!visible.length){section.style.display='none';return}section.style.display='';var count=section.querySelector('.scheduled-actions-count');if(count)count.textContent=visible.length+' pending';var label=section.querySelector('.section-label');if(label)label.textContent='Scheduled Action'+(visible.length>1?'s':'')}
function unify(card,section,tasks,rows){if(!card||!section)return null;var cardText=text(card.textContent);if(!cardText.trim())return null;var byId={};(rows||[]).forEach(function(r){byId[String(r.id)]=r});var matches=(tasks||[]).filter(isAutomaticPayment).filter(function(t){return idsFromTask(t).some(function(id){return stageMatches(cardText,byId[String(id)])})});mutating=true;try{removeLegacyBar();if(matches.length!==1){restoreUnified(section,null);updateSection(section);return false}var task=matches[0],taskCard=section.querySelector('.scheduled-task-card[data-task-id="'+task.id+'"]');if(!taskCard)return null;restoreUnified(section,task.id);taskCard.style.display='none';taskCard.setAttribute('data-unified-action','true');updateSection(section);return true}finally{mutating=false}}
function applyCached(){if(mutating||busy)return false;var c=current(),card=document.getElementById('actionRequiredCard'),section=document.getElementById('scheduledActionsDetail');removeLegacyBar();if(!c||!card||card.hidden||card.getAttribute('aria-hidden')==='true')return false;if(!section)return true;var P=window.PaymentExtensionsCore,C=P&&P.cache;if(!C||!C.loaded||!Array.isArray(C.t)||!Array.isArray(C.s)){return false}var tasks=C.t.filter(function(t){return Number(t&&t.unit_id)===Number(c.sno)&&t.status==='pending'}),rows=C.s.filter(function(r){return Number(r&&r.unit_id)===Number(c.sno)});var resolved=unify(card,section,tasks,rows);section.removeAttribute('data-unification-pending');return resolved!==null}
async function apply(){var run=++token,c=current(),card=document.getElementById('actionRequiredCard'),section=document.getElementById('scheduledActionsDetail');removeLegacyBar();if(!c||!card||card.hidden||card.getAttribute('aria-hidden')==='true')return;if(!section)return;var cardText=text(card.textContent);if(!cardText.trim())return;try{busy=true;var q=await sb.from('scheduled_actions').select('id,unit_id,action_label,note,status,source,auto_kind,auto_key,schedule_id').eq('unit_id',Number(c.sno)).eq('status','pending');if(run!==token||!current()||Number(current().sno)!==Number(c.sno))return;if(q.error)throw q.error;var tasks=(q.data||[]).filter(isAutomaticPayment),ids=[];tasks.forEach(function(t){idsFromTask(t).forEach(function(id){if(ids.indexOf(id)<0)ids.push(id)})});if(!tasks.length||!ids.length){mutating=true;try{restoreUnified(section,null);removeLegacyBar();updateSection(section);section.removeAttribute('data-unification-pending')}finally{mutating=false}return}section.setAttribute('data-unification-pending','true');var p=await sb.from('payment_schedule').select('id,stage_name').in('id',ids);if(run!==token||!current()||Number(current().sno)!==Number(c.sno))return;if(p.error)throw p.error;unify(card,section,tasks,p.data||[])}catch(e){console.warn('Could not unify duplicate payment follow-up card',e)}finally{busy=false;var live=document.getElementById('scheduledActionsDetail');if(live)live.removeAttribute('data-unification-pending')}}
function ensureStyle(){if(document.getElementById('detailActionUnificationStyles'))return;var s=document.createElement('style');s.id='detailActionUnificationStyles';s.textContent='#scheduledActionsDetail[data-unification-pending="true"]{visibility:hidden!important}#actionRequiredFollowupBar{display:none!important}';document.head.appendChild(s)}
function schedule(ms){clearTimeout(timer);timer=setTimeout(function(){if(!busy){if(!applyCached())apply()}},ms==null?30:ms)}
function relevantMutation(m){var t=m&&m.target;if(!t)return false;if(t.id==='actionRequiredCard'||t.id==='scheduledActionsDetail')return true;if(t.closest&&(t.closest('#actionRequiredCard')||t.closest('#scheduledActionsDetail')))return true;for(var i=0;i<(m.addedNodes||[]).length;i++){var n=m.addedNodes[i];if(n&&n.nodeType===1&&(n.id==='scheduledActionsDetail'||n.id==='actionRequiredCard'||(n.querySelector&&(n.querySelector('#scheduledActionsDetail')||n.querySelector('#actionRequiredCard')))))return true}return false}
function install(){ensureStyle();removeLegacyBar();if(!window.state||!window.sb){setTimeout(install,80);return}var obs=new MutationObserver(function(ms){if(mutating||busy)return;removeLegacyBar();for(var i=0;i<ms.length;i++){if(relevantMutation(ms[i])){if(!applyCached())schedule(0);break}}});obs.observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',function(e){if(e.target&&e.target.closest&&e.target.closest('.unit-row,.scheduled-mark-done,#saComplete,#saSave,#saCancelTask'))schedule(120)},true);window.addEventListener('pageshow',function(){removeLegacyBar();if(!applyCached())schedule(20)});if(!applyCached())schedule(20)}
install();
})();
