(function(){
'use strict';
if(window.__sunblissDetailActionUnificationInstalled)return;
window.__sunblissDetailActionUnificationInstalled=true;
var timer=null,token=0,busy=false;
function text(v){return v==null?'':String(v)}
function norm(v){return text(v).toLowerCase().replace(/instalment/g,'installment').replace(/\(spa\)/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function current(){if(!window.state||state.view!=='detail'||!state.selectedUnit||!Array.isArray(state.dues))return null;return state.dues.find(function(c){return c&&(text(c.unit)+'::'+text(c.sno))===text(state.selectedUnit)})||null}
function idsFromTask(t){var out=[];if(t&&t.schedule_id!=null)out.push(Number(t.schedule_id));var m=text(t&&t.auto_key).match(/\|schedules?:([0-9,]+)/);if(m)m[1].split(',').forEach(function(v){var n=Number(v);if(n>0&&out.indexOf(n)<0)out.push(n)});return out}
function isAutomaticPayment(t){if(!t||t.status!=='pending'||text(t.source).toLowerCase()==='manual'||text(t.auto_kind).toLowerCase()==='extension_active')return false;var s=norm([t.auto_kind,t.action_label,t.note,t.auto_key].join(' '));return idsFromTask(t).length>0||/(payment|installment|demand|reminder|outstanding|overdue|receipt|collection|charges)/.test(s)}
function clean(){document.querySelectorAll('.scheduled-task-card[data-unified-action="true"]').forEach(function(el){el.style.display='';el.removeAttribute('data-unified-action')});var section=document.getElementById('scheduledActionsDetail');if(section)section.style.display='';var bar=document.getElementById('actionRequiredFollowupBar');if(bar)bar.remove()}
function stageMatches(cardText,row){var stage=norm(row&&row.stage_name);if(!stage)return false;var card=norm(cardText);if(card.indexOf(stage)>=0)return true;if(stage.indexOf('dld')>=0&&stage.indexOf('admin')>=0&&card.indexOf('dld admin fees')>=0)return true;return false}
function updateSection(section){if(!section)return;var visible=[].slice.call(section.querySelectorAll('.scheduled-task-card')).filter(function(el){return el.style.display!=='none'});if(!visible.length){section.style.display='none';return}section.style.display='';var count=section.querySelector('.scheduled-actions-count');if(count)count.textContent=visible.length+' pending';var label=section.querySelector('.section-label');if(label)label.textContent='Scheduled Action'+(visible.length>1?'s':'')}
function addFollowupBar(card,task){var old=document.getElementById('actionRequiredFollowupBar');if(old)old.remove();var row=document.createElement('div');row.id='actionRequiredFollowupBar';row.className='action-required-followup-bar';row.innerHTML='<div class="action-required-followup-copy"><span class="action-required-followup-label">Follow-up</span><span class="action-required-followup-auto">Automatic</span></div><button type="button" class="action-required-followup-done">Mark Done</button>';var btn=row.querySelector('button');btn.onclick=function(e){e.preventDefault();e.stopPropagation();var original=document.querySelector('.scheduled-task-card[data-task-id="'+task.id+'"] .scheduled-mark-done');if(original)original.click()};card.appendChild(row)}
async function apply(){var run=++token,c=current(),card=document.getElementById('actionRequiredCard'),section=document.getElementById('scheduledActionsDetail');clean();if(!c||!card||card.hidden||card.getAttribute('aria-hidden')==='true'||!section||!window.sb)return;var cardText=text(card.textContent);if(!cardText.trim())return;try{busy=true;var q=await sb.from('scheduled_actions').select('id,unit_id,action_label,note,status,source,auto_kind,auto_key,schedule_id').eq('unit_id',Number(c.sno)).eq('status','pending');if(run!==token||!current()||Number(current().sno)!==Number(c.sno))return;if(q.error)throw q.error;var tasks=(q.data||[]).filter(isAutomaticPayment),ids=[];tasks.forEach(function(t){idsFromTask(t).forEach(function(id){if(ids.indexOf(id)<0)ids.push(id)})});if(!tasks.length||!ids.length)return;var p=await sb.from('payment_schedule').select('id,stage_name').in('id',ids);if(run!==token||!current()||Number(current().sno)!==Number(c.sno))return;if(p.error)throw p.error;var byId={};(p.data||[]).forEach(function(r){byId[String(r.id)]=r});var matches=tasks.filter(function(t){return idsFromTask(t).some(function(id){return stageMatches(cardText,byId[String(id)])})});
if(matches.length!==1)return;var task=matches[0],taskCard=section.querySelector('.scheduled-task-card[data-task-id="'+task.id+'"]');if(!taskCard)return;taskCard.style.display='none';taskCard.setAttribute('data-unified-action','true');addFollowupBar(card,task);updateSection(section)}catch(e){console.warn('Could not unify duplicate payment follow-up card',e)}finally{busy=false}}
function ensureStyle(){if(document.getElementById('detailActionUnificationStyles'))return;var s=document.createElement('style');s.id='detailActionUnificationStyles';s.textContent='.action-required-followup-bar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:12px -1px -1px;padding:11px 1px 0;border-top:1px solid var(--paper-line,#d8cfb7)}.action-required-followup-copy{display:flex;align-items:center;gap:7px;min-width:0}.action-required-followup-label{font:650 11px/1.25 Inter,Arial,sans-serif;color:var(--ink,#172331)}.action-required-followup-auto{display:inline-flex;align-items:center;border:1px solid rgba(176,128,25,.42);border-radius:999px;padding:3px 7px;font:700 8.5px/1 IBM Plex Mono,monospace;letter-spacing:.04em;text-transform:uppercase;color:var(--gold-deep,#9b6b0c);background:rgba(207,158,38,.07)}.action-required-followup-done{border:0;background:transparent;padding:5px 0;font:700 11px/1.2 Inter,Arial,sans-serif;color:var(--gold-deep,#9b6b0c);cursor:pointer;white-space:nowrap}@media(max-width:520px){.action-required-followup-bar{margin-top:10px;padding-top:10px}}';document.head.appendChild(s)}
function schedule(ms){clearTimeout(timer);timer=setTimeout(function(){if(!busy)apply()},ms==null?80:ms)}
function install(){ensureStyle();if(!window.state||!window.sb){setTimeout(install,80);return}var obs=new MutationObserver(function(m){if(busy)return;for(var i=0;i<m.length;i++){var t=m[i].target;if(t&&(t.id==='actionRequiredCard'||t.id==='scheduledActionsDetail'||(t.closest&&(t.closest('#actionRequiredCard')||t.closest('#scheduledActionsDetail'))))){schedule(60);break}}});obs.observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',function(e){if(e.target&&e.target.closest&&e.target.closest('.unit-row,.scheduled-mark-done,#saComplete,#saSave,#saCancelTask'))schedule(180)},true);window.addEventListener('pageshow',function(){schedule(120)});schedule(120)}
install();
})();
