(function(){
  'use strict';
  if(document.getElementById('sunblissMobileInsightsCardsStyle'))return;

  var style=document.createElement('style');
  style.id='sunblissMobileInsightsCardsStyle';
  style.textContent=[
    '@media(max-width:1023px){',

      '/* Credit notes issued: one framed card with a compact heading strip. */',
      '#creditNotePortfolio.credit-note-mini{',
        'margin:0 0 22px!important;',
        'border:1px solid var(--paper-line)!important;',
        'border-radius:14px!important;',
        'background:var(--paper)!important;',
        'box-shadow:0 2px 8px rgba(15,26,38,.035)!important;',
        'overflow:hidden!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-toggle{',
        'display:grid!important;',
        'grid-template-columns:20px minmax(0,1fr) auto!important;',
        'grid-template-rows:44px minmax(70px,auto)!important;',
        'column-gap:10px!important;',
        'width:100%!important;',
        'min-height:114px!important;',
        'padding:0 14px!important;',
        'border:0!important;',
        'background:linear-gradient(to bottom,rgba(235,227,206,.72) 0 43px,var(--paper-line) 43px 44px,transparent 44px 100%)!important;',
        'text-align:left!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-toggle>div{display:contents!important;}',
      '#creditNotePortfolio .credit-note-mini-toggle::before{',
        'content:"";',
        'grid-column:1;grid-row:1;',
        'align-self:center;justify-self:start;',
        'width:17px;height:17px;',
        'background-repeat:no-repeat;background-position:center;background-size:17px 17px;',
        'background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 24 24%27 fill=%27none%27 stroke=%27%2316232F%27 stroke-width=%271.8%27 stroke-linecap=%27round%27 stroke-linejoin=%27round%27%3E%3Cpath d=%27M6 2h8l4 4v16H6z%27/%3E%3Cpath d=%27M14 2v5h5M9 11h6M9 15h5%27/%3E%3C/svg%3E");',
        'opacity:.88;',
      '}',
      '#creditNotePortfolio .credit-note-mini-label{',
        'grid-column:2;grid-row:1;',
        'align-self:center;',
        'margin:0!important;',
        'font:600 10px/1.2 IBM Plex Mono,monospace!important;',
        'letter-spacing:.065em!important;',
        'text-transform:uppercase!important;',
        'color:var(--ink)!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-total{',
        'grid-column:1/3;grid-row:2;',
        'align-self:center;',
        'font-family:Fraunces,serif!important;',
        'font-size:25px!important;',
        'line-height:1.05!important;',
        'font-weight:700!important;',
        'color:var(--ink)!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-arrow{',
        'grid-column:3;grid-row:2;',
        'align-self:center;justify-self:end;',
        'font-size:20px!important;',
        'color:var(--muted)!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-detail{border-top:1px solid var(--paper-line)!important;}',

      '/* Unit mix: visually join the heading and existing rows without changing data or markup. */',
      '.overview>.section-label:has(+ div>.mix-row){',
        'display:flex!important;align-items:center!important;gap:10px!important;',
        'min-height:44px!important;',
        'margin:22px 0 0!important;',
        'padding:0 14px!important;',
        'border:1px solid var(--paper-line)!important;',
        'border-radius:14px 14px 0 0!important;',
        'background:linear-gradient(180deg,rgba(235,227,206,.72),rgba(246,241,228,.94))!important;',
        'box-shadow:0 2px 8px rgba(15,26,38,.025)!important;',
        'color:var(--ink)!important;',
        'font-family:IBM Plex Mono,monospace!important;',
        'font-size:10px!important;font-weight:600!important;line-height:1.2!important;',
        'letter-spacing:.065em!important;text-transform:uppercase!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)::before{',
        'content:"";display:block;flex:0 0 17px;width:17px;height:17px;',
        'background-repeat:no-repeat;background-position:center;background-size:17px 17px;',
        'background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 24 24%27 fill=%27none%27 stroke=%27%2316232F%27 stroke-width=%271.8%27 stroke-linecap=%27round%27%3E%3Cpath d=%27M5 20V13M12 20V8M19 20V4%27/%3E%3C/svg%3E");',
        'opacity:.82;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div{',
        'margin:0 0 22px!important;',
        'border:1px solid var(--paper-line)!important;border-top:0!important;',
        'border-radius:0 0 14px 14px!important;',
        'background:var(--paper)!important;',
        'overflow:hidden!important;',
        'box-shadow:0 2px 8px rgba(15,26,38,.025)!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row{',
        'display:grid!important;',
        'grid-template-columns:.72fr 1fr 1fr!important;',
        'align-items:center!important;',
        'min-height:48px!important;',
        'padding:0!important;',
        'border-bottom:1px solid var(--paper-line)!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row:last-child{border-bottom:0!important;}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>span{padding:12px 14px!important;min-width:0!important;}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>.mix-label{',
        'font:700 13px/1.25 IBM Plex Mono,monospace!important;color:var(--ink)!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>.mix-count{',
        'border-left:1px solid rgba(220,210,182,.72)!important;',
        'font:400 11.5px/1.25 IBM Plex Mono,monospace!important;color:var(--muted)!important;text-align:center!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>.mix-value{',
        'border-left:1px solid rgba(220,210,182,.72)!important;',
        'font:500 12px/1.25 IBM Plex Mono,monospace!important;color:var(--ink)!important;text-align:right!important;white-space:nowrap!important;',
      '}',

      '/* Collection by stage: same heading-cell language, existing swipe/table behavior retained. */',
      '.overview>.section-label:has(+ .stage-scroll){',
        'display:flex!important;align-items:center!important;gap:10px!important;',
        'min-height:44px!important;',
        'margin:22px 0 0!important;',
        'padding:0 14px!important;',
        'border:1px solid var(--paper-line)!important;',
        'border-radius:14px 14px 0 0!important;',
        'background:linear-gradient(180deg,rgba(235,227,206,.72),rgba(246,241,228,.94))!important;',
        'box-shadow:0 2px 8px rgba(15,26,38,.025)!important;',
        'color:var(--ink)!important;',
        'font-family:IBM Plex Mono,monospace!important;',
        'font-size:10px!important;font-weight:600!important;line-height:1.2!important;',
        'letter-spacing:.055em!important;text-transform:uppercase!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)::before{',
        'content:"";display:block;flex:0 0 17px;width:17px;height:17px;',
        'background-repeat:no-repeat;background-position:center;background-size:17px 17px;',
        'background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 24 24%27 fill=%27none%27 stroke=%27%2316232F%27 stroke-width=%271.8%27 stroke-linecap=%27round%27 stroke-linejoin=%27round%27%3E%3Cpath d=%27M6 2h8l4 4v16H6z%27/%3E%3Cpath d=%27M14 2v5h5M9 11h6M9 15h6M9 19h4%27/%3E%3C/svg%3E");',
        'opacity:.88;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll{',
        'margin:0 0 10px!important;',
        'border:1px solid var(--paper-line)!important;border-top:0!important;',
        'border-radius:0 0 14px 14px!important;',
        'background:var(--paper)!important;',
        'box-shadow:0 2px 8px rgba(15,26,38,.025)!important;',
        'overflow-x:auto!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl{',
        'min-width:460px!important;',
        'margin:0!important;',
        'background:var(--paper)!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl th{',
        'padding:11px 12px!important;',
        'border-bottom:1px solid var(--paper-line)!important;',
        'font-size:9px!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl td{',
        'padding:11px 12px!important;',
        'border-top:1px solid var(--paper-line)!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl tbody tr:first-child td{border-top:0!important;}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl td:first-child{font-size:12.5px!important;}',
    '}'
  ].join('');
  document.head.appendChild(style);
})();
