(function(){
  'use strict';
  if(document.getElementById('sunblissMobileInsightsCardsStyle'))return;

  var style=document.createElement('style');
  style.id='sunblissMobileInsightsCardsStyle';
  style.textContent=[
    '@media(max-width:1023px){',

      '/* Credit Notes Issued — match approved reference card with tighter mobile scale. */',
      '#creditNotePortfolio.credit-note-mini{',
        'margin:0 0 10px!important;',
        'border:1px solid var(--paper-line)!important;',
        'border-radius:16px!important;',
        'background:var(--paper)!important;',
        'box-shadow:0 2px 9px rgba(15,26,38,.045)!important;',
        'overflow:hidden!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-toggle{',
        'display:grid!important;',
        'grid-template-columns:21px minmax(0,1fr) 24px!important;',
        'grid-template-rows:44px 70px!important;',
        'column-gap:11px!important;',
        'width:100%!important;',
        'min-height:114px!important;',
        'padding:0 16px!important;',
        'border:0!important;',
        'background:linear-gradient(to bottom,rgba(235,227,206,.72) 0 43px,var(--paper-line) 43px 44px,var(--paper) 44px 100%)!important;',
        'text-align:left!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-toggle>div{display:contents!important;}',
      '#creditNotePortfolio .credit-note-mini-toggle::before{',
        'content:"";grid-column:1;grid-row:1;align-self:center;justify-self:start;',
        'width:18px;height:18px;background-repeat:no-repeat;background-position:center;background-size:18px 18px;',
        'background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 24 24%27 fill=%27none%27 stroke=%27%2316232F%27 stroke-width=%271.8%27 stroke-linecap=%27round%27 stroke-linejoin=%27round%27%3E%3Cpath d=%27M6 2h8l4 4v16H6z%27/%3E%3Cpath d=%27M14 2v5h5M9 11h6M9 15h5%27/%3E%3C/svg%3E");',
        'opacity:.9;',
      '}',
      '#creditNotePortfolio .credit-note-mini-label{',
        'grid-column:2;grid-row:1;align-self:center;margin:0!important;',
        'font:600 10.5px/1.2 IBM Plex Mono,monospace!important;',
        'letter-spacing:.07em!important;text-transform:uppercase!important;color:var(--ink)!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-total{',
        'grid-column:1/3;grid-row:2;align-self:center;',
        'font-family:Fraunces,serif!important;font-size:15px!important;line-height:1.05!important;font-weight:700!important;',
        'letter-spacing:-.01em!important;color:var(--ink)!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-arrow{',
        'grid-column:3;grid-row:2;align-self:center;justify-self:end;',
        'font-size:20px!important;line-height:1!important;color:var(--muted)!important;',
      '}',
      '#creditNotePortfolio .credit-note-mini-detail{border-top:1px solid var(--paper-line)!important;}',

      '/* Unit Mix — same approved structure, smaller labels and tighter section spacing. */',
      '.overview>.section-label:has(+ div>.mix-row){',
        'display:flex!important;align-items:center!important;gap:11px!important;',
        'min-height:48px!important;margin:10px 0 0!important;padding:0 16px!important;',
        'border:1px solid var(--paper-line)!important;border-radius:16px 16px 0 0!important;',
        'background:linear-gradient(180deg,rgba(235,227,206,.72),rgba(235,227,206,.56))!important;',
        'box-shadow:0 2px 9px rgba(15,26,38,.035)!important;',
        'color:var(--ink)!important;font-family:IBM Plex Mono,monospace!important;',
        'font-size:10.5px!important;font-weight:600!important;line-height:1.2!important;',
        'letter-spacing:.07em!important;text-transform:uppercase!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)::before{',
        'content:"";display:block;flex:0 0 18px;width:18px;height:18px;',
        'background-repeat:no-repeat;background-position:center;background-size:18px 18px;',
        'background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 24 24%27 fill=%27none%27 stroke=%27%2316232F%27 stroke-width=%271.8%27 stroke-linecap=%27round%27%3E%3Cpath d=%27M5 20V13M12 20V8M19 20V4%27/%3E%3C/svg%3E");',
        'opacity:.9;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div{',
        'margin:0 0 10px!important;border:1px solid var(--paper-line)!important;border-top:0!important;',
        'border-radius:0 0 16px 16px!important;background:var(--paper)!important;overflow:hidden!important;',
        'box-shadow:0 2px 9px rgba(15,26,38,.035)!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row{',
        'display:grid!important;grid-template-columns:34% 30% 36%!important;align-items:center!important;',
        'min-height:52px!important;padding:0!important;border-bottom:1px solid var(--paper-line)!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row:last-child{border-bottom:0!important;}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>span{',
        'position:relative!important;display:flex!important;align-items:center!important;min-width:0!important;height:100%!important;',
        'padding:0 16px!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>.mix-label{',
        'font-family:Fraunces,serif!important;font-size:12px!important;font-weight:700!important;line-height:1.15!important;',
        'color:var(--ink)!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>.mix-count{',
        'justify-content:center!important;font-family:Inter,system-ui,sans-serif!important;font-size:12px!important;font-weight:400!important;',
        'color:var(--muted)!important;text-align:center!important;white-space:nowrap!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>.mix-value{',
        'justify-content:flex-end!important;font-family:Fraunces,serif!important;font-size:13px!important;font-weight:600!important;',
        'line-height:1.15!important;color:var(--ink)!important;text-align:right!important;white-space:nowrap!important;',
      '}',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>.mix-count::before,',
      '.overview>.section-label:has(+ div>.mix-row)+div>.mix-row>.mix-value::before{',
        'content:"";position:absolute;left:0;top:50%;width:1px;height:27px;transform:translateY(-50%);background:rgba(220,210,182,.86);',
      '}',

      '/* Collection by Stage — framed swipe table with tighter section spacing. */',
      '.overview>.section-label:has(+ .stage-scroll){',
        'display:flex!important;align-items:center!important;gap:11px!important;',
        'min-height:48px!important;margin:10px 0 0!important;padding:0 16px!important;',
        'border:1px solid var(--paper-line)!important;border-radius:16px 16px 0 0!important;',
        'background:linear-gradient(180deg,rgba(235,227,206,.72),rgba(235,227,206,.56))!important;',
        'box-shadow:0 2px 9px rgba(15,26,38,.035)!important;',
        'color:var(--ink)!important;font-family:IBM Plex Mono,monospace!important;',
        'font-size:10.2px!important;font-weight:600!important;line-height:1.2!important;',
        'letter-spacing:.055em!important;text-transform:uppercase!important;white-space:nowrap!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)::before{',
        'content:"";display:block;flex:0 0 18px;width:18px;height:18px;',
        'background-repeat:no-repeat;background-position:center;background-size:18px 18px;',
        'background-image:url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 24 24%27 fill=%27none%27 stroke=%27%2316232F%27 stroke-width=%271.8%27 stroke-linecap=%27round%27 stroke-linejoin=%27round%27%3E%3Cpath d=%27M6 2h8l4 4v16H6z%27/%3E%3Cpath d=%27M14 2v5h5M9 11h6M9 15h6M9 19h4%27/%3E%3C/svg%3E");',
        'opacity:.9;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll{',
        'margin:0 0 10px!important;border:1px solid var(--paper-line)!important;border-top:0!important;',
        'border-radius:0 0 16px 16px!important;background:var(--paper)!important;',
        'box-shadow:0 2px 9px rgba(15,26,38,.035)!important;overflow-x:auto!important;overflow-y:hidden!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl{',
        'min-width:460px!important;margin:0!important;background:var(--paper)!important;border-collapse:collapse!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl th{',
        'padding:12px 14px!important;border-bottom:1px solid var(--paper-line)!important;',
        'font-family:IBM Plex Mono,monospace!important;font-size:9.5px!important;font-weight:500!important;',
        'line-height:1.2!important;letter-spacing:.045em!important;color:var(--muted)!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl td{',
        'padding:11.5px 14px!important;border-top:1px solid var(--paper-line)!important;',
        'font-family:IBM Plex Mono,monospace!important;font-size:11.5px!important;line-height:1.25!important;color:var(--ink)!important;',
      '}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl tbody tr:first-child td{border-top:0!important;}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl th:first-child,',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl td:first-child{width:52%!important;text-align:left!important;}',
      '.overview>.section-label:has(+ .stage-scroll)+.stage-scroll .stage-tbl td:first-child{',
        'font-family:Inter,system-ui,sans-serif!important;font-size:13px!important;font-weight:500!important;line-height:1.25!important;',
        'white-space:nowrap!important;',
      '}',
    '}'
  ].join('');
  document.head.appendChild(style);
})();
