(function(){
'use strict';
if(window.__sunblissPaymentExtensionsCore)return;window.__sunblissPaymentExtensionsCore=true;
var C={e:[],s:[],c:[],t:[],u:null,loaded:false,busy:null},timer=null,pref=null;
function tx(v){return v==null?'':String(v)}
function esc(v){if(typeof window.esc==='function')return window.esc(tx(v));return tx(v).replace(/[&<>"']/g,function(x){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]})}
function today(n){var d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+(n||0));return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function day(v){var s=tx(v).slice(0,10),d=new Date(s+'T00:00:00');return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(d)?d:null}
function days(v){var a=day(v),b=day(today());return a&&b?Math.round((a-b)/86400000):null}
function date(v){var d=day(v);return d?d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):tx(v)}
function money(v){var n=Math.max(0,Number(v)||0);return typeof window.fmtAED==='function'?window.fmtAED(n):'AED '+n.toLocaleString('en-AE',{maximumFractionDigits:2})}
function units(){var x={};(window.state&&Array.isArray(state.dues)?state.dues:[]).forEach(function(c){if(Number(c&&c.sno)>0)x[c.sno]=1});return Object.keys(x).map(Number)}
function cust(id){return(window.state&&Array.isArray(state.dues)?state.dues:[]).find(function(c){return Number(c&&c.sno)===Number(id)})||null}
function current(){return window.state&&state.selectedUnit&&Array.isArray(state.dues)?state.dues.find(function(c){return tx(c.unit)+'::'+tx(c.sno)===tx(state.selectedUnit)})||null:null}
function allowed(){return !!(window.state&&(state.userRole==='crm_officer'||state.userRole==='manager'))}
function smap(){var x={};C.s.forEach(function(r){x[r.id]=r});return x}
function cmap(){var x={};C.c.forEach(function(r){if(r.payment_schedule_id!=null)x[r.payment_schedule_id]=(x[r.payment_schedule_id]||0)+(Number(r.amount)||0)});return x}
function rem(r,cm){return r?Math.round(Math.max(0,(Number(r.due_amount)||0)-(Number(r.paid_amount)||0)-(cm[r.id]||0))*100)/100:0}
function pen(v){return v==='original_due_date'?'Charges from original due date':v==='extended_due_date'?'Charges after extended deadline':v==='waived_until_extension'?'Charges waived through extension':v==='no_late_charges'?'No late charges':'Penalty treatment not specified'}
async function load(force){if(!window.sb||!allowed())return C;if(C.loaded&&!force)return C;if(C.busy&&!force)return C.busy;C.busy=(async function(){var ids=units(),ur=await sb.auth.getUser();C.u=ur&&ur.data&&ur.data.user||null;if(!ids.length){C.e=[];C.s=[];C.c=[];C.t=[];C.loaded=true;C.busy=null;return C}var q=await Promise.all([sb.from('payment_extensions').select('*').in('unit_id',ids),sb.from('payment_schedule').select('id,customer_id,unit_id,stage_name,due_amount,due_date,paid_amount,status').in('unit_id',ids),sb.from('credit_notes').select('payment_schedule_id,unit_id,amount').in('unit_id',ids),sb.from('scheduled_actions').select('id,unit_id,action_label,due_date,priority,note,status,owner_id,source,auto_kind,auto_key,schedule_id,completed_at,cancelled_at')]);q.forEach(function(r){if(r.error)throw r.error});C.e=q[0].data||[];C.s=q[1].data||[];C.c=q[2].data||[];C.t=q[3].data||[];C.loaded=true;C.busy=null;return C})().catch(function(e){C.busy=null;throw e});return C.busy}
function active(){var sm=smap(),cm=cmap(),now=today();return C.e.filter(function(e){return e.status==='active'&&tx(e.extended_due_date)>=now&&rem(sm[e.payment_schedule_id],cm)>1})}
async function statuses(){var sm=smap(),cm=cmap(),now=today(),iso=new Date().toISOString(),changed=false;for(var i=0;i<C.e.length;i++){var e=C.e[i],p=null;if(e.status!=='active')continue;if(rem(sm[e.payment_schedule_id],cm)<=1)p={status:'completed',completed_at:iso,updated_at:iso};else if(tx(e.extended_due_date)<now)p={status:'expired',expired_at:iso,updated_at:iso};if(p){var r=await sb.from('payment_extensions').update(p).eq('id',e.id);if(r.error)throw r.error;changed=true}}return changed}
function groups(){var sm=smap(),cm=cmap(),g={};active().forEach(function(e){var r=sm[e.payment_schedule_id];if(!r)return;var k=e.unit_id+'|'+e.extended_due_date;(g[k]||(g[k]={unit:Number(e.unit_id),due:tx(e.extended_due_date),x:[]})).x.push({e:e,r:r,n:rem(r,cm)})});return Object.keys(g).map(function(k){return g[k]})}
function total(g){return Math.round(g.x.reduce(function(a,x){return a+x.n},0)*100)/100}
function key(g){return'extension_active|unit:'+g.unit+'|due:'+g.due+'|schedules:'+g.x.map(function(x){return Number(x.r.id)}).sort(function(a,b){return a-b}).join(',')}
function label(g){var d=days(g.due),m=money(total(g));return d===0?'Extension Payment Due Today — '+m:d===1?'Extension Expires Tomorrow — '+m:d===2?'Send Extension Expiry Reminder — '+m:d!=null&&d<=10?'Extension Due in '+d+' Days — '+m:'Extension Active — '+m}
function note(g){var orig={},pp={},st=[];g.x.forEach(function(x){orig[x.e.original_due_date]=1;pp[x.e.penalty_basis]=1;st.push(x.r.stage_name)});var ps=Object.keys(pp);return st.join(' + ')+' · '+money(total(g))+' outstanding · original due '+Object.keys(orig).map(date).join(' / ')+' · extended until '+date(g.due)+' · '+(ps.length===1?pen(ps[0]):'See extension terms')+'.'}
async function cancel(ids){if(!ids.length)return false;var r=await sb.from('scheduled_actions').update({status:'cancelled',cancelled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).in('id',ids);if(r.error)throw r.error;return true}
async function extTasks(){if(!C.u)return false;var gs=groups(),want={},old={},changed=false,now=new Date().toISOString();gs.forEach(function(g){want[key(g)]=g});C.t.forEach(function(t){if(t.auto_kind==='extension_active'&&t.auto_key)old[t.auto_key]=t});var dead=[];C.t.forEach(function(t){if(t.auto_kind==='extension_active'&&t.status==='pending'&&!want[t.auto_key])dead.push(t.id)});if(await cancel(dead))changed=true;for(var k in want){var g=want[k],p={unit_id:g.unit,action_label:label(g),due_date:g.due,priority:days(g.due)<=2?'High':'Medium',note:note(g),status:'pending',owner_id:C.u.id,source:'manual',auto_kind:'extension_active',auto_key:k,schedule_id:null,updated_at:now},o=old[k];if(o){if(o.status!=='pending'||tx(o.action_label)!==p.action_label||tx(o.note)!==p.note){var u=await sb.from('scheduled_actions').update({action_label:p.action_label,due_date:p.due_date,priority:p.priority,note:p.note,status:'pending',cancelled_at:null,completed_at:null,updated_at:now}).eq('id',o.id);if(u.error)throw u.error;changed=true}}else{var z=await sb.from('scheduled_actions').insert(p);if(z.error&&z.error.code!=='23505')throw z.error;if(!z.error)changed=true}}return changed}
function idsFrom(k){var m=tx(k).match(/\|schedules:([0-9,]+)/);return m?m[1].split(',').map(Number):[]}
async function conflicts(){var act={};active().forEach(function(e){act[e.payment_schedule_id]=1});var sm=smap(),cm=cmap(),now=today(),dead=[],res={},changed=false;if(!C.u)return false;C.t.forEach(function(t){if(t.status!=='pending'||t.source!=='automatic')return;if(t.schedule_id!=null&&act[t.schedule_id]){dead.push(t.id);return}if(t.auto_kind!=='overdue_follow_up')return;var all=idsFrom(t.auto_key),hit=all.some(function(id){return act[id]});if(!hit)return;dead.push(t.id);var left=all.map(function(id){var r=sm[id];return !act[id]&&r&&tx(r.due_date)<now&&rem(r,cm)>1?{r:r,n:rem(r,cm)}:null}).filter(Boolean);if(!left.length)return;left.sort(function(a,b){return tx(a.r.due_date).localeCompare(tx(b.r.due_date))});var rk='extension_residual_overdue|unit:'+t.unit_id+'|schedules:'+left.map(function(x){return x.r.id}).sort(function(a,b){return a-b}).join(','),sum=Math.round(left.reduce(function(a,x){return a+x.n},0)*100)/100;res[rk]={unit_id:Number(t.unit_id),action_label:'Urgent Follow-up — '+money(sum)+' overdue',due_date:left[0].r.due_date,priority:'High',note:left.map(function(x){return x.r.stage_name}).join(' + ')+' · '+money(sum)+' overdue. Other obligations are under an approved extension.',status:'pending',owner_id:C.u.id,source:'manual',auto_kind:'extension_residual_overdue',auto_key:rk,schedule_id:null,updated_at:new Date().toISOString()}});if(await cancel(dead))changed=true;var old={};C.t.forEach(function(t){if(t.auto_kind==='extension_residual_overdue'&&t.auto_key)old[t.auto_key]=t});var gone=[];C.t.forEach(function(t){if(t.auto_kind==='extension_residual_overdue'&&t.status==='pending'&&!res[t.auto_key])gone.push(t.id)});if(await cancel(gone))changed=true;for(var k in res){var p=res[k],o=old[k];if(o){if(o.status!=='pending'||tx(o.note)!==p.note){var u=await sb.from('scheduled_actions').update({action_label:p.action_label,due_date:p.due_date,priority:'High',note:p.note,status:'pending',cancelled_at:null,updated_at:p.updated_at}).eq('id',o.id);if(u.error)throw u.error;changed=true}}else{var q=await sb.from('scheduled_actions').insert(p);if(q.error&&q.error.code!=='23505')throw q.error;if(!q.error)changed=true}}return changed}
async function run(){await load(true);var ch=await statuses();if(ch)await load(true);if(await extTasks())ch=true;if(ch)await load(true);if(await conflicts())ch=true;if(ch)await load(true);render();return ch}
function sync(){if(C.busy)return C.busy;if(C.syncing)return C.syncing;C.syncing=run().catch(function(e){console.warn('Extension sync failed',e);return false}).then(function(v){C.syncing=null;return v});return C.syncing}
function later(ms){clearTimeout(timer);timer=setTimeout(sync,ms||250)}
function unitGroups(id){return groups().filter(function(g){return g.unit===Number(id)}).sort(function(a,b){return a.due.localeCompare(b.due)})}
function genuineOverdue(id){var a={};active().forEach(function(e){a[e.payment_schedule_id]=1});var cm=cmap(),now=today();return C.s.filter(function(r){var n=tx(r.stage_name).toLowerCase();return Number(r.unit_id)===Number(id)&&!a[r.id]&&r.due_date&&tx(r.due_date)<now&&rem(r,cm)>1&&n.indexOf('dld')<0&&n.indexOf('admin fee')<0})}
function actionCard(){if(!window.state||state.view!=='detail')return;var c=current(),gs=c?unitGroups(c.sno):[];if(!c||!gs.length||genuineOverdue(c.sno).length)return;var card=document.getElementById('actionRequiredCard');if(!card)return;var all=[];gs.forEach(function(g){all=all.concat(g.x)});var sum=Math.round(gs.reduce(function(a,g){return a+total(g)},0)*100)/100,first=gs[0],d=days(first.due),orig={};all.forEach(function(x){orig[x.e.original_due_date]=1});var msg=(all.length===1?money(sum)+' outstanding is':money(sum)+' across '+all.length+' payment obligations is')+' under an approved payment extension until '+date(first.due)+'.',detail='Original SPA due '+Object.keys(orig).map(date).join(' / ')+' · '+(d===0?'extended deadline is today':d===1?'1 day remaining':d+' days remaining'),html='<div class="action-required-head"><span class="action-required-title">Action Required</span><span class="action-required-status">Extension Active</span></div><p class="action-required-message">'+esc(msg)+'</p><p class="action-required-detail">'+esc(detail)+'.</p>',sig=msg+'|'+detail;if(card.dataset.extSig===sig&&card.querySelector('.action-required-status')&&card.querySelector('.action-required-status').textContent==='Extension Active')return;card.dataset.extSig=sig;card.setAttribute('data-tone','extension');card.innerHTML=html}
function styles(){if(document.getElementById('extensionCoreStyles'))return;var s=document.createElement('style');s.id='extensionCoreStyles';s.textContent='.action-required-card[data-tone="extension"]{border-left-color:var(--amber,#9C5A12)!important;background:rgba(156,90,18,.065)!important}.action-required-card[data-tone="extension"] .action-required-status{color:var(--amber,#9C5A12)!important}.scheduled-extension{border-left-color:var(--amber,#9C5A12)!important;background:rgba(156,90,18,.05)!important}.ext-badge{display:inline-flex;margin-left:6px;padding:2px 6px;border:1px solid rgba(156,90,18,.3);border-radius:999px;color:var(--amber,#9C5A12);font:700 8px/1.2 IBM Plex Mono,monospace;text-transform:uppercase}.scheduled-task-state.ext{color:var(--amber,#9C5A12)!important;background:rgba(156,90,18,.08)!important}';document.head.appendChild(s)}
function decorate(){var m={};C.t.forEach(function(t){if(t.auto_kind==='extension_active')m[t.id]=t});document.querySelectorAll('[data-task-id]').forEach(function(n){var t=m[n.getAttribute('data-task-id')];if(!t)return;n.classList.add('scheduled-extension');var title=n.querySelector('.scheduled-task-title,.scheduled-overview-title');if(title&&!title.querySelector('.ext-badge'))title.insertAdjacentHTML('beforeend','<span class="ext-badge">Extension</span>');n.querySelectorAll('.scheduled-task-actions,.scheduled-mark-done,.scheduled-edit,.scheduled-overview-done').forEach(function(x){x.remove()});var st=n.querySelector('.scheduled-task-state');if(st){st.className='scheduled-task-state ext';st.textContent='Extension Active'}})}
function counts(){var a={today:0,tomorrow:0,overdue:0,upcoming:0,completed:0,extensions:0},td=today(),tm=today(1);C.t.forEach(function(t){if(t.auto_kind==='extension_active'){if(t.status==='pending')a.extensions++;return}if(t.status==='completed'){a.completed++;return}if(t.status!=='pending')return;var d=tx(t.due_date);if(d<td)a.overdue++;else if(d===td)a.today++;else if(d===tm)a.tomorrow++;else a.upcoming++});return a}
function extOption(){var s=document.getElementById('scheduledOverviewFilter');if(!s)return;if(!s.querySelector('option[value="extensions"]')){var o=document.createElement('option');o.value='extensions';var up=s.querySelector('option[value="upcoming"]');up?s.insertBefore(o,up):s.appendChild(o)}if(!s.__extBound){s.__extBound=1;s.addEventListener('change',function(){pref=this.value;setTimeout(overview,0)})}if(pref==='extensions')s.value='extensions';var c=counts(),names={today:'Today',tomorrow:'Tomorrow',overdue:'Overdue',extensions:'Extensions',upcoming:'Upcoming',completed:'Completed'};Object.keys(names).forEach(function(k){var o=s.querySelector('option[value="'+k+'"]'),v=names[k]+' · '+c[k];if(o&&o.textContent!==v)o.textContent=v})}
function openUnit(id){var c=cust(id);if(!c)return;if(typeof window.goToDetail==='function')window.goToDetail(c.unit,c.sno,'overview');else{state.selectedUnit=c.unit+'::'+c.sno;state.view='detail';state.detailFrom='overview';if(typeof window.renderMain==='function')window.renderMain()}}
function overview(){if(!window.state||state.view!=='overview')return;extOption();var s=document.getElementById('scheduledOverviewFilter'),h=document.getElementById('scheduledOverviewList');if(!s||!h)return;if(s.value!=='extensions'){var m={};C.t.forEach(function(t){if(t.auto_kind==='extension_active')m[t.id]=1});h.querySelectorAll('[data-task-id]').forEach(function(n){if(m[n.getAttribute('data-task-id')])n.remove()});decorate();return}var rows=C.t.filter(function(t){return t.status==='pending'&&t.auto_kind==='extension_active'}).sort(function(a,b){return tx(a.due_date).localeCompare(tx(b.due_date))}),html=rows.map(function(t){var c=cust(t.unit_id),d=days(t.due_date);return'<div class="scheduled-overview-row scheduled-extension" data-task-id="'+t.id+'"><div class="scheduled-overview-main" data-ext-unit="'+t.unit_id+'"><div class="scheduled-overview-unit">'+esc(c?c.unit:'Unit '+t.unit_id)+' · '+esc(c?c.name:'Customer')+'</div><div class="scheduled-overview-title">'+esc(t.action_label)+'<span class="ext-badge">Extension</span></div><div class="scheduled-overview-meta"><span class="scheduled-task-state ext">Extension Active</span> · '+esc(date(t.due_date))+' · '+esc(d===0?'Due today':d===1?'1 day remaining':d+' days remaining')+(t.note?' · '+esc(t.note):'')+'</div></div></div>'}).join('')||'<div style="padding:16px 2px;color:var(--muted);font-size:12px">No active payment extensions.</div>';if(h.innerHTML!==html)h.innerHTML=html;h.querySelectorAll('[data-ext-unit]').forEach(function(n){if(!n.__x){n.__x=1;n.onclick=function(){openUnit(n.getAttribute('data-ext-unit'))}}})}
function render(){styles();actionCard();decorate();overview();if(window.PaymentExtensionsUI&&typeof window.PaymentExtensionsUI.refresh==='function')window.PaymentExtensionsUI.refresh(C)}
window.PaymentExtensionsCore={cache:C,load:load,sync:sync,active:active,remaining:rem,scheduleMap:smap,creditMap:cmap,formatDate:date,money:money,penalty:pen,render:render};
function install(){
  if(!window.state||!window.sb||typeof window.renderDetail!=='function'||typeof window.renderOverview!=='function'||typeof window.loadFromSupabase!=='function'){setTimeout(install,70);return}
  styles();
  var rd=window.renderDetail;
  window.renderDetail=function(){var o=rd.apply(this,arguments);load(false).then(function(){render();later(240)}).catch(function(){});return o};
  var ro=window.renderOverview;
  window.renderOverview=function(){var o=ro.apply(this,arguments);load(false).then(function(){render();later(240)}).catch(function(){});return o};
  var ld=window.loadFromSupabase;
  window.loadFromSupabase=async function(){var o=await ld.apply(this,arguments);await sync();return o};
  window.addEventListener('pageshow',function(){load(true).then(function(){render();later(120)}).catch(function(){})});
  sync();
}
install();
})();