(function(){
'use strict';
if(window.__sunblissExtensionUncoveredOverdueGuard)return;window.__sunblissExtensionUncoveredOverdueGuard=true;
var busy=null,timer=null,meta={};
function tx(v){return v==null?'':String(v)}
function norm(v){return tx(v).trim().toLowerCase().replace(/\s+/g,' ')}
function today(){var d=new Date();d.setHours(0,0,0,0);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function money(v){var n=Math.max(0,Number(v)||0);return typeof window.fmtAED==='function'?window.fmtAED(n):'AED '+n.toLocaleString('en-AE',{maximumFractionDigits:2})}
function date(v){var s=tx(v).slice(0,10),d=new Date(s+'T00:00:00');return isNaN(d)?s:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function isPayment(r){var n=norm(r&&r.stage_name);return !!n&&n.indexOf('dld')<0&&n.indexOf('admin fee')<0&&n.indexOf('booking')<0&&(n.indexOf('installment')>=0||n.indexOf('down payment')>=0||n.indexOf('final')>=0)}
function managed(){var x={};if(!window.state||!Array.isArray(state.dues))return x;state.dues.forEach(function(c){(c.stages||[]).forEach(function(s){if(s&&s.id&&s.carryForwardManaged===true)x[String(s.id)]=1})});return x}
function current(){return window.state&&state.selectedUnit&&Array.isArray(state.dues)?state.dues.find(function(c){return tx(c.unit)+'::'+tx(c.sno)===tx(state.selectedUnit)})||null:null}
function extInfo(){var C=window.PaymentExtensionsCore;if(!C)return null;var active=C.active(),sched={},units={},latest={};active.forEach(function(e){sched[String(e.payment_schedule_id)]=1;units[String(e.unit_id)]=1;var d=tx(e.extended_due_date);if(!latest[e.unit_id]||d>latest[e.unit_id])latest[e.unit_id]=d});return{C:C,active:active,sched:sched,units:units,latest:latest}}
function rowsByUnit(info){var C=info.C,cm=C.creditMap(),m=managed(),out={},now=today();(C.cache.s||[]).forEach(function(r){var uid=String(r.unit_id),sid=String(r.id);if(!info.units[uid]||info.sched[sid]||m[sid]||!isPayment(r)||!r.due_date||tx(r.due_date)>=now)return;var n=C.remaining(r,cm);if(n<=1)return;(out[uid]=out[uid]||[]).push({r:r,n:n})});Object.keys(out).forEach(function(k){out[k].sort(function(a,b){return tx(a.r.due_date).localeCompare(tx(b.r.due_date))})});return out}
function key(uid,rows){return'extension_uncovered_overdue|unit:'+uid+'|schedules:'+rows.map(function(x){return Number(x.r.id)}).sort(function(a,b){return a-b}).join(',')}
async function cancel(ids){if(!ids.length)return false;var r=await sb.from('scheduled_actions').update({status:'cancelled',cancelled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).in('id',ids);if(r.error)throw r.error;return true}
async function sync(){if(busy)return busy;busy=(async function(){var C=window.PaymentExtensionsCore;if(!window.sb||!C)return false;await C.load(true);var info=extInfo();if(!info)return false;var user=info.C.cache.u;if(!user)return false;var groups=rowsByUnit(info),desired={},changed=false,now=new Date().toISOString();Object.keys(groups).forEach(function(uid){var rows=groups[uid],sum=Math.round(rows.reduce(function(a,x){return a+x.n},0)*100)/100,k=key(uid,rows);desired[k]={unit_id:Number(uid),action_label:'Urgent Follow-up — '+money(sum)+' overdue',due_date:rows[0].r.due_date,priority:'High',note:rows.map(function(x){return tx(x.r.stage_name)}).join(' + ')+' · '+money(sum)+' overdue. Other obligations remain under an approved extension until '+date(info.latest[uid])+'.',status:'pending',owner_id:user.id,source:'manual',auto_kind:'extension_uncovered_overdue',auto_key:k,schedule_id:null,updated_at:now}});var q=await sb.from('scheduled_actions').select('id,unit_id,action_label,due_date,priority,note,status,auto_kind,auto_key').eq('auto_kind','extension_uncovered_overdue');if(q.error)throw q.error;var old={},dead=[];(q.data||[]).forEach(function(t){if(t.auto_key)old[t.auto_key]=t;if(t.status==='pending'&&!desired[t.auto_key])dead.push(t.id)});if(await cancel(dead))changed=true;for(var k in desired){var p=desired[k],o=old[k];if(o){if(o.status!=='pending'||tx(o.action_label)!==p.action_label||tx(o.note)!==p.note||tx(o.due_date)!==tx(p.due_date)){var u=await sb.from('scheduled_actions').update({action_label:p.action_label,due_date:p.due_date,priority:'High',note:p.note,status:'pending',cancelled_at:null,completed_at:null,updated_at:now}).eq('id',o.id);if(u.error)throw u.error;changed=true}meta[String(o.id)]=p}else{var ins=await sb.from('scheduled_actions').insert(p).select('id').single();if(ins.error&&ins.error.code!=='23505')throw ins.error;if(!ins.error){changed=true;meta[String(ins.data.id)]=p}}}var fresh=await sb.from('scheduled_actions').select('id,auto_kind').eq('auto_kind','extension_uncovered_overdue').eq('status','pending');if(!fresh.error){meta={};(fresh.data||[]).forEach(function(t){meta[String(t.id)]=t})}decorate();overrideAction(groups,info);return changed})().catch(function(e){console.warn('Extension uncovered overdue guard failed',e);return false}).then(function(v){busy=null;return v});return busy}
function decorate(){document.querySelectorAll('[data-task-id]').forEach(function(n){var id=String(n.getAttribute('data-task-id')||'');if(!meta[id])return;n.classList.add('scheduled-auto');n.setAttribute('data-auto-kind','overdue_follow_up');var title=n.querySelector('.scheduled-task-title,.scheduled-overview-title');if(title&&!title.querySelector('.scheduled-auto-badge')){var b=document.createElement('span');b.className='scheduled-auto-badge';b.textContent='Automatic';title.appendChild(b)}n.querySelectorAll('.scheduled-task-actions,.scheduled-mark-done,.scheduled-edit,.scheduled-overview-done').forEach(function(x){x.remove()})})}
function overrideAction(groups,info){if(!window.state||state.view!=='detail')return;var c=current();if(!c)return;var rows=groups[String(c.sno)]||[];if(!rows.length)return;var card=document.getElementById('actionRequiredCard');if(!card)return;var sum=Math.round(rows.reduce(function(a,x){return a+x.n},0)*100)/100,stages=rows.map(function(x){return tx(x.r.stage_name)}).join(' + '),msg=money(sum)+' is genuinely overdue for '+stages+'.',detail='Stage: '+stages+' · By '+date(rows[0].r.due_date)+' · Overdue. Other approved extension items remain protected until '+date(info.latest[c.sno])+'.',action={status:'Overdue',tone:'danger',message:msg,detail:detail};if(typeof window.sunblissRenderActionRequiredCard==='function'){window.sunblissRenderActionRequiredCard(card,action);return}card.setAttribute('data-tone','danger');var status=card.querySelector('.action-required-status'),message=card.querySelector('.action-required-message'),detailNode=card.querySelector('.action-required-detail');if(status)status.textContent=action.status;if(message)message.textContent=action.message;if(detailNode)detailNode.textContent=action.detail}
function later(ms){clearTimeout(timer);timer=setTimeout(sync,ms==null?450:ms)}
function install(){
  if(!window.PaymentExtensionsCore||!window.state||!window.sb||typeof window.loadFromSupabase!=='function'){setTimeout(install,80);return}
  var ld=window.loadFromSupabase;
  window.loadFromSupabase=async function(){var o=await ld.apply(this,arguments);await sync();return o};
  var rd=window.renderDetail;
  if(typeof rd==='function')window.renderDetail=function(){var o=rd.apply(this,arguments);later(120);return o};
  var ro=window.renderOverview;
  if(typeof ro==='function')window.renderOverview=function(){var o=ro.apply(this,arguments);later(120);return o};
  window.addEventListener('pageshow',function(){decorate();later(100)});
  later(60);
}
install();
})();