(function(){
'use strict';
if(window.__sunblissPaymentScheduleRevisedDatesInstalled)return;
window.__sunblissPaymentScheduleRevisedDatesInstalled=true;
var cache={},loading={},queued=false;
function text(v){return v==null?'':String(v)}
function norm(v){return text(v).replace(/\s+/g,' ').trim().toLowerCase()}
function unitId(){if(!window.state||!state.selectedUnit)return null;var p=String(state.selectedUnit).split('::');return p.length>1&&Number(p[1])?Number(p[1]):null}
function customer(){if(!window.state||!state.selectedUnit||!Array.isArray(state.dues))return null;return state.dues.find(function(c){return c&&(text(c.unit)+'::'+text(c.sno))===text(state.selectedUnit)})||null}
function iso(v){var s=text(v).slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:''}
function date(v){var s=iso(v),d=s?new Date(s+'T00:00:00'):null;return d&&!isNaN(d.getTime())?d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):text(v)}
function styles(){if(document.getElementById('paymentScheduleRevisedDateStyles'))return;var s=document.createElement('style');s.id='paymentScheduleRevisedDateStyles';s.textContent='.stage-date-adjustment{display:flex;justify-content:space-between;gap:6px;margin:2px 0 4px;font-size:10px;line-height:1.35}.stage-date-adjustment span:first-child{color:var(--muted)}.stage-date-adjustment span:last-child{font-family:IBM Plex Mono,monospace;text-align:right;font-weight:700}.stage-date-adjustment.revised span:last-child{color:var(--amber,#9C5A12)}.stage-date-adjustment.extended span:last-child{color:var(--gold-deep,#8F6A1E)}';document.head.appendChild(s)}
async function load(uid,force){var k=String(uid),hit=cache[k];if(!force&&hit&&Date.now()-hit.at<5000)return hit.data;if(loading[k])return loading[k];loading[k]=(async function(){var q=await Promise.all([sb.from('payment_schedule').select('id,due_date,revised_due_date,revision_approved_on,revision_reference').eq('unit_id',uid),sb.from('payment_extensions').select('payment_schedule_id,extended_due_date,status').eq('unit_id',uid)]);q.forEach(function(r){if(r.error)throw r.error});var now=new Date();now.setHours(0,0,0,0);var ext={};(q[1].data||[]).forEach(function(e){var d=iso(e.extended_due_date),dd=d?new Date(d+'T00:00:00'):null;if(e.status==='active'&&dd&&dd>=now)ext[String(e.payment_schedule_id)]=d});var rows={};(q[0].data||[]).forEach(function(r){rows[String(r.id)]=r});var data={rows:rows,extensions:ext};cache[k]={at:Date.now(),data:data};delete loading[k];return data})().catch(function(e){delete loading[k];throw e});return loading[k]}
function byRow(card){var rows=card.querySelectorAll('.stage-row');for(var i=0;i<rows.length;i++){var a=rows[i].querySelector('span:first-child');if(a&&norm(a.textContent)==='by')return rows[i]}return null}
function addRow(after,label,value,cls){var r=document.createElement('div');r.className='stage-date-adjustment '+cls;r.innerHTML='<span></span><span></span>';r.children[0].textContent=label;r.children[1].textContent=date(value);after.insertAdjacentElement('afterend',r);return r}
async function decorate(force){queued=false;styles();if(!window.state||!window.sb||state.view!=='detail')return;var c=customer(),uid=unitId(),detail=document.querySelector('.detail');if(!c||!uid||!detail)return;var key=text(state.selectedUnit);try{var data=await load(uid,!!force);if(!window.state||state.view!=='detail'||text(state.selectedUnit)!==key)return;var cards=detail.querySelectorAll('.ledger-scroll .stage-card');cards.forEach(function(card,index){card.querySelectorAll('.stage-date-adjustment').forEach(function(x){x.remove()});var stage=c.stages&&c.stages[index];if(!stage||!stage.id)return;var row=data.rows[String(stage.id)]||{},anchor=byRow(card);if(!anchor)return;var contractual=iso(row.due_date),revised=iso(row.revised_due_date),extended=data.extensions[String(stage.id)]||'';var last=anchor;if(revised&&revised!==contractual)last=addRow(last,'Revised to',revised,'revised');if(extended)last=addRow(last,'Extended to',extended,'extended')})}catch(e){console.warn('Could not show revised payment dates',e)}}
function schedule(force){if(force){var uid=unitId();if(uid)delete cache[String(uid)]}if(queued)return;queued=true;requestAnimationFrame(function(){decorate(!!force)})}
function install(){if(!window.state||!window.sb||typeof window.renderDetail!=='function'){setTimeout(install,70);return}var rd=window.renderDetail;window.renderDetail=function(){var x=rd.apply(this,arguments);schedule(false);return x};document.addEventListener('click',function(e){if(e.target&&e.target.closest&&e.target.closest('#extSave,#ieSave,#scSave'))setTimeout(function(){schedule(true)},180)},true);window.addEventListener('pageshow',function(){schedule(false)});schedule(true)}
install();
})();
