(function(){
'use strict';
if(window.__sunblissRecordPaymentReliabilityInstalled)return;
window.__sunblissRecordPaymentReliabilityInstalled=true;

var cache={customer:null,rows:[],credits:{},loading:false,saving:false};
function text(v){return v==null?'':String(v)}
function safe(v){if(typeof window.esc==='function')return window.esc(text(v));return text(v).replace(/[&<>"']/g,function(ch){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
function money(v){return typeof window.fmtAED==='function'?window.fmtAED(Number(v)||0):'AED '+(Number(v)||0).toLocaleString('en-AE',{maximumFractionDigits:2})}
function today(){var d=new Date(),m=d.getMonth()+1,day=d.getDate();return d.getFullYear()+'-'+String(m).padStart(2,'0')+'-'+String(day).padStart(2,'0')}
function currentCustomer(){if(!window.state||!state.selectedUnit||!Array.isArray(state.dues))return null;return state.dues.find(function(c){return c&&(text(c.unit)+'::'+text(c.sno))===text(state.selectedUnit)})||null}
function unitId(c){return Number(c&&(c.unitId!=null?c.unitId:c.sno))||0}
function isDld(row){return /\bdld\b|admin\s*fees?/i.test(text(row&&row.stage_name))}
function remaining(row){var due=Number(row&&row.due_amount)||0,cash=Number(row&&row.paid_amount)||0,credit=isDld(row)?0:(Number(cache.credits[String(row&&row.id)])||0);return Math.round((due-cash-credit)*100)/100}
function closePanel(){var p=document.getElementById('recordPaymentReliablePanel');if(p)p.remove();cache.customer=null;cache.rows=[];cache.credits={};cache.loading=false;cache.saving=false;if(window.state){state.paymentFormOpen=false;state.paymentFormSaving=false;state.paymentFormError=null}}
function setError(msg){var e=document.getElementById('recordPaymentReliableError');if(e){e.textContent=msg;e.style.display='block'}var b=document.getElementById('pfSave');if(b&&!cache.saving){b.disabled=false;b.textContent='Save payment'}}
function clearError(){var e=document.getElementById('recordPaymentReliableError');if(e){e.textContent='';e.style.display='none'}}
function ensureStyles(){if(document.getElementById('recordPaymentReliableStyles'))return;var s=document.createElement('style');s.id='recordPaymentReliableStyles';s.textContent=[
'#recordPaymentReliablePanel{margin:0!important}',
'#recordPaymentReliablePanel.crm-full-page-inline{padding:calc(10px + env(safe-area-inset-top)) 14px calc(12px + env(safe-area-inset-bottom))!important;scroll-padding-bottom:76px!important}',
'#recordPaymentReliablePanel>.section-label:first-child{position:static!important;margin:0 0 9px!important;padding:0!important;border:0!important;background:transparent!important;font-size:10.5px!important;line-height:1.25!important}',
'#recordPaymentReliablePanel .record-payment-summary{margin:0 0 10px;padding:8px 10px;border:1px solid var(--paper-line);border-radius:9px;background:var(--paper-dim);font-size:11px;line-height:1.35;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
'#recordPaymentReliablePanel .record-payment-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 10px}',
'#recordPaymentReliablePanel .brand-field{margin-bottom:8px;font-size:10.8px;line-height:1.25;min-width:0}',
'#recordPaymentReliablePanel select,#recordPaymentReliablePanel input{display:block;width:100%;min-width:0;min-height:42px;margin-top:4px;padding:7px 10px;border:1px solid var(--paper-line);border-radius:8px;font:500 15px/1.2 Inter,sans-serif;color:var(--ink);background:var(--paper-dim);box-sizing:border-box}',
'#recordPaymentReliablePanel select{padding-right:30px;white-space:nowrap;text-overflow:ellipsis}',
'#recordPaymentReliablePanel .record-payment-stage-note{margin:-2px 0 9px;padding:0 2px;font-size:10.3px;line-height:1.35;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
'#recordPaymentReliablePanel .record-payment-empty{padding:12px;border:1px solid var(--paper-line);border-radius:10px;background:var(--paper-dim);font-size:11.5px;line-height:1.45;color:var(--muted);margin-bottom:12px}',
'#recordPaymentReliablePanel .credit-note-toggle{margin:0 0 4px;padding:2px 0 6px;font-size:11px}',
'#recordPaymentReliablePanel #pfCreditFields{margin:3px 0 8px;padding:10px}',
'#recordPaymentReliablePanel #pfCreditFields .credit-note-fields-help{margin-bottom:8px;font-size:10px}',
'#recordPaymentReliablePanel .brand-editor-actions{position:sticky!important;bottom:calc(-12px - env(safe-area-inset-bottom))!important;display:flex!important;flex-direction:row!important;gap:8px!important;margin:10px -14px calc(-12px - env(safe-area-inset-bottom))!important;padding:9px 14px calc(9px + env(safe-area-inset-bottom))!important;background:var(--paper)!important;border-top:1px solid var(--paper-line)!important;box-shadow:0 -6px 16px rgba(15,26,38,.07)!important}',
'#recordPaymentReliablePanel .brand-editor-actions button{width:auto!important;min-height:42px!important;margin:0!important;padding:8px 12px!important;border-radius:999px!important}',
'#recordPaymentReliablePanel .brand-editor-actions #pfSave{flex:1.45!important}',
'#recordPaymentReliablePanel .brand-editor-actions #pfCancel{flex:.75!important}',
'@media(max-width:360px){#recordPaymentReliablePanel .record-payment-grid{grid-template-columns:1fr}#recordPaymentReliablePanel .record-payment-summary{white-space:normal}#recordPaymentReliablePanel .record-payment-stage-note{white-space:normal}}',
'@media(max-height:720px){#recordPaymentReliablePanel.crm-full-page-inline{padding-top:calc(7px + env(safe-area-inset-top))!important}#recordPaymentReliablePanel .brand-field{margin-bottom:6px}#recordPaymentReliablePanel select,#recordPaymentReliablePanel input{min-height:38px;padding-top:6px;padding-bottom:6px}#recordPaymentReliablePanel .record-payment-summary{margin-bottom:7px;padding:6px 9px}#recordPaymentReliablePanel .record-payment-stage-note{margin-bottom:6px}#recordPaymentReliablePanel .brand-editor-actions{margin-top:7px!important}}'
].join('');document.head.appendChild(s)}
function optionLabel(r){var rem=Math.max(0,remaining(r));return text(r.stage_name)+' · '+(rem<=1?'Fully settled':money(rem)+' remaining')}
function stageNote(r){if(!r)return'';var due=Number(r.due_amount)||0,cash=Number(r.paid_amount)||0,credit=isDld(r)?0:(Number(cache.credits[String(r.id)])||0),rem=Math.max(0,remaining(r)),parts=['Due '+money(due),'Cash '+money(cash)];if(credit>0)parts.push('Credit '+money(credit));parts.push('Remaining '+money(rem));return parts.join(' · ')}
function updateStageNote(){var sel=document.getElementById('pfStage'),note=document.getElementById('recordPaymentStageNote');if(!sel||!note)return;var sid=Number(sel.value)||0,row=cache.rows.find(function(r){return Number(r.id)===sid})||null;note.textContent=stageNote(row);note.title=note.textContent}
function renderForm(){var p=document.getElementById('recordPaymentReliablePanel');if(!p)return;var c=cache.customer,rows=cache.rows,openRows=rows.filter(function(r){return remaining(r)>1}),selected=(openRows[0]||rows[0]||{}).id||'';var options=rows.map(function(r){return'<option value="'+safe(r.id)+'"'+(Number(r.id)===Number(selected)?' selected':'')+'>'+safe(optionLabel(r))+'</option>'}).join('');
var form=rows.length?'<label class="brand-field">Installment<select id="pfStage">'+options+'</select></label><p class="record-payment-stage-note" id="recordPaymentStageNote"></p><div class="record-payment-grid"><label class="brand-field">Amount paid (AED)<input type="number" id="pfAmount" min="0" step="0.01" inputmode="decimal" placeholder="e.g. 50000" /></label><label class="brand-field">Payment date<input type="date" id="pfDate" value="'+today()+'" /></label></div><div class="record-payment-grid"><label class="brand-field">Reference (optional)<input type="text" id="pfRef" placeholder="Transfer / cheque no." /></label><label class="brand-field">Remarks (optional)<input type="text" id="pfRemarks" placeholder="Payment note" /></label></div><button class="credit-note-toggle" type="button" id="pfCreditToggle" aria-expanded="false">+ Add credit note (optional)</button><div id="pfCreditFields" hidden><p class="credit-note-fields-title">Credit note</p><p class="credit-note-fields-help">Paperwork adjustment only. It settles this installment without being counted as cash received.</p><div class="record-payment-grid"><label class="brand-field">Credit note amount (AED)<input type="number" id="pfCreditAmount" min="0" step="0.01" inputmode="decimal" placeholder="e.g. 25000" /></label><label class="brand-field">Issue date<input type="date" id="pfCreditDate" value="'+today()+'" /></label></div><div class="record-payment-grid"><label class="brand-field">Reason<input type="text" id="pfCreditReason" placeholder="Reason for credit note" /></label><label class="brand-field">Reference no. (optional)<input type="text" id="pfCreditRef" placeholder="e.g. CN-2026-014" /></label></div></div><div class="brand-editor-actions"><button class="btn btn-gold" type="button" id="pfSave" style="justify-content:center">Save payment</button><button class="btn-paper" type="button" id="pfCancel" style="justify-content:center;margin-bottom:0">Cancel</button></div>':'<div class="record-payment-empty">No payment schedule is available for this unit. Review the installment ledger before recording a payment.</div><div class="brand-editor-actions"><button class="btn-paper" type="button" id="pfCancel" style="justify-content:center;margin-bottom:0">Close</button></div>';
p.innerHTML='<p class="section-label" style="margin-top:0">Record Payment</p><p class="record-payment-summary">Unit '+safe(c&&c.unit||'')+' · '+safe(c&&c.name||'')+'</p><p class="brand-error" id="recordPaymentReliableError" style="display:none"></p>'+form;
var cancel=document.getElementById('pfCancel');if(cancel)cancel.onclick=closePanel;var select=document.getElementById('pfStage');if(select){select.onchange=updateStageNote;updateStageNote()}var toggle=document.getElementById('pfCreditToggle');if(toggle)toggle.onclick=function(){var box=document.getElementById('pfCreditFields'),open=box&&!box.hidden;if(box)box.hidden=open;toggle.setAttribute('aria-expanded',open?'false':'true');toggle.textContent=open?'+ Add credit note (optional)':'− Remove credit note'};var save=document.getElementById('pfSave');if(save)save.onclick=savePayment}
async function loadRows(c){var uid=unitId(c);if(!uid)throw new Error('This unit is not linked to its database record. Refresh the CRM and try again.');var q=await Promise.all([sb.from('payment_schedule').select('id,customer_id,unit_id,stage_name,due_amount,due_date,revised_due_date,paid_amount,paid_date,status').eq('unit_id',uid).order('due_date',{ascending:true}).order('id',{ascending:true}),sb.from('credit_notes').select('payment_schedule_id,amount').eq('unit_id',uid)]);q.forEach(function(r){if(r.error)throw r.error});cache.rows=(q[0].data||[]).filter(function(r){return Number(r.due_amount)>0&&!/\bbooking\b/i.test(text(r.stage_name))});cache.credits={};(q[1].data||[]).forEach(function(n){if(n.payment_schedule_id!=null){var k=String(n.payment_schedule_id);cache.credits[k]=Math.round(((cache.credits[k]||0)+(Number(n.amount)||0))*100)/100}})}
async function openPanel(){if(!window.state||state.userRole!=='crm_officer'||!window.sb)return;closePanel();ensureStyles();var c=currentCustomer();if(!c)return;cache.customer=c;cache.loading=true;state.paymentFormOpen=false;var p=document.createElement('div');p.id='recordPaymentReliablePanel';p.className='brand-editor record-payment-panel';p.setAttribute('role','dialog');p.setAttribute('aria-modal','true');p.innerHTML='<p class="section-label" style="margin-top:0">Record Payment</p><p class="record-payment-summary">Unit '+safe(c.unit||'')+' · '+safe(c.name||'')+'</p><p class="stat-sub">Loading payment schedule…</p>';document.body.appendChild(p);try{await loadRows(c);cache.loading=false;renderForm()}catch(e){cache.loading=false;p.innerHTML='<p class="section-label" style="margin-top:0">Record Payment</p><p class="record-payment-summary">Unit '+safe(c.unit||'')+' · '+safe(c.name||'')+'</p><p class="brand-error">'+safe(e&&e.message?e.message:'Could not load the payment schedule.')+'</p><div class="brand-editor-actions"><button class="btn-paper" type="button" id="pfCancel" style="justify-content:center;margin-bottom:0">Close</button></div>';document.getElementById('pfCancel').onclick=closePanel}}
function val(id){var e=document.getElementById(id);return e?text(e.value).trim():''}
async function savePayment(){if(cache.saving)return;clearError();var sid=Number(val('pfStage'))||0,row=cache.rows.find(function(r){return Number(r.id)===sid})||null,cash=val('pfAmount')===''?0:Number(val('pfAmount')),date=val('pfDate'),ref=val('pfRef'),remarks=val('pfRemarks'),box=document.getElementById('pfCreditFields'),creditOpen=!!(box&&!box.hidden),credit=creditOpen&&val('pfCreditAmount')!==''?Number(val('pfCreditAmount')):0,creditDate=creditOpen?val('pfCreditDate'):'',creditReason=creditOpen?val('pfCreditReason'):'',creditRef=creditOpen?val('pfCreditRef'):'';if(!row){setError('Select an installment.');return}if(!isFinite(cash)||cash<0){setError('Enter a valid cash payment amount.');return}if(!isFinite(credit)||credit<0){setError('Enter a valid credit note amount.');return}if(cash<=0&&credit<=0){setError('Enter a cash payment, a credit note, or both.');return}if(cash>0&&!date){setError('Select a payment date.');return}if(credit>0&&!creditDate){setError('Select the credit note issue date.');return}if(credit>0&&!creditReason){setError('Enter the credit note reason.');return}if(isDld(row)&&credit>0){setError('DLD + Admin Fees must be settled in cash. Credit notes cannot be applied to this stage.');return}var btn=document.getElementById('pfSave'),key=state.selectedUnit,from=state.detailFrom||'list';cache.saving=true;state.paymentFormSaving=true;if(btn){btn.disabled=true;btn.textContent='Saving…'}try{var r=await sb.rpc('crm_record_payment_with_credit_note',{p_schedule_id:row.id,p_cash_amount:Math.round(cash*100)/100,p_payment_date:cash>0?date:null,p_payment_reference:ref||null,p_remarks:remarks||null,p_credit_amount:Math.round(credit*100)/100,p_credit_issue_date:credit>0?creditDate:null,p_credit_reason:credit>0?creditReason:null,p_credit_reference:credit>0?(creditRef||null):null});if(r.error)throw r.error;closePanel();await loadFromSupabase();state.selectedUnit=key;state.detailFrom=from;state.view='detail';if(typeof window.renderMain==='function')window.renderMain();else if(typeof window.renderDetail==='function')window.renderDetail()}catch(e){cache.saving=false;state.paymentFormSaving=false;if(btn){btn.disabled=false;btn.textContent='Save payment'}setError(e&&e.message?e.message:'Could not save that payment.')}}
function targetFromEvent(e){if(!e||!e.target||!e.target.closest)return null;return e.target.closest('#btnOpenPaymentForm,#actionRecordPayment')}
document.addEventListener('click',function(e){var target=targetFromEvent(e);if(!target)return;if(!window.state||state.userRole!=='crm_officer')return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openPanel()},true);
window.addEventListener('popstate',closePanel);window.addEventListener('pageshow',function(){if(document.getElementById('recordPaymentReliablePanel'))closePanel()});
window.__sunblissOpenRecordPayment=openPanel;
ensureStyles();
})();
