(function(){
'use strict';
if(window.__sunblissSmartNewCustomerOverlayInstalled)return;
window.__sunblissSmartNewCustomerOverlayInstalled=true;
var RMS=['Farhan Ali','Mohammad Fayaz','Aarzo Akbar','Mohammed Shariq'];
var STAGES=[
 {code:'DP',label:'Down Payment'},
 {code:'1ST',label:'1st Installment'},
 {code:'DLD',label:'DLD + Admin Fees',admin:5100},
 {code:'2ND',label:'2nd Installment',extra:true},
 {code:'3RD',label:'3rd Installment',extra:true},
 {code:'4TH',label:'4th Installment',extra:true},
 {code:'5TH',label:'5th Installment',extra:true},
 {code:'6TH',label:'6th Installment',extra:true},
 {code:'7TH',label:'7th Installment',extra:true},
 {code:'FIN',label:'Final (Handover)',final:true}
];
var EXTRAS=STAGES.filter(function(s){return s.extra;}).map(function(s){return s.code;});
var FINAL_DATE='2027-10-31';
function txt(v){return v==null?'':String(v);}
function val(id){var e=document.getElementById(id);return e?txt(e.value).trim():'';}
function num(v){if(v==null||txt(v).trim()==='')return null;var n=Number(v);return isFinite(n)?n:null;}
function round(v){return Math.round((Number(v)||0)*100)/100;}
function safe(v){if(typeof window.esc==='function')return window.esc(txt(v));return txt(v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function ordinal(d){return d==='1'?'1st':d==='2'?'2nd':d==='3'?'3rd':d?d+'th':'';}
function floorFromUnit(v){var m=txt(v).trim().match(/-\s*(\d)/);return m?ordinal(m[1]):'';}
function currentUnitId(){if(!window.state||!state.selectedUnit)return null;var p=String(state.selectedUnit).split('::');return p.length>1&&Number(p[1])?Number(p[1]):null;}
function stage(code){for(var i=0;i<STAGES.length;i++)if(STAGES[i].code===code)return STAGES[i];return null;}
function ensureState(){if(!window.state)return;state.__smartNcPct=state.__smartNcPct||{};state.__smartNcVisible=Array.isArray(state.__smartNcVisible)?state.__smartNcVisible:[];}
function styles(){if(document.getElementById('smartNcStyles'))return;var s=document.createElement('style');s.id='smartNcStyles';s.textContent=[
 '#ncSoldBy{display:block;width:100%;margin-top:5px;padding:10px 11px;border:1px solid var(--paper-line);border-radius:8px;font:500 16px/1.2 Inter,sans-serif;color:var(--ink);background:var(--paper-dim);box-sizing:border-box}',
 '.smart-nc-stage{position:relative;display:grid!important;grid-template-columns:.72fr 1.15fr 1fr;gap:8px!important;align-items:end!important;margin-bottom:11px!important}',
 '.smart-nc-stage>label{flex:none!important;margin-bottom:0!important}.smart-nc-stage .smart-nc-pct{display:block}.smart-nc-stage input{width:100%}',
 '.smart-nc-stage.smart-nc-hidden{display:none!important}.smart-nc-stage input[readonly]{background:rgba(220,210,182,.45);color:var(--slate)}',
 '.smart-nc-hint{grid-column:1/-1;font-size:10.5px;line-height:1.4;color:var(--muted);margin:-2px 0 0}.smart-nc-hint b{color:var(--ink)}',
 '#smartNcAddStage{width:100%;justify-content:center;margin:0 0 12px}.smart-nc-auto-note{font-size:10.8px;line-height:1.45;color:var(--muted);margin:-5px 0 11px}',
 '#smartNcWarning{display:none;margin:0 0 11px;padding:9px 10px;border-radius:9px;border:1px solid rgba(174,59,43,.28);background:rgba(174,59,43,.07);color:var(--rust);font-size:11px;line-height:1.4}',
 '#smartNcIndividualNameWrap{margin:0 0 10px}.new-customer-channel-fields[hidden] #smartNcIndividualNameWrap{display:none!important}',
 '@media(max-width:520px){.smart-nc-stage{grid-template-columns:1fr 1fr}.smart-nc-stage>label:last-of-type{grid-column:1/-1}.smart-nc-hint{grid-column:1/-1}}'
].join('');document.head.appendChild(s);}
function insertNote(after,text){if(!after||!after.parentNode)return;var p=document.createElement('p');p.className='smart-nc-auto-note';p.textContent=text;after.insertAdjacentElement('afterend',p);}
function replaceRm(){var old=document.getElementById('ncSoldBy');if(!old||old.tagName==='SELECT')return;var sel=document.createElement('select');sel.id='ncSoldBy';sel.innerHTML='<option value="">Choose RM</option>'+RMS.map(function(r){return'<option value="'+safe(r)+'">'+safe(r)+'</option>';}).join('');if(RMS.indexOf(old.value)!==-1)sel.value=old.value;var label=old.closest('label.brand-field');if(label){var nodes=Array.prototype.slice.call(label.childNodes);nodes.forEach(function(n){if(n===old)return;});label.replaceChild(sel,old);}else old.replaceWith(sel);}
function decorateUnit(){var unit=document.getElementById('ncUnitNo'),floor=document.getElementById('ncFloor'),area=document.getElementById('ncArea'),rate=document.getElementById('ncPricePerSqft'),total=document.getElementById('ncTotalPrice');if(!unit||!floor||!area||!rate||!total)return;
 if(!unit.dataset.smartFloor){unit.dataset.smartFloor='1';floor.dataset.smartAuto=floorFromUnit(unit.value);floor.dataset.smartManual=(floor.value&&floor.dataset.smartAuto&&floor.value!==floor.dataset.smartAuto)?'1':'0';unit.addEventListener('input',function(){var next=floorFromUnit(unit.value),prior=floor.dataset.smartAuto||'';if(floor.dataset.smartManual!=='1'||!floor.value||floor.value===prior){floor.value=next;floor.dataset.smartAuto=next;floor.dataset.smartManual='0';}});floor.addEventListener('input',function(){floor.dataset.smartManual='1';});if(!floor.value){floor.value=floorFromUnit(unit.value);floor.dataset.smartAuto=floor.value;}}
 if(!area.dataset.smartTotal){area.dataset.smartTotal='1';var calc=function(){var a=num(area.value),r=num(rate.value);if(a===null||r===null||a<0||r<0)return;total.value=round(a*r).toFixed(2);total.dispatchEvent(new Event('input',{bubbles:true}));};area.addEventListener('input',calc);rate.addEventListener('input',calc);if(!total.value&&area.value&&rate.value)calc();}
 if(!floor.closest('label').nextElementSibling||!floor.closest('label').nextElementSibling.classList.contains('smart-nc-auto-note'))insertNote(floor.closest('label'),'Floor auto-fills from the first digit after the dash (A3-502 → 5th). You can overwrite it manually.');
 if(!total.closest('label').nextElementSibling||!total.closest('label').nextElementSibling.classList.contains('smart-nc-auto-note'))insertNote(total.closest('label'),'Total Price automatically recalculates as Area × Price / sqft.');
}
function individualName(){var box=document.getElementById('ncIndividualFields');if(!box)return;var wrap=document.getElementById('smartNcIndividualNameWrap');if(!wrap){wrap=document.createElement('label');wrap.className='brand-field';wrap.id='smartNcIndividualNameWrap';wrap.innerHTML='Individual source name<input type="text" id="ncIndividualSourceName" placeholder="Enter individual name" />';var section=box.querySelector('.section-label');if(section)section.insertAdjacentElement('afterend',wrap);else box.insertBefore(wrap,box.firstChild);var input=wrap.querySelector('input');input.value=state.__smartNcIndividualName||'';input.addEventListener('input',function(){state.__smartNcIndividualName=input.value;});}else{var i=wrap.querySelector('input');if(i&&!i.value&&state.__smartNcIndividualName)i.value=state.__smartNcIndividualName;}
 var src=document.getElementById('ncSource');if(src){Array.prototype.forEach.call(src.options,function(o){if(o.value==='Individual Buyer')o.textContent='Individual';});}}
function stageRowFor(code){var a=document.getElementById('ncAmt_'+code);if(!a)return null;var row=a.closest('div');if(!row||row.classList.contains('smart-nc-stage'))return row;row.classList.add('smart-nc-stage');row.dataset.stage=code;var s=stage(code);var pct=document.createElement('label');pct.className='brand-field smart-nc-pct';pct.innerHTML='%<input type="number" id="ncPct_'+code+'" min="0" max="100" step="0.01" inputmode="decimal" />';row.insertBefore(pct,row.firstChild);var p=pct.querySelector('input');p.value=state.__smartNcPct[code]||'';if(s.final){p.readOnly=true;a.readOnly=true;var d=document.getElementById('ncDate_FIN');if(d&&!d.value)d.value=FINAL_DATE;}else{p.addEventListener('input',function(){state.__smartNcPct[code]=p.value;calcStage(code);calcFinal();});a.addEventListener('input',function(){syncPct(code);calcFinal();});}
 if(s.admin||s.final){var h=document.createElement('p');h.className='smart-nc-hint';h.innerHTML=s.admin?'Percentage = <b>Total Price × % + AED 5,100</b> admin fee.':'Final due amount is the remaining balance. Due date defaults to <b>31 Oct 2027</b> and can be changed.';row.appendChild(h);}return row;}
function calcStage(code){var s=stage(code),p=num(val('ncPct_'+code)),t=num(val('ncTotalPrice')),a=document.getElementById('ncAmt_'+code);if(!s||s.final||!a||p===null||t===null)return;a.value=round(t*p/100+(s.admin||0)).toFixed(2);}
function syncPct(code){var s=stage(code),t=num(val('ncTotalPrice')),a=num(val('ncAmt_'+code)),p=document.getElementById('ncPct_'+code);if(!s||s.final||!p||t===null||t<=0||a===null)return;var base=a-(s.admin||0);if(base<0){p.value='';state.__smartNcPct[code]='';return;}p.value=(Math.round(base/t*100*10000)/10000).toString();state.__smartNcPct[code]=p.value;}
function calcAllPct(){STAGES.forEach(function(s){if(!s.final&&val('ncPct_'+s.code)!=='')calcStage(s.code);});}
function calcFinal(){var total=num(val('ncTotalPrice')),fa=document.getElementById('ncAmt_FIN'),fp=document.getElementById('ncPct_FIN'),warn=document.getElementById('smartNcWarning');if(!fa||!fp)return;var sum=0;STAGES.forEach(function(s){if(s.final)return;var row=document.querySelector('.smart-nc-stage[data-stage="'+s.code+'"]');if(!row||row.classList.contains('smart-nc-hidden'))return;var n=num(val('ncAmt_'+s.code));if(n!==null&&n>0)sum+=n;});if(total===null){fa.value='';fp.value='';return;}var rem=round(total-sum);if(rem<0)rem=0;fa.value=rem.toFixed(2);fp.value=total>0?(Math.round(rem/total*100*10000)/10000).toString():'0';if(warn){if(sum>total+.01){warn.textContent='Other installments exceed Total Price by AED '+round(sum-total).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+'. Reduce an installment before saving.';warn.style.display='block';}else{warn.textContent='';warn.style.display='none';}}}
function paymentSchedule(){ensureState();var anchor=null;STAGES.forEach(function(s){var row=stageRowFor(s.code);if(row&&!anchor)anchor=row;});var visible=state.__smartNcVisible;EXTRAS.forEach(function(c){var row=document.querySelector('.smart-nc-stage[data-stage="'+c+'"]');if(row)row.classList.toggle('smart-nc-hidden',visible.indexOf(c)===-1);});var fin=document.querySelector('.smart-nc-stage[data-stage="FIN"]');if(fin&&!document.getElementById('smartNcWarning')){var w=document.createElement('div');w.id='smartNcWarning';fin.parentNode.insertBefore(w,fin);}if(fin&&!document.getElementById('smartNcAddStage')&&visible.length<EXTRAS.length){var b=document.createElement('button');b.type='button';b.id='smartNcAddStage';b.className='btn-paper';b.textContent='+ Add another installment';fin.parentNode.insertBefore(b,fin);b.addEventListener('click',function(){var next=EXTRAS.find(function(c){return state.__smartNcVisible.indexOf(c)===-1;});if(next){state.__smartNcVisible.push(next);var r=document.querySelector('.smart-nc-stage[data-stage="'+next+'"]');if(r)r.classList.remove('smart-nc-hidden');}if(state.__smartNcVisible.length>=EXTRAS.length)b.remove();calcFinal();});}
 var total=document.getElementById('ncTotalPrice');if(total&&!total.dataset.smartSchedule){total.dataset.smartSchedule='1';total.addEventListener('input',function(){calcAllPct();calcFinal();});}calcAllPct();calcFinal();}
function bookingNote(){var b=document.getElementById('ncBookingAmount');if(!b)return;var l=b.closest('label');if(l&&(!l.nextElementSibling||!l.nextElementSibling.classList.contains('smart-nc-auto-note')))insertNote(l,'Booking Amount is automatically recorded in Transaction History after the customer is created.');}
function decorate(){if(!window.state||!document.getElementById('ncUnitNo'))return;ensureState();styles();replaceRm();decorateUnit();individualName();paymentSchedule();bookingNote();}
async function savePostCreate(baseSave){var individual=val('ncIndividualSourceName')||state.__smartNcIndividualName||'';var bookingAmount=num(val('ncBookingAmount'));var bookingDate=val('ncBookingDate');var source=val('ncSource');var pctSnapshot={};STAGES.forEach(function(s){pctSnapshot[s.code]=val('ncPct_'+s.code);});var other=0,total=num(val('ncTotalPrice'));STAGES.forEach(function(s){if(s.final)return;var r=document.querySelector('.smart-nc-stage[data-stage="'+s.code+'"]');if(!r||r.classList.contains('smart-nc-hidden'))return;var n=num(val('ncAmt_'+s.code));if(n!==null&&n>0)other+=n;});if(total!==null&&other>total+.01){state.newCustomerFormError='Other installments exceed Total Price. Reduce an installment before saving.';if(typeof window.renderNewCustomer==='function')window.renderNewCustomer();return;}
 await baseSave();if(state.newCustomerFormError||state.view!=='detail'||!state.selectedUnit)return;var unitId=currentUnitId();if(!unitId)return;try{if(source==='Individual Buyer'){var sr=await sb.from('sales').update({individual_source_name:individual||null,updated_at:new Date().toISOString()}).eq('unit_id',unitId);if(sr.error)throw sr.error;}if(bookingAmount!==null&&bookingAmount>0){var existing=await sb.from('payment_transactions').select('id').eq('unit_id',unitId).eq('payment_type','Booking Amount').eq('amount',round(bookingAmount)).limit(1);if(existing.error)throw existing.error;if(!(existing.data||[]).length){var ur=await sb.from('units').select('customer_id').eq('id',unitId).single();if(ur.error)throw ur.error;var tr=await sb.from('payment_transactions').insert({unit_id:unitId,customer_id:ur.data?ur.data.customer_id:null,payment_date:bookingDate||null,amount:round(bookingAmount),payment_type:'Booking Amount',remarks:'Auto-recorded from New Customer booking amount'});if(tr.error)throw tr.error;}}
 state.__smartNcPct={};state.__smartNcVisible=[];state.__smartNcIndividualName='';var key=state.selectedUnit,from=state.detailFrom||'list';await loadFromSupabase();state.selectedUnit=key;state.detailFrom=from;state.view='detail';if(typeof window.renderMain==='function')window.renderMain();}catch(e){alert('Customer created, but the smart post-save update needs attention: '+(e&&e.message?e.message:'Unknown error'));}}
async function enrichIndividual(){if(!window.sb||!window.state)return;var r=await sb.from('sales').select('unit_id,individual_source_name');if(r.error)throw r.error;var m={};(r.data||[]).forEach(function(x){m[String(x.unit_id)]=x.individual_source_name||'';});[state.dues,state.cancelled].forEach(function(list){if(!Array.isArray(list))return;list.forEach(function(c){if(!c)return;c.info=c.info||{};c.info.individualSourceName=m[String(c.sno)]||'';});});}
function showIndividual(){document.querySelectorAll('.smart-individual-source-detail').forEach(function(e){e.remove();});if(!window.state||state.view!=='detail'||!state.selectedUnit)return;var c=(state.dues||[]).find(function(x){return x&&(txt(x.unit)+'::'+txt(x.sno))===txt(state.selectedUnit);});var n=c&&c.info?txt(c.info.individualSourceName).trim():'';if(!n)return;var rows=Array.prototype.slice.call(document.querySelectorAll('.detail .field-row'));var src=rows.find(function(r){var l=r.querySelector('.field-label');return l&&txt(l.textContent).trim().toLowerCase()==='source';});if(!src)return;var d=document.createElement('div');d.className='field-row smart-individual-source-detail';d.innerHTML='<span class="field-label">Individual source</span><span class="field-value">'+safe(n)+'</span>';src.insertAdjacentElement('afterend',d);}
function install(){if(!window.state||!window.sb||typeof window.saveNewCustomer!=='function'||typeof window.loadFromSupabase!=='function'){setTimeout(install,50);return;}styles();var base=window.saveNewCustomer;window.saveNewCustomer=function(){return savePostCreate(base);};var load=window.loadFromSupabase;window.loadFromSupabase=async function(){var r=await load.apply(this,arguments);try{await enrichIndividual();}catch(e){console.warn('Could not load individual source names',e);}return r;};if(typeof window.renderDetail==='function'){var rd=window.renderDetail;window.renderDetail=function(){var r=rd.apply(this,arguments);showIndividual();return r;};}var app=document.getElementById('app')||document.body;new MutationObserver(function(){requestAnimationFrame(decorate);}).observe(app,{childList:true,subtree:true});decorate();enrichIndividual().then(showIndividual).catch(function(){});}
install();
})();
