create table if not exists public.credit_notes (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  unit_id bigint not null references public.units(id) on delete cascade,
  payment_schedule_id bigint not null references public.payment_schedule(id) on delete cascade,
  issue_date date not null,
  amount numeric not null check (amount > 0),
  reason text not null check (length(btrim(reason)) > 0),
  reference_number text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists idx_credit_notes_schedule on public.credit_notes(payment_schedule_id);
create index if not exists idx_credit_notes_unit on public.credit_notes(unit_id);
create index if not exists idx_credit_notes_customer on public.credit_notes(customer_id);
create index if not exists idx_credit_notes_issue_date on public.credit_notes(issue_date);

alter table public.credit_notes enable row level security;

drop policy if exists "approved profiles read credit_notes" on public.credit_notes;
create policy "approved profiles read credit_notes"
on public.credit_notes for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role::text = any(array['crm_officer'::text,'manager'::text])
  )
);

drop policy if exists "crm write credit_notes" on public.credit_notes;
create policy "crm write credit_notes"
on public.credit_notes for all
to public
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'crm_officer'::public.user_role
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'crm_officer'::public.user_role
  )
);

create or replace function public.crm_set_payment_schedule_status_with_credits()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credit numeric := 0;
  v_settled numeric := 0;
begin
  if new.id is not null then
    select coalesce(sum(cn.amount),0)
      into v_credit
      from public.credit_notes cn
     where cn.payment_schedule_id = new.id;
  end if;

  v_settled := coalesce(new.paid_amount,0) + v_credit;

  if new.due_amount is null then
    new.status := coalesce(new.status,'Outstanding');
  elsif v_settled >= coalesce(new.due_amount,0) - 0.01 and coalesce(new.due_amount,0) > 0 then
    new.status := 'Paid';
  elsif v_settled > 0 then
    new.status := 'Partial';
  else
    new.status := 'Outstanding';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_payment_schedule_status_with_credits on public.payment_schedule;
create trigger trg_payment_schedule_status_with_credits
before insert or update of due_amount, paid_amount, status
on public.payment_schedule
for each row execute function public.crm_set_payment_schedule_status_with_credits();

create or replace function public.crm_refresh_schedule_after_credit_note()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_schedule bigint;
  v_new_schedule bigint;
begin
  v_old_schedule := case when tg_op in ('UPDATE','DELETE') then old.payment_schedule_id else null end;
  v_new_schedule := case when tg_op in ('INSERT','UPDATE') then new.payment_schedule_id else null end;

  if v_old_schedule is not null then
    update public.payment_schedule
       set status = status,
           updated_at = now()
     where id = v_old_schedule;
  end if;

  if v_new_schedule is not null and v_new_schedule is distinct from v_old_schedule then
    update public.payment_schedule
       set status = status,
           updated_at = now()
     where id = v_new_schedule;
  elsif v_new_schedule is not null and tg_op = 'INSERT' then
    update public.payment_schedule
       set status = status,
           updated_at = now()
     where id = v_new_schedule;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_credit_notes_refresh_schedule on public.credit_notes;
create trigger trg_credit_notes_refresh_schedule
after insert or update or delete
on public.credit_notes
for each row execute function public.crm_refresh_schedule_after_credit_note();

create or replace function public.crm_record_payment_with_credit_note(
  p_schedule_id bigint,
  p_cash_amount numeric default 0,
  p_payment_date date default null,
  p_payment_reference text default null,
  p_remarks text default null,
  p_credit_amount numeric default 0,
  p_credit_issue_date date default null,
  p_credit_reason text default null,
  p_credit_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_schedule public.payment_schedule%rowtype;
  v_cash numeric := coalesce(p_cash_amount,0);
  v_credit numeric := coalesce(p_credit_amount,0);
  v_new_cash numeric;
  v_total_credit numeric;
  v_status text;
  v_tx_id bigint;
  v_credit_id bigint;
begin
  if not exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'crm_officer'::public.user_role
  ) then
    raise exception 'Only CRM officers can record payments or credit notes.';
  end if;

  if v_cash < 0 or v_credit < 0 then
    raise exception 'Cash and credit note amounts cannot be negative.';
  end if;
  if v_cash <= 0 and v_credit <= 0 then
    raise exception 'Enter a cash payment, a credit note, or both.';
  end if;
  if v_cash > 0 and p_payment_date is null then
    raise exception 'Payment date is required when cash is recorded.';
  end if;
  if v_credit > 0 and p_credit_issue_date is null then
    raise exception 'Credit note issue date is required.';
  end if;
  if v_credit > 0 and length(btrim(coalesce(p_credit_reason,''))) = 0 then
    raise exception 'Credit note reason is required.';
  end if;

  select *
    into v_schedule
    from public.payment_schedule
   where id = p_schedule_id
   for update;

  if not found then
    raise exception 'Installment schedule not found.';
  end if;

  if v_cash > 0 then
    insert into public.payment_transactions(
      customer_id,unit_id,payment_date,amount,payment_type,payment_reference,remarks
    ) values (
      v_schedule.customer_id,v_schedule.unit_id,p_payment_date,v_cash,v_schedule.stage_name,
      nullif(btrim(p_payment_reference),''),nullif(btrim(p_remarks),'')
    ) returning id into v_tx_id;
  end if;

  if v_credit > 0 then
    insert into public.credit_notes(
      customer_id,unit_id,payment_schedule_id,issue_date,amount,reason,reference_number,created_by
    ) values (
      v_schedule.customer_id,v_schedule.unit_id,v_schedule.id,p_credit_issue_date,v_credit,
      btrim(p_credit_reason),nullif(btrim(p_credit_reference),''),auth.uid()
    ) returning id into v_credit_id;
  end if;

  v_new_cash := coalesce(v_schedule.paid_amount,0) + v_cash;

  select coalesce(sum(amount),0)
    into v_total_credit
    from public.credit_notes
   where payment_schedule_id = v_schedule.id;

  if v_schedule.due_amount is not null
     and v_schedule.due_amount > 0
     and v_new_cash + v_total_credit >= v_schedule.due_amount - 0.01 then
    v_status := 'Paid';
  elsif v_new_cash + v_total_credit > 0 then
    v_status := 'Partial';
  else
    v_status := 'Outstanding';
  end if;

  update public.payment_schedule
     set paid_amount = v_new_cash,
         paid_date = case when v_cash > 0 then p_payment_date else paid_date end,
         status = v_status,
         updated_at = now()
   where id = v_schedule.id;

  return jsonb_build_object(
    'schedule_id',v_schedule.id,
    'transaction_id',v_tx_id,
    'credit_note_id',v_credit_id,
    'cash_paid',v_new_cash,
    'credit_notes',v_total_credit,
    'settled',v_new_cash + v_total_credit,
    'status',v_status
  );
end;
$$;

revoke all on function public.crm_record_payment_with_credit_note(bigint,numeric,date,text,text,numeric,date,text,text) from public;
revoke all on function public.crm_record_payment_with_credit_note(bigint,numeric,date,text,text,numeric,date,text,text) from anon;
grant execute on function public.crm_record_payment_with_credit_note(bigint,numeric,date,text,text,numeric,date,text,text) to authenticated;

comment on table public.credit_notes is 'Paperwork credit notes applied against specific installment schedules; separate from cash payments.';
