-- Professional but simple customer modification-request workflow.

create table if not exists public.modification_requests (
  id bigint generated by default as identity primary key,
  request_no text unique,
  customer_id bigint references public.customers(id) on delete set null,
  unit_id bigint not null references public.units(id) on delete cascade,
  title text not null,
  details text,
  received_via text not null
    check (received_via in ('Email','WhatsApp','Call','Letter','In Person','Other')),
  request_date date not null,
  status text not null default 'under_review'
    check (status in (
      'under_review',
      'clarification_required',
      'approval_pending',
      'awaiting_customer_confirmation',
      'execution',
      'completed',
      'not_feasible',
      'rejected',
      'withdrawn'
    )),
  step text not null default 'review'
    check (step in (
      'review',
      'clarification',
      'management_approval',
      'send_confirmation',
      'customer_confirmation',
      'inform_customer',
      'execution',
      'closed'
    )),
  revision_no integer not null default 0 check (revision_no >= 0),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.modification_request_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.modification_requests(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  note text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists modification_requests_unit_idx
  on public.modification_requests(unit_id,status,updated_at desc);

create index if not exists modification_request_events_request_idx
  on public.modification_request_events(request_id,created_at,id);

alter table public.scheduled_actions
  add column if not exists modification_request_id bigint
  references public.modification_requests(id) on delete set null;

create index if not exists scheduled_actions_modification_request_idx
  on public.scheduled_actions(modification_request_id);

alter table public.scheduled_actions
  drop constraint if exists scheduled_actions_workflow_kind_check;

alter table public.scheduled_actions
  add constraint scheduled_actions_workflow_kind_check
  check (
    workflow_kind is null or workflow_kind in (
      'accounts_confirmation',
      'cheque_clearance',
      'payment_receipt',
      'promise_follow_up',
      'payment_query',
      'payment_follow_up',
      'payment_review',
      'partial_payment_commitment',
      'payment_reported',
      'extension_approval',
      'modification_request'
    )
  );

alter table public.modification_requests enable row level security;
alter table public.modification_request_events enable row level security;

create or replace function public.crm_create_modification_request(
  p_unit_id bigint,
  p_title text,
  p_details text default null,
  p_received_via text default 'Email',
  p_request_date date default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_customer_id bigint;
  v_request_id bigint;
  v_task_id bigint;
  v_user uuid := auth.uid();
  v_now timestamptz := now();
  v_today date := (now() at time zone 'Asia/Dubai')::date;
  v_request_date date := coalesce(p_request_date,(now() at time zone 'Asia/Dubai')::date);
  v_title text := btrim(coalesce(p_title,''));
  v_details text := nullif(btrim(coalesce(p_details,'')),'');
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to record modification requests.';
  end if;

  if char_length(v_title) < 3 then
    raise exception 'Enter a short modification request title.';
  end if;

  if p_received_via not in ('Email','WhatsApp','Call','Letter','In Person','Other') then
    raise exception 'Select how the modification request was received.';
  end if;

  select u.customer_id into v_customer_id
  from public.units u
  where u.id=p_unit_id;

  if not found then
    raise exception 'Customer unit not found.';
  end if;

  insert into public.modification_requests(
    customer_id,unit_id,title,details,received_via,request_date,
    status,step,revision_no,created_by,created_at,updated_at
  ) values (
    v_customer_id,p_unit_id,v_title,v_details,p_received_via,v_request_date,
    'under_review','review',0,v_user,v_now,v_now
  )
  returning id into v_request_id;

  update public.modification_requests
     set request_no='MR-'||lpad(v_request_id::text,6,'0')
   where id=v_request_id;

  insert into public.modification_request_events(
    request_id,event_type,from_status,to_status,note,created_by,created_at
  ) values (
    v_request_id,'request_received',null,'under_review',
    'Request received via '||p_received_via||
      case when v_details is not null then '. '||v_details else '' end,
    v_user,v_now
  );

  insert into public.scheduled_actions(
    unit_id,action_label,due_date,priority,note,status,owner_id,
    source,auto_kind,auto_key,schedule_id,transaction_id,workflow_kind,
    commitment_part_id,extension_request_id,modification_request_id,
    created_at,updated_at
  ) values (
    p_unit_id,'Review Modification Request',v_today,'Medium',
    v_title,'pending',v_user,
    'manual',null,'modification|request:'||v_request_id::text,
    null,null,'modification_request',
    null,null,v_request_id,
    v_now,v_now
  )
  returning id into v_task_id;

  return jsonb_build_object(
    'request_id',v_request_id,
    'request_no','MR-'||lpad(v_request_id::text,6,'0'),
    'task_id',v_task_id,
    'status','under_review',
    'step','review',
    'next_action','Review Modification Request'
  );
end;
$function$;

create or replace function public.crm_get_modification_requests(p_unit_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_result jsonb;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to view modification requests.';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id',r.id,
        'request_no',r.request_no,
        'unit_id',r.unit_id,
        'title',r.title,
        'details',r.details,
        'received_via',r.received_via,
        'request_date',r.request_date,
        'status',r.status,
        'step',r.step,
        'revision_no',r.revision_no,
        'created_at',r.created_at,
        'updated_at',r.updated_at,
        'closed_at',r.closed_at,
        'task',(
          select jsonb_build_object(
            'id',a.id,
            'unit_id',a.unit_id,
            'action_label',a.action_label,
            'due_date',a.due_date,
            'priority',a.priority,
            'note',a.note,
            'status',a.status,
            'workflow_kind',a.workflow_kind,
            'modification_request_id',a.modification_request_id
          )
          from public.scheduled_actions a
          where a.modification_request_id=r.id
            and a.status='pending'
          order by a.updated_at desc,a.id desc
          limit 1
        )
      )
      order by
        case when r.step='closed' then 1 else 0 end,
        r.updated_at desc,
        r.id desc
    ),
    '[]'::jsonb
  )
  into v_result
  from public.modification_requests r
  where r.unit_id=p_unit_id;

  return v_result;
end;
$function$;

create or replace function public.crm_get_modification_request(p_request_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_result jsonb;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to view modification requests.';
  end if;

  select jsonb_build_object(
    'request',to_jsonb(r),
    'events',coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id',e.id,
          'event_type',e.event_type,
          'from_status',e.from_status,
          'to_status',e.to_status,
          'note',e.note,
          'created_at',e.created_at
        ) order by e.created_at,e.id
      )
      from public.modification_request_events e
      where e.request_id=r.id
    ),'[]'::jsonb),
    'task',(
      select to_jsonb(a)
      from public.scheduled_actions a
      where a.modification_request_id=r.id
        and a.status='pending'
      order by a.updated_at desc,a.id desc
      limit 1
    )
  )
  into v_result
  from public.modification_requests r
  where r.id=p_request_id;

  if v_result is null then
    raise exception 'Modification request not found.';
  end if;

  return v_result;
end;
$function$;

create or replace function public.crm_advance_modification_request(
  p_task_id bigint,
  p_outcome text,
  p_note text default null,
  p_next_date date default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_task public.scheduled_actions%rowtype;
  v_req public.modification_requests%rowtype;
  v_user uuid := auth.uid();
  v_now timestamptz := now();
  v_today date := (now() at time zone 'Asia/Dubai')::date;
  v_from_status text;
  v_to_status text;
  v_event text;
  v_action text;
  v_due date;
  v_priority text := 'Medium';
  v_new_step text;
  v_close boolean := false;
  v_note text := nullif(btrim(coalesce(p_note,'')),'');
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to update modification requests.';
  end if;

  select * into v_task
  from public.scheduled_actions
  where id=p_task_id
  for update;

  if not found
     or v_task.status<>'pending'
     or v_task.workflow_kind<>'modification_request'
     or v_task.modification_request_id is null then
    raise exception 'Pending modification workflow task not found.';
  end if;

  select * into v_req
  from public.modification_requests
  where id=v_task.modification_request_id
  for update;

  if not found or v_req.step='closed' then
    raise exception 'Active modification request not found.';
  end if;

  v_from_status := v_req.status;

  if v_req.step='review' then
    if p_outcome='feasible' then
      v_to_status:='under_review'; v_new_step:='send_confirmation';
      v_action:='Send Final Modification Confirmation'; v_due:=v_today;
      v_event:='feasible';
    elsif p_outcome='clarification_required' then
      if p_next_date is null then raise exception 'Select the customer follow-up date.'; end if;
      v_to_status:='clarification_required'; v_new_step:='clarification';
      v_action:='Follow up for Modification Clarification'; v_due:=p_next_date;
      v_priority:='High'; v_event:='clarification_required';
    elsif p_outcome='management_approval_required' then
      v_to_status:='approval_pending'; v_new_step:='management_approval';
      v_action:='Management Approval — Modification Request'; v_due:=v_today;
      v_priority:='High'; v_event:='management_approval_required';
    elsif p_outcome='not_feasible' then
      v_to_status:='not_feasible'; v_new_step:='inform_customer';
      v_action:='Inform Customer — Modification Not Feasible'; v_due:=v_today;
      v_priority:='High'; v_event:='not_feasible';
    else
      raise exception 'Select a valid review outcome.';
    end if;

  elsif v_req.step='clarification' then
    if p_outcome='clarified' then
      v_to_status:='under_review'; v_new_step:='review';
      v_action:='Review Modification Request'; v_due:=v_today;
      v_event:='clarification_received';
    elsif p_outcome='no_response' then
      if p_next_date is null then raise exception 'Select the next follow-up date.'; end if;
      v_to_status:='clarification_required'; v_new_step:='clarification';
      v_action:='Follow up for Modification Clarification'; v_due:=p_next_date;
      v_priority:='High'; v_event:='no_response';
    elsif p_outcome='withdrawn' then
      v_to_status:='withdrawn'; v_new_step:='closed';
      v_event:='withdrawn'; v_close:=true;
    else
      raise exception 'Select a valid clarification outcome.';
    end if;

  elsif v_req.step='management_approval' then
    if p_outcome='approved' then
      v_to_status:='under_review'; v_new_step:='send_confirmation';
      v_action:='Send Final Modification Confirmation'; v_due:=v_today;
      v_event:='management_approved';
    elsif p_outcome='rejected' then
      v_to_status:='rejected'; v_new_step:='inform_customer';
      v_action:='Inform Customer — Modification Rejected'; v_due:=v_today;
      v_priority:='High'; v_event:='management_rejected';
    else
      raise exception 'Select Approved or Rejected.';
    end if;

  elsif v_req.step='send_confirmation' then
    if p_outcome<>'sent' then raise exception 'Mark the final confirmation as sent.'; end if;
    v_to_status:='awaiting_customer_confirmation'; v_new_step:='customer_confirmation';
    v_action:='Await Customer Confirmation'; v_due:=coalesce(p_next_date,v_today+3);
    v_event:='final_confirmation_sent';

  elsif v_req.step='customer_confirmation' then
    if p_outcome='confirmed' then
      v_to_status:='execution'; v_new_step:='execution';
      v_action:='Execute Modification'; v_due:=v_today;
      v_event:='customer_confirmed';
    elsif p_outcome='revision_requested' then
      if v_note is null then raise exception 'Enter the revised request/details.'; end if;
      v_to_status:='under_review'; v_new_step:='review';
      v_action:='Review Revised Modification Request'; v_due:=v_today;
      v_event:='revision_requested';
    elsif p_outcome='no_response' then
      if p_next_date is null then raise exception 'Select the next follow-up date.'; end if;
      v_to_status:='awaiting_customer_confirmation'; v_new_step:='customer_confirmation';
      v_action:='Await Customer Confirmation'; v_due:=p_next_date;
      v_event:='no_response';
    elsif p_outcome='withdrawn' then
      v_to_status:='withdrawn'; v_new_step:='closed';
      v_event:='withdrawn'; v_close:=true;
    else
      raise exception 'Select a valid customer outcome.';
    end if;

  elsif v_req.step='inform_customer' then
    if p_outcome<>'informed' then raise exception 'Mark the customer as informed.'; end if;
    v_to_status:=v_req.status; v_new_step:='closed';
    v_event:='customer_informed'; v_close:=true;

  elsif v_req.step='execution' then
    if p_outcome<>'completed' then raise exception 'Mark the modification as completed.'; end if;
    v_to_status:='completed'; v_new_step:='closed';
    v_event:='completed'; v_close:=true;

  else
    raise exception 'Unsupported modification workflow step.';
  end if;

  update public.modification_requests
     set status=v_to_status,
         step=v_new_step,
         revision_no=case when v_event='revision_requested' then revision_no+1 else revision_no end,
         details=case when v_event='revision_requested' and v_note is not null then v_note else details end,
         updated_at=v_now,
         closed_at=case when v_close then v_now else null end
   where id=v_req.id;

  insert into public.modification_request_events(
    request_id,event_type,from_status,to_status,note,created_by,created_at
  ) values (
    v_req.id,v_event,v_from_status,v_to_status,v_note,v_user,v_now
  );

  if v_close then
    update public.scheduled_actions
       set status='completed',
           completed_at=v_now,
           completion_note=coalesce(v_note,
             case
               when v_to_status='completed' then 'Modification completed.'
               when v_to_status='withdrawn' then 'Modification request withdrawn.'
               else 'Customer informed and request closed.'
             end),
           updated_at=v_now
     where id=v_task.id;
  else
    update public.scheduled_actions
       set action_label=v_action,
           due_date=v_due,
           priority=v_priority,
           note=case
             when v_note is not null then v_note
             when v_event='final_confirmation_sent' then 'Final modification confirmation sent. Awaiting customer confirmation.'
             when v_event='customer_confirmed' then 'Customer confirmed the final modification scope.'
             else v_task.note
           end,
           status='pending',
           source='manual',
           auto_kind=null,
           auto_key='modification|request:'||v_req.id::text,
           schedule_id=null,
           transaction_id=null,
           workflow_kind='modification_request',
           commitment_part_id=null,
           extension_request_id=null,
           modification_request_id=v_req.id,
           completed_at=null,
           completion_note=null,
           cancelled_at=null,
           updated_at=v_now
     where id=v_task.id;
  end if;

  return jsonb_build_object(
    'request_id',v_req.id,
    'request_no',v_req.request_no,
    'task_id',v_task.id,
    'status',v_to_status,
    'step',v_new_step,
    'next_action',case when v_close then null else v_action end,
    'closed',v_close
  );
end;
$function$;

grant execute on function public.crm_create_modification_request(bigint,text,text,text,date) to authenticated;
grant execute on function public.crm_get_modification_requests(bigint) to authenticated;
grant execute on function public.crm_get_modification_request(bigint) to authenticated;
grant execute on function public.crm_advance_modification_request(bigint,text,text,date) to authenticated;
