create table if not exists public.payment_schedule_deletion_log (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null,
  customer_id bigint,
  unit_id bigint not null,
  stage_name text not null,
  deleted_row jsonb not null,
  reason text not null,
  deleted_at timestamptz not null default now(),
  deleted_by uuid not null
);

create index if not exists payment_schedule_deletion_log_unit_idx
  on public.payment_schedule_deletion_log(unit_id, deleted_at desc);
create index if not exists payment_schedule_deletion_log_schedule_idx
  on public.payment_schedule_deletion_log(schedule_id);

alter table public.payment_schedule_deletion_log enable row level security;

grant select, insert on public.payment_schedule_deletion_log to authenticated;
grant usage, select on sequence public.payment_schedule_deletion_log_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='payment_schedule_deletion_log'
      and policyname='approved profiles read payment schedule deletion log'
  ) then
    create policy "approved profiles read payment schedule deletion log"
      on public.payment_schedule_deletion_log
      for select
      to authenticated
      using (
        exists (
          select 1 from public.profiles
          where id=(select auth.uid())
            and role::text in ('crm_officer','manager')
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='payment_schedule_deletion_log'
      and policyname='crm insert payment schedule deletion log'
  ) then
    create policy "crm insert payment schedule deletion log"
      on public.payment_schedule_deletion_log
      for insert
      to authenticated
      with check (
        deleted_by=(select auth.uid())
        and exists (
          select 1 from public.profiles
          where id=(select auth.uid())
            and role::text='crm_officer'
        )
      );
  end if;
end $$;

create or replace function public.crm_delete_installment(
  p_schedule_id bigint,
  p_unit_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_row public.payment_schedule%rowtype;
  v_reason text;
  v_tx_count integer;
  v_cn_count integer;
  v_carry_count integer;
  v_audit_id bigint;
  v_rows integer;
begin
  if not exists (
    select 1 from public.profiles
    where id=(select auth.uid())
      and role::text='crm_officer'
  ) then
    raise exception 'Only CRM Officers can delete installments.';
  end if;

  if p_schedule_id is null or p_unit_id is null then
    raise exception 'Installment and unit are required.';
  end if;

  v_reason := nullif(btrim(coalesce(p_reason,'')),'');
  if v_reason is null or length(v_reason) < 5 then
    raise exception 'Enter a short reason for deleting this installment.';
  end if;

  select * into v_row
  from public.payment_schedule
  where id=p_schedule_id
    and unit_id=p_unit_id
  for update;

  if not found then
    raise exception 'Installment schedule row not found. Refresh and try again.';
  end if;

  if coalesce(v_row.paid_amount,0) <> 0 or v_row.paid_date is not null then
    raise exception 'This installment cannot be deleted because it already has payment activity.';
  end if;

  select count(*) into v_tx_count
  from public.payment_transactions pt
  where pt.unit_id=v_row.unit_id
    and (
      pt.payment_schedule_id=v_row.id
      or (
        pt.payment_schedule_id is null
        and (
          (v_row.stage_name='DLD + Admin Fees (SPA)' and lower(coalesce(pt.payment_type,'')) like '%dld%')
          or (v_row.stage_name like 'Final Installment%' and lower(coalesce(pt.payment_type,'')) like 'final%')
          or lower(coalesce(pt.payment_type,'')) like lower(v_row.stage_name) || '%'
          or lower(coalesce(pt.payment_type,'')) like lower(replace(v_row.stage_name,'Installment','Instalment')) || '%'
        )
      )
    );

  if v_tx_count > 0 then
    raise exception 'This installment cannot be deleted because % payment transaction(s) are linked or match this stage.', v_tx_count;
  end if;

  select count(*) into v_cn_count
  from public.credit_notes
  where payment_schedule_id=v_row.id;
  if v_cn_count > 0 then
    raise exception 'This installment cannot be deleted because % credit note(s) are linked to it.', v_cn_count;
  end if;

  select count(*) into v_carry_count
  from public.carry_forward_events
  where payment_schedule_id=v_row.id;
  if v_carry_count > 0 then
    raise exception 'This installment cannot be deleted because % carry-forward event(s) are linked to it.', v_carry_count;
  end if;

  insert into public.payment_schedule_deletion_log(
    schedule_id, customer_id, unit_id, stage_name, deleted_row, reason, deleted_by
  ) values (
    v_row.id, v_row.customer_id, v_row.unit_id, v_row.stage_name, to_jsonb(v_row), v_reason, (select auth.uid())
  ) returning id into v_audit_id;

  delete from public.payment_schedule
  where id=v_row.id
    and unit_id=v_row.unit_id
    and coalesce(paid_amount,0)=0
    and paid_date is null;

  get diagnostics v_rows=row_count;
  if v_rows <> 1 then
    raise exception 'Installment changed before deletion. Refresh and try again.';
  end if;

  return jsonb_build_object(
    'deleted',true,
    'schedule_id',v_row.id,
    'unit_id',v_row.unit_id,
    'stage_name',v_row.stage_name,
    'audit_id',v_audit_id
  );
end;
$$;

revoke all on function public.crm_delete_installment(bigint,bigint,text) from public;
revoke all on function public.crm_delete_installment(bigint,bigint,text) from anon;
grant execute on function public.crm_delete_installment(bigint,bigint,text) to authenticated;
