-- Separate signed carry-forward ledger for installment over/underpayments.
-- Scheduled amounts and actual payment transaction amounts remain immutable accounting concepts.

alter table public.payment_transactions
  add column if not exists payment_schedule_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'payment_transactions_payment_schedule_id_fkey'
      and conrelid = 'public.payment_transactions'::regclass
  ) then
    alter table public.payment_transactions
      add constraint payment_transactions_payment_schedule_id_fkey
      foreign key (payment_schedule_id) references public.payment_schedule(id) on delete set null;
  end if;
end $$;

create index if not exists idx_payment_transactions_schedule
  on public.payment_transactions(payment_schedule_id);

create table if not exists public.carry_forward_events (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  unit_id bigint not null references public.units(id) on delete cascade,
  payment_schedule_id bigint not null references public.payment_schedule(id) on delete cascade,
  payment_transaction_id bigint references public.payment_transactions(id) on delete set null,
  event_date date not null,
  amount numeric not null check (abs(amount) >= 0.01),
  reason text not null default 'Payment variance',
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.carry_forward_allocations (
  id bigint generated by default as identity primary key,
  positive_event_id bigint not null references public.carry_forward_events(id) on delete cascade,
  negative_event_id bigint not null references public.carry_forward_events(id) on delete cascade,
  amount numeric not null check (amount > 0),
  allocation_date date not null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  reversed_at timestamptz,
  reversed_by uuid references auth.users(id) on delete set null,
  reversal_reason text,
  check (positive_event_id <> negative_event_id)
);

create index if not exists idx_carry_forward_events_schedule
  on public.carry_forward_events(payment_schedule_id,event_date,id);
create index if not exists idx_carry_forward_events_unit
  on public.carry_forward_events(unit_id,event_date,id);
create index if not exists idx_carry_forward_events_transaction
  on public.carry_forward_events(payment_transaction_id);
create index if not exists idx_carry_forward_allocations_positive
  on public.carry_forward_allocations(positive_event_id);
create index if not exists idx_carry_forward_allocations_negative
  on public.carry_forward_allocations(negative_event_id);
create index if not exists idx_carry_forward_allocations_active
  on public.carry_forward_allocations(positive_event_id,negative_event_id)
  where reversed_at is null;

alter table public.carry_forward_events enable row level security;
alter table public.carry_forward_allocations enable row level security;

drop policy if exists "approved profiles read carry_forward_events" on public.carry_forward_events;
create policy "approved profiles read carry_forward_events"
on public.carry_forward_events for select to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role::text = any(array['crm_officer'::text,'manager'::text])
  )
);

drop policy if exists "approved profiles read carry_forward_allocations" on public.carry_forward_allocations;
create policy "approved profiles read carry_forward_allocations"
on public.carry_forward_allocations for select to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role::text = any(array['crm_officer'::text,'manager'::text])
  )
);

grant select,insert,update,delete on public.carry_forward_events to authenticated;
grant select,insert,update,delete on public.carry_forward_allocations to authenticated;

create or replace function public.crm_rebalance_unit_carry(
  p_unit_id bigint,
  p_allocation_date date default current_date,
  p_reason text default 'Carry-forward recalculation'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pos record;
  v_neg record;
  v_pos_remaining numeric;
  v_neg_remaining numeric;
  v_amount numeric;
  v_created integer := 0;
  v_reversed integer := 0;
  v_balance numeric := 0;
begin
  if p_unit_id is null then
    raise exception 'Unit is required for carry-forward reconciliation.';
  end if;

  update public.carry_forward_allocations a
     set reversed_at = now(),
         reversed_by = auth.uid(),
         reversal_reason = coalesce(nullif(btrim(p_reason),''),'Carry-forward recalculation')
   where a.reversed_at is null
     and exists (
       select 1 from public.carry_forward_events e
       where e.id in (a.positive_event_id,a.negative_event_id)
         and e.unit_id = p_unit_id
     );
  get diagnostics v_reversed = row_count;

  create temporary table if not exists pg_temp.cf_positive(
    schedule_id bigint primary key,
    event_id bigint not null,
    event_date date not null,
    remaining numeric not null
  ) on commit drop;
  truncate pg_temp.cf_positive;

  create temporary table if not exists pg_temp.cf_negative(
    schedule_id bigint primary key,
    event_id bigint not null,
    event_date date not null,
    remaining numeric not null
  ) on commit drop;
  truncate pg_temp.cf_negative;

  insert into pg_temp.cf_positive(schedule_id,event_id,event_date,remaining)
  select x.payment_schedule_id,
         (select e2.id from public.carry_forward_events e2 where e2.payment_schedule_id=x.payment_schedule_id order by e2.event_date desc,e2.id desc limit 1),
         (select e3.event_date from public.carry_forward_events e3 where e3.payment_schedule_id=x.payment_schedule_id order by e3.event_date,e3.id limit 1),
         round(x.position,2)
  from (
    select e.payment_schedule_id,sum(e.amount) as position
    from public.carry_forward_events e
    where e.unit_id=p_unit_id
    group by e.payment_schedule_id
    having sum(e.amount) > 0.009
  ) x;

  insert into pg_temp.cf_negative(schedule_id,event_id,event_date,remaining)
  select x.payment_schedule_id,
         (select e2.id from public.carry_forward_events e2 where e2.payment_schedule_id=x.payment_schedule_id order by e2.event_date desc,e2.id desc limit 1),
         (select e3.event_date from public.carry_forward_events e3 where e3.payment_schedule_id=x.payment_schedule_id order by e3.event_date,e3.id limit 1),
         round(abs(x.position),2)
  from (
    select e.payment_schedule_id,sum(e.amount) as position
    from public.carry_forward_events e
    where e.unit_id=p_unit_id
    group by e.payment_schedule_id
    having sum(e.amount) < -0.009
  ) x;

  for v_pos in select * from pg_temp.cf_positive order by event_date,event_id loop
    select remaining into v_pos_remaining from pg_temp.cf_positive where schedule_id=v_pos.schedule_id;
    if v_pos_remaining < 0.01 then continue; end if;

    for v_neg in select * from pg_temp.cf_negative where remaining >= 0.01 order by event_date,event_id loop
      select remaining into v_pos_remaining from pg_temp.cf_positive where schedule_id=v_pos.schedule_id;
      exit when v_pos_remaining < 0.01;
      select remaining into v_neg_remaining from pg_temp.cf_negative where schedule_id=v_neg.schedule_id;
      if v_neg_remaining < 0.01 then continue; end if;

      v_amount := least(v_pos_remaining,v_neg_remaining);
      insert into public.carry_forward_allocations(
        positive_event_id,negative_event_id,amount,allocation_date,created_by
      ) values (
        v_pos.event_id,v_neg.event_id,v_amount,coalesce(p_allocation_date,current_date),auth.uid()
      );
      v_created := v_created + 1;
      update pg_temp.cf_positive set remaining=round(remaining-v_amount,2) where schedule_id=v_pos.schedule_id;
      update pg_temp.cf_negative set remaining=round(remaining-v_amount,2) where schedule_id=v_neg.schedule_id;
    end loop;
  end loop;

  update public.payment_schedule ps
     set status=ps.status,updated_at=now()
   where ps.unit_id=p_unit_id;

  select round(coalesce(sum(e.amount),0),2)
    into v_balance
    from public.carry_forward_events e
   where e.unit_id=p_unit_id;

  return jsonb_build_object(
    'unit_id',p_unit_id,
    'unit_carry_forward',v_balance,
    'allocations_reversed',v_reversed,
    'allocations_created',v_created
  );
end;
$$;

create or replace function public.crm_sync_schedule_carry(
  p_schedule_id bigint,
  p_event_date date default current_date,
  p_payment_transaction_id bigint default null,
  p_reason text default 'Payment variance'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_schedule public.payment_schedule%rowtype;
  v_credit numeric := 0;
  v_current_position numeric := 0;
  v_target_position numeric := 0;
  v_delta numeric := 0;
  v_event_id bigint;
  v_unit_balance numeric := 0;
  v_applied_to_schedule numeric := 0;
  v_rebalance jsonb;
begin
  select * into v_schedule from public.payment_schedule where id=p_schedule_id for update;
  if not found then raise exception 'Installment schedule not found.'; end if;

  select coalesce(sum(cn.amount),0) into v_credit
  from public.credit_notes cn where cn.payment_schedule_id=v_schedule.id;

  select coalesce(sum(e.amount),0) into v_current_position
  from public.carry_forward_events e where e.payment_schedule_id=v_schedule.id;

  if v_schedule.due_amount is null or v_schedule.due_amount<=0 then
    v_target_position:=0;
  elsif coalesce(v_schedule.paid_amount,0)>0 or v_credit>0 then
    v_target_position:=coalesce(v_schedule.paid_amount,0)+v_credit-v_schedule.due_amount;
  else
    v_target_position:=0;
  end if;

  v_target_position:=round(v_target_position,2);
  v_current_position:=round(v_current_position,2);
  v_delta:=round(v_target_position-v_current_position,2);

  if abs(v_delta)>=0.01 then
    insert into public.carry_forward_events(
      customer_id,unit_id,payment_schedule_id,payment_transaction_id,event_date,amount,reason,created_by
    ) values (
      v_schedule.customer_id,v_schedule.unit_id,v_schedule.id,p_payment_transaction_id,
      coalesce(p_event_date,current_date),v_delta,coalesce(nullif(btrim(p_reason),''),'Payment variance'),auth.uid()
    ) returning id into v_event_id;
  end if;

  v_rebalance:=public.crm_rebalance_unit_carry(
    v_schedule.unit_id,coalesce(p_event_date,current_date),
    coalesce(nullif(btrim(p_reason),''),'Carry-forward recalculation')
  );

  select round(coalesce(sum(e.amount),0),2) into v_unit_balance
  from public.carry_forward_events e where e.unit_id=v_schedule.unit_id;

  select round(coalesce(sum(a.amount),0),2) into v_applied_to_schedule
  from public.carry_forward_allocations a
  join public.carry_forward_events ne on ne.id=a.negative_event_id
  where ne.payment_schedule_id=v_schedule.id and a.reversed_at is null;

  return jsonb_build_object(
    'schedule_id',v_schedule.id,
    'event_id',v_event_id,
    'event_delta',v_delta,
    'schedule_position',v_target_position,
    'carry_applied',v_applied_to_schedule,
    'unit_carry_forward',v_unit_balance,
    'rebalanced',v_rebalance
  );
end;
$$;

create or replace function public.crm_set_payment_schedule_status_with_credits()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credit numeric := 0;
  v_carry_applied numeric := 0;
  v_settled numeric := 0;
begin
  if new.id is not null then
    select coalesce(sum(cn.amount),0) into v_credit
    from public.credit_notes cn where cn.payment_schedule_id=new.id;

    select coalesce(sum(a.amount),0) into v_carry_applied
    from public.carry_forward_allocations a
    join public.carry_forward_events ne on ne.id=a.negative_event_id
    where ne.payment_schedule_id=new.id and a.reversed_at is null;
  end if;

  v_settled := coalesce(new.paid_amount,0)+v_credit+v_carry_applied;
  if new.due_amount is null then
    new.status := coalesce(new.status,'Outstanding');
  elsif coalesce(new.due_amount,0)>0 and v_settled>=new.due_amount-0.01 then
    new.status := 'Paid';
  elsif v_settled>0 then
    new.status := 'Partial';
  else
    new.status := 'Outstanding';
  end if;
  return new;
end;
$$;

create or replace function public.crm_record_payment_with_credit_note(
  p_schedule_id bigint,
  p_cash_amount numeric default 0,
  p_payment_date date default null,
  p_payment_reference text default null,
  p_remarks text default null,
  p_credit_amount numeric default 0,
  p_credit_issue_date date default null,
  p_credit_reason text default null,
  p_credit_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_schedule public.payment_schedule%rowtype;
  v_cash numeric := coalesce(p_cash_amount,0);
  v_credit numeric := coalesce(p_credit_amount,0);
  v_new_cash numeric;
  v_total_credit numeric;
  v_tx_id bigint;
  v_credit_id bigint;
  v_sync jsonb;
  v_status text;
  v_event_date date;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role='crm_officer'::public.user_role
  ) then raise exception 'Only CRM officers can record payments or credit notes.'; end if;

  if v_cash<0 or v_credit<0 then raise exception 'Cash and credit note amounts cannot be negative.'; end if;
  if v_cash<=0 and v_credit<=0 then raise exception 'Enter a cash payment, a credit note, or both.'; end if;
  if v_cash>0 and p_payment_date is null then raise exception 'Payment date is required when cash is recorded.'; end if;
  if v_credit>0 and p_credit_issue_date is null then raise exception 'Credit note issue date is required.'; end if;
  if v_credit>0 and length(btrim(coalesce(p_credit_reason,'')))=0 then raise exception 'Credit note reason is required.'; end if;

  select * into v_schedule from public.payment_schedule where id=p_schedule_id for update;
  if not found then raise exception 'Installment schedule not found.'; end if;

  if v_cash>0 then
    insert into public.payment_transactions(
      customer_id,unit_id,payment_schedule_id,payment_date,amount,payment_type,payment_reference,remarks
    ) values (
      v_schedule.customer_id,v_schedule.unit_id,v_schedule.id,p_payment_date,v_cash,v_schedule.stage_name,
      nullif(btrim(p_payment_reference),''),nullif(btrim(p_remarks),'')
    ) returning id into v_tx_id;
  end if;

  if v_credit>0 then
    insert into public.credit_notes(
      customer_id,unit_id,payment_schedule_id,issue_date,amount,reason,reference_number,created_by
    ) values (
      v_schedule.customer_id,v_schedule.unit_id,v_schedule.id,p_credit_issue_date,v_credit,
      btrim(p_credit_reason),nullif(btrim(p_credit_reference),''),auth.uid()
    ) returning id into v_credit_id;
  end if;

  v_new_cash:=coalesce(v_schedule.paid_amount,0)+v_cash;
  update public.payment_schedule
  set paid_amount=v_new_cash,
      paid_date=case when v_cash>0 then p_payment_date else paid_date end,
      updated_at=now()
  where id=v_schedule.id;

  v_event_date:=coalesce(case when v_cash>0 then p_payment_date else null end,p_credit_issue_date,current_date);
  v_sync:=public.crm_sync_schedule_carry(
    v_schedule.id,v_event_date,v_tx_id,
    case when v_cash>0 and v_credit>0 then 'Payment and credit note variance'
         when v_cash>0 then 'Payment variance'
         else 'Credit note settlement variance' end
  );

  select coalesce(sum(amount),0) into v_total_credit
  from public.credit_notes where payment_schedule_id=v_schedule.id;
  select status into v_status from public.payment_schedule where id=v_schedule.id;

  return jsonb_build_object(
    'schedule_id',v_schedule.id,'transaction_id',v_tx_id,'credit_note_id',v_credit_id,
    'cash_paid',v_new_cash,'credit_notes',v_total_credit,'status',v_status,
    'carry_forward',v_sync->'unit_carry_forward','carry_event_delta',v_sync->'event_delta','carry_applied',v_sync->'carry_applied'
  );
end;
$$;

create or replace function public.crm_edit_payment_transaction(
  p_transaction_id bigint,p_payment_date date,p_amount numeric,p_payment_type text,p_payment_reference text,p_remarks text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_tx public.payment_transactions%rowtype;
  v_old_sched public.payment_schedule%rowtype;
  v_new_sched public.payment_schedule%rowtype;
  v_old_schedule_id bigint;
  v_new_schedule_id bigint;
  v_same_schedule boolean:=false;
  v_old_new_paid numeric:=0;
  v_new_new_paid numeric:=0;
  v_latest_date date;
  v_payment_type text:=btrim(coalesce(p_payment_type,''));
begin
  if auth.uid() is null or not exists (
    select 1 from public.profiles where profiles.id=auth.uid() and profiles.role='crm_officer'::public.user_role
  ) then raise exception 'Not authorized to edit transactions'; end if;
  if p_payment_date is null then raise exception 'Payment date is required'; end if;
  if p_amount is null or p_amount<=0 then raise exception 'Payment amount must be greater than zero'; end if;
  if v_payment_type='' then raise exception 'Installment is required'; end if;

  select * into v_tx from public.payment_transactions where id=p_transaction_id for update;
  if not found then raise exception 'Transaction not found'; end if;

  v_old_schedule_id:=v_tx.payment_schedule_id;
  if v_old_schedule_id is null then
    select id into v_old_schedule_id from public.payment_schedule
    where customer_id is not distinct from v_tx.customer_id
      and unit_id is not distinct from v_tx.unit_id
      and lower(btrim(stage_name))=lower(btrim(coalesce(v_tx.payment_type,'')))
    order by id limit 1;
  end if;
  if v_old_schedule_id is null then raise exception 'The original installment could not be matched safely. Review the installment ledger before editing this transaction.'; end if;

  select id into v_new_schedule_id from public.payment_schedule
  where customer_id is not distinct from v_tx.customer_id
    and unit_id is not distinct from v_tx.unit_id
    and lower(btrim(stage_name))=lower(v_payment_type)
  order by id limit 1;
  if v_new_schedule_id is null then raise exception 'The selected installment is not linked to this customer and unit'; end if;

  perform 1 from public.payment_schedule where id in (v_old_schedule_id,v_new_schedule_id) order by id for update;
  select * into v_old_sched from public.payment_schedule where id=v_old_schedule_id;
  select * into v_new_sched from public.payment_schedule where id=v_new_schedule_id;
  v_same_schedule:=v_old_schedule_id=v_new_schedule_id;

  insert into public.payment_transaction_edit_log(
    transaction_id,customer_id,unit_id,old_payment_date,old_amount,old_payment_type,old_payment_reference,old_remarks,
    new_payment_date,new_amount,new_payment_type,new_payment_reference,new_remarks,edited_by
  ) values (
    v_tx.id,v_tx.customer_id,v_tx.unit_id,v_tx.payment_date,v_tx.amount,v_tx.payment_type,v_tx.payment_reference,v_tx.remarks,
    p_payment_date,p_amount,v_payment_type,nullif(btrim(coalesce(p_payment_reference,'')),''),nullif(btrim(coalesce(p_remarks,'')),''),auth.uid()
  );

  update public.payment_transactions
  set payment_schedule_id=v_new_schedule_id,payment_date=p_payment_date,amount=p_amount,payment_type=v_payment_type,
      payment_reference=nullif(btrim(coalesce(p_payment_reference,'')),''),remarks=nullif(btrim(coalesce(p_remarks,'')),'')
  where id=v_tx.id;

  if v_same_schedule then
    v_new_new_paid:=greatest(0,coalesce(v_old_sched.paid_amount,0)-coalesce(v_tx.amount,0)+p_amount);
    select max(payment_date) into v_latest_date from public.payment_transactions where payment_schedule_id=v_old_schedule_id;
    update public.payment_schedule set paid_amount=v_new_new_paid,
      paid_date=case when v_new_new_paid<=0 then null else coalesce(v_latest_date,p_payment_date) end,updated_at=now()
    where id=v_old_schedule_id;
    perform public.crm_sync_schedule_carry(v_old_schedule_id,p_payment_date,v_tx.id,'Payment transaction edited');
    v_old_new_paid:=v_new_new_paid;
  else
    v_old_new_paid:=greatest(0,coalesce(v_old_sched.paid_amount,0)-coalesce(v_tx.amount,0));
    select max(payment_date) into v_latest_date from public.payment_transactions where payment_schedule_id=v_old_schedule_id;
    update public.payment_schedule set paid_amount=v_old_new_paid,
      paid_date=case when v_old_new_paid<=0 then null else coalesce(v_latest_date,v_old_sched.paid_date) end,updated_at=now()
    where id=v_old_schedule_id;
    perform public.crm_sync_schedule_carry(v_old_schedule_id,p_payment_date,v_tx.id,'Payment moved from installment');

    v_new_new_paid:=coalesce(v_new_sched.paid_amount,0)+p_amount;
    select max(payment_date) into v_latest_date from public.payment_transactions where payment_schedule_id=v_new_schedule_id;
    update public.payment_schedule set paid_amount=v_new_new_paid,paid_date=coalesce(v_latest_date,p_payment_date),updated_at=now()
    where id=v_new_schedule_id;
    perform public.crm_sync_schedule_carry(v_new_schedule_id,p_payment_date,v_tx.id,'Payment moved to installment');
  end if;

  return jsonb_build_object('transaction_id',v_tx.id,'old_schedule_id',v_old_schedule_id,'new_schedule_id',v_new_schedule_id,
    'same_schedule',v_same_schedule,'old_schedule_paid_amount',v_old_new_paid,'new_schedule_paid_amount',v_new_new_paid);
end;
$$;

create or replace function public.crm_delete_payment_transaction(p_transaction_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_tx public.payment_transactions%rowtype;
  v_sched public.payment_schedule%rowtype;
  v_schedule_id bigint;
  v_new_paid numeric:=0;
  v_latest_date date;
begin
  if auth.uid() is null or not exists (
    select 1 from public.profiles where profiles.id=auth.uid() and profiles.role='crm_officer'::public.user_role
  ) then raise exception 'Not authorized to delete transactions'; end if;

  select * into v_tx from public.payment_transactions where id=p_transaction_id for update;
  if not found then raise exception 'Transaction not found'; end if;

  v_schedule_id:=v_tx.payment_schedule_id;
  if v_schedule_id is null then
    select id into v_schedule_id from public.payment_schedule
    where customer_id is not distinct from v_tx.customer_id
      and unit_id is not distinct from v_tx.unit_id
      and lower(btrim(stage_name))=lower(btrim(coalesce(v_tx.payment_type,'')))
    order by id limit 1;
  end if;
  if v_schedule_id is not null then select * into v_sched from public.payment_schedule where id=v_schedule_id for update; end if;

  insert into public.payment_transaction_deletion_log(
    transaction_id,customer_id,unit_id,payment_date,amount,payment_type,payment_reference,remarks,deleted_by
  ) values (
    v_tx.id,v_tx.customer_id,v_tx.unit_id,v_tx.payment_date,v_tx.amount,v_tx.payment_type,v_tx.payment_reference,v_tx.remarks,auth.uid()
  );

  delete from public.payment_transactions where id=p_transaction_id;

  if v_schedule_id is not null and v_sched.id is not null then
    v_new_paid:=greatest(0,coalesce(v_sched.paid_amount,0)-coalesce(v_tx.amount,0));
    select max(payment_date) into v_latest_date from public.payment_transactions where payment_schedule_id=v_schedule_id;
    update public.payment_schedule set paid_amount=v_new_paid,
      paid_date=case when v_new_paid>0 then coalesce(v_latest_date,v_sched.paid_date) else null end,updated_at=now()
    where id=v_schedule_id;
    perform public.crm_sync_schedule_carry(v_schedule_id,current_date,null,'Payment transaction deleted: '||v_tx.id::text);
  end if;

  return jsonb_build_object('deleted_transaction_id',v_tx.id,'schedule_updated',v_schedule_id is not null,
    'new_paid_amount',case when v_schedule_id is not null then v_new_paid else null end);
end;
$$;

revoke all on function public.crm_rebalance_unit_carry(bigint,date,text) from public,anon,authenticated;
revoke all on function public.crm_sync_schedule_carry(bigint,date,bigint,text) from public,anon,authenticated;
revoke all on function public.crm_record_payment_with_credit_note(bigint,numeric,date,text,text,numeric,date,text,text) from public,anon;
revoke all on function public.crm_edit_payment_transaction(bigint,date,numeric,text,text,text) from public,anon;
revoke all on function public.crm_delete_payment_transaction(bigint) from public,anon;

grant execute on function public.crm_record_payment_with_credit_note(bigint,numeric,date,text,text,numeric,date,text,text) to authenticated;
grant execute on function public.crm_edit_payment_transaction(bigint,date,numeric,text,text,text) to authenticated;
grant execute on function public.crm_delete_payment_transaction(bigint) to authenticated;

comment on table public.carry_forward_events is 'Append-only signed installment variance events. Positive is customer credit; negative is a shortage.';
comment on table public.carry_forward_allocations is 'FIFO carry-forward offsets. Reversals preserve allocation audit history.';
comment on column public.payment_transactions.payment_schedule_id is 'Stable installment link for actual cash transactions.';
