create table if not exists public.payment_extensions (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id),
  unit_id bigint not null references public.units(id),
  payment_schedule_id bigint not null references public.payment_schedule(id),
  original_due_date date not null,
  extended_due_date date not null,
  approved_on date not null,
  approved_by text not null check (char_length(btrim(approved_by)) between 2 and 120),
  approval_reference text,
  reason text,
  penalty_basis text not null default 'not_specified',
  status text not null default 'active' check (status in ('active','completed','expired','cancelled')),
  created_by uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  expired_at timestamptz,
  cancelled_at timestamptz,
  cancellation_reason text,
  constraint payment_extensions_date_order check (extended_due_date > original_due_date)
);

alter table public.payment_extensions drop constraint if exists payment_extensions_penalty_basis_check;
alter table public.payment_extensions add constraint payment_extensions_penalty_basis_check
  check (penalty_basis in ('not_specified','original_due_date','extended_due_date','waived_until_extension','no_late_charges'));

create unique index if not exists payment_extensions_one_active_per_schedule_idx
  on public.payment_extensions(payment_schedule_id) where status='active';
create index if not exists payment_extensions_unit_status_due_idx
  on public.payment_extensions(unit_id,status,extended_due_date,id);
create index if not exists payment_extensions_schedule_history_idx
  on public.payment_extensions(payment_schedule_id,created_at desc,id desc);

alter table public.payment_extensions enable row level security;

drop policy if exists payment_extensions_select_staff on public.payment_extensions;
create policy payment_extensions_select_staff on public.payment_extensions
for select to authenticated using (
  exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('crm_officer'::public.user_role,'manager'::public.user_role))
);

drop policy if exists payment_extensions_insert_staff on public.payment_extensions;
create policy payment_extensions_insert_staff on public.payment_extensions
for insert to authenticated with check (
  created_by=(select auth.uid()) and exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('crm_officer'::public.user_role,'manager'::public.user_role))
);

drop policy if exists payment_extensions_update_staff on public.payment_extensions;
create policy payment_extensions_update_staff on public.payment_extensions
for update to authenticated using (
  exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('crm_officer'::public.user_role,'manager'::public.user_role))
) with check (
  exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('crm_officer'::public.user_role,'manager'::public.user_role))
);

revoke all on table public.payment_extensions from anon;
revoke all on table public.payment_extensions from authenticated;
grant select,insert,update on table public.payment_extensions to authenticated;
revoke all on sequence public.payment_extensions_id_seq from authenticated;
grant usage,select on sequence public.payment_extensions_id_seq to authenticated;

alter table public.scheduled_actions drop constraint if exists scheduled_actions_auto_kind_check;
alter table public.scheduled_actions add constraint scheduled_actions_auto_kind_check
  check (auto_kind is null or auto_kind in ('demand_letter','gentle_reminder','overdue_follow_up','extension_active','extension_residual_overdue'));