
-- Two-stage payment extension approvals: Management decision -> customer confirmation.
-- Separate revision history, no contractual due-date overwrite, old active extension stays effective.

alter table public.payment_extension_requests
  add column if not exists previous_request_id bigint references public.payment_extension_requests(id) on delete set null,
  add column if not exists revision_no integer not null default 1,
  add column if not exists decision_type text,
  add column if not exists customer_response text,
  add column if not exists customer_responded_at timestamptz,
  add column if not exists customer_response_note text;
alter table public.payment_extension_requests
  drop constraint if exists payment_extension_requests_status_check;
alter table public.payment_extension_requests
  add constraint payment_extension_requests_status_check
  check(status in ('pending','clarification','offered','approved','rejected','cancelled','superseded'));

alter table public.scheduled_actions
  drop constraint if exists scheduled_actions_workflow_kind_check;
alter table public.scheduled_actions
  add constraint scheduled_actions_workflow_kind_check
  check (workflow_kind is null or workflow_kind in (
    'accounts_confirmation','cheque_clearance','payment_receipt','promise_follow_up',
    'payment_query','payment_follow_up','payment_review','partial_payment_commitment',
    'payment_reported','extension_approval','extension_customer_confirmation',
    'extension_clarification','modification_request'
  ));

create table if not exists public.payment_extension_request_events (
 id bigint generated by default as identity primary key,
 request_id bigint not null references public.payment_extension_requests(id) on delete cascade,
 event_type text not null,
 notes text,
 actor_id uuid references public.profiles(id),
 details jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists payment_extension_request_events_request_idx
on public.payment_extension_request_events(request_id,created_at,id);
alter table public.payment_extension_request_events enable row level security;
drop policy if exists payment_extension_event_select on public.payment_extension_request_events;
create policy payment_extension_event_select on public.payment_extension_request_events
  for select to authenticated using (
    exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text in ('crm_officer','manager'))
  );
grant select on public.payment_extension_request_events to authenticated;

create or replace function public.crm_create_payment_extension_request(
  p_unit_id bigint,
  p_schedule_id bigint,
  p_requested_until date,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_schedule public.payment_schedule%rowtype;
  v_task_id bigint;
  v_request_id bigint;
  v_owner uuid := auth.uid();
  v_now timestamptz := now();
  v_credit numeric := 0;
  v_outstanding numeric := 0;
  v_note text;
  v_previous_request_id bigint;
  v_revision_no integer := 1;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid()
      and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to create an extension request.';
  end if;

  if p_requested_until is null then
    raise exception 'Select the requested extension date.';
  end if;

  select * into v_schedule
  from public.payment_schedule
  where id=p_schedule_id
    and unit_id=p_unit_id
  for update;

  if not found then
    raise exception 'The selected installment was not found for this customer.';
  end if;

  if v_schedule.due_date is null then
    raise exception 'This installment has no contractual due date and cannot use the extension workflow.';
  end if;

  if p_requested_until <= v_schedule.due_date then
    raise exception 'Requested extension date must be later than the contractual due date.';
  end if;

  -- An existing effective extension remains in force until the new offer is accepted.

  if exists (
    select 1 from public.payment_extension_requests r
    where r.payment_schedule_id=p_schedule_id
      and r.status in ('pending','offered','clarification')
  ) then
    raise exception 'There is an open extension workflow for this installment. Complete its active task first.';
  end if;

  select coalesce(sum(c.amount),0)
    into v_credit
  from public.credit_notes c
  where c.payment_schedule_id=p_schedule_id;

  v_outstanding := greatest(
    0,
    coalesce(v_schedule.due_amount,0)
      - coalesce(v_schedule.paid_amount,0)
      - coalesce(v_credit,0)
  );

  if v_outstanding <= 0.01 then
    raise exception 'This installment is already settled.';
  end if;

  -- Reuse the current collection task for this exact installment when possible.
  select a.id into v_task_id
  from public.scheduled_actions a
  where a.unit_id=p_unit_id
    and a.status='pending'
    and (
      a.schedule_id=p_schedule_id
      or a.auto_key like '%|schedule:'||p_schedule_id::text||'%'
      or a.auto_key like '%|schedules:%'||p_schedule_id::text||'%'
    )
    and (
      a.auto_kind in ('demand_letter','gentle_reminder','overdue_follow_up','extension_residual_overdue','extension_uncovered_overdue')
      or a.workflow_kind in ('promise_follow_up','payment_query','payment_follow_up','payment_review','partial_payment_commitment','payment_reported')
      or (
        a.source='manual'
        and (
          a.schedule_id=p_schedule_id
          or lower(coalesce(a.action_label,'')) ~ '(payment|installment|demand|reminder|outstanding|overdue|collection|call customer|follow up|follow-up)'
        )
      )
    )
  order by
    case when a.source='manual' then 0 else 1 end,
    a.id desc
  limit 1
  for update;

  if v_task_id is null then
    insert into public.scheduled_actions(
      unit_id,action_label,due_date,priority,note,status,owner_id,
      source,auto_kind,auto_key,schedule_id,transaction_id,workflow_kind,
      commitment_part_id,created_at,updated_at
    ) values (
      p_unit_id,
      'Management Approval — Payment Extension',
      current_date,
      'High',
      null,
      'pending',
      v_owner,
      'manual',
      null,
      'manual_payment|unit:'||p_unit_id::text||'|schedule:'||p_schedule_id::text,
      p_schedule_id,
      null,
      'extension_approval',
      null,
      v_now,
      v_now
    )
    returning id into v_task_id;
  end if;

  select r.id, coalesce(r.revision_no,1)+1
    into v_previous_request_id, v_revision_no
  from public.payment_extension_requests r
  where r.payment_schedule_id=p_schedule_id
  order by r.id desc limit 1;

  insert into public.payment_extension_requests(
    customer_id,unit_id,payment_schedule_id,source_task_id,
    original_due_date,requested_until,reason,status,requested_by,
    requested_at,created_at,updated_at,previous_request_id,revision_no
  ) values (
    v_schedule.customer_id,p_unit_id,p_schedule_id,v_task_id,
    v_schedule.due_date,p_requested_until,
    nullif(btrim(coalesce(p_reason,'')),''),
    'pending',v_owner,v_now,v_now,v_now,v_previous_request_id,v_revision_no
  )
  returning id into v_request_id;

  v_note := 'Customer requested payment extension from ' ||
    to_char(v_schedule.due_date,'DD Mon YYYY') ||
    ' to ' || to_char(p_requested_until,'DD Mon YYYY') || '.';
  if nullif(btrim(coalesce(p_reason,'')),'') is not null then
    v_note := v_note || ' ' || btrim(p_reason);
  end if;

  update public.scheduled_actions
     set action_label='Management Approval — Payment Extension',
         due_date=current_date,
         priority='High',
         note=v_note,
         status='pending',
         owner_id=coalesce(owner_id,v_owner),
         source='manual',
         auto_kind=null,
         auto_key='manual_payment|unit:'||p_unit_id::text||'|schedule:'||p_schedule_id::text,
         schedule_id=p_schedule_id,
         transaction_id=null,
         workflow_kind='extension_approval',
         commitment_part_id=null,
         extension_request_id=v_request_id,
         completed_at=null,
         completion_note=null,
         cancelled_at=null,
         updated_at=v_now
   where id=v_task_id;

  -- One collection action for the installment while approval is pending.
  update public.scheduled_actions
     set status='cancelled',cancelled_at=v_now,updated_at=v_now
   where unit_id=p_unit_id
     and status='pending'
     and id<>v_task_id
     and (
       schedule_id=p_schedule_id
       or auto_key like '%|schedule:'||p_schedule_id::text||'%'
       or auto_key like '%|schedules:%'||p_schedule_id::text||'%'
     )
     and (
       auto_kind in ('demand_letter','gentle_reminder','overdue_follow_up','extension_residual_overdue','extension_uncovered_overdue')
       or workflow_kind in ('promise_follow_up','payment_query','payment_follow_up','payment_review','partial_payment_commitment','payment_reported')
     );

  -- A new extension request replaces an earlier split-payment promise for this installment.
  update public.partial_payment_plans
     set status='cancelled',updated_at=v_now
   where payment_schedule_id=p_schedule_id
     and status='active';

  insert into public.payment_extension_request_events(request_id,event_type,notes,actor_id,details)
  values (v_request_id,case when v_previous_request_id is null then 'requested' else 'rerequested' end,
    nullif(btrim(coalesce(p_reason,'')),''),v_owner,
    jsonb_build_object('requested_until',p_requested_until,'previous_request_id',v_previous_request_id,'revision_no',v_revision_no));

  return jsonb_build_object(
    'request_id',v_request_id,
    'task_id',v_task_id,
    'schedule_id',p_schedule_id,
    'requested_until',p_requested_until,
    'next_action','Management Approval — Payment Extension'
  );
end;
$function$;




create or replace function public.crm_resolve_payment_extension_request(
  p_task_id bigint,
  p_decision text,
  p_approved_until date default null,
  p_approved_by text default null,
  p_approval_reference text default null,
  p_penalty_basis text default 'not_specified',
  p_note text default null
)
returns jsonb language plpgsql security definer set search_path=public as $function$
declare
  t public.scheduled_actions%rowtype;
  r public.payment_extension_requests%rowtype;
  v_owner uuid := auth.uid();
  v_now timestamptz := now();
  v_decision text := lower(btrim(coalesce(p_decision,'')));
  v_label text;
begin
  if not exists(select 1 from public.profiles p where p.id=auth.uid()
    and p.role::text in ('crm_officer','manager')) then
    raise exception 'You are not authorized to record management decisions.';
  end if;
  if v_decision not in ('approved','approved_with_changes','rejected','clarification') then
    raise exception 'Select a valid management decision.';
  end if;
  select * into t from public.scheduled_actions where id=p_task_id for update;
  if not found or t.status<>'pending' or t.workflow_kind<>'extension_approval'
     or t.extension_request_id is null then
    raise exception 'Pending extension approval task not found.';
  end if;
  select * into r from public.payment_extension_requests
   where id=t.extension_request_id for update;
  if not found or r.status<>'pending' then raise exception 'Pending extension request not found.'; end if;

  if v_decision='clarification' then
    update public.payment_extension_requests set status='clarification',decision_type=v_decision,
     decision_note=nullif(btrim(coalesce(p_note,'')),''),updated_at=v_now where id=r.id;
    update public.scheduled_actions set
      action_label='Obtain Clarification — Payment Extension',due_date=current_date,
      workflow_kind='extension_clarification',priority='High',note=coalesce(nullif(btrim(p_note),''),'Clarification requested by Management.'),
      updated_at=v_now where id=t.id;
  elsif v_decision='rejected' then
    update public.payment_extension_requests set status='rejected',
     decision_type='rejected',decision_at=v_now,decision_by=v_owner,
     decision_note=nullif(btrim(coalesce(p_note,'')),''),updated_at=v_now where id=r.id;
    update public.scheduled_actions set
      action_label='Inform Customer — Extension Rejected',due_date=current_date,
      workflow_kind='extension_customer_confirmation',priority='High',
      note=coalesce(nullif(btrim(p_note),''),'Management declined the requested payment extension.'),
      updated_at=v_now where id=t.id;
  else
    if p_approved_until is null or p_approved_until<=r.original_due_date then
      raise exception 'Select an approved date later than the original contractual due date.';
    end if;
    if char_length(btrim(coalesce(p_approved_by,''))) not between 2 and 120 then
      raise exception 'Enter who approved this decision.';
    end if;
    if p_penalty_basis not in
      ('not_specified','original_due_date','extended_due_date','waived_until_extension','no_late_charges') then
      raise exception 'Choose a valid late-charge treatment.';
    end if;
    -- Correct the category if approved date differs, even if the UI selected plain approval.
    v_decision:=case when p_approved_until=r.requested_until
      then 'approved' else 'approved_with_changes' end;
    update public.payment_extension_requests set status='offered',
      decision_type=v_decision, decision_at=v_now,decision_by=v_owner,
      decision_note=nullif(btrim(coalesce(p_note,'')),''),approved_until=p_approved_until,
      approved_by=btrim(p_approved_by),
      approval_reference=nullif(btrim(coalesce(p_approval_reference,'')),''),penalty_basis=p_penalty_basis,
      updated_at=v_now where id=r.id;
    update public.scheduled_actions set
      action_label='Confirm with Customer — Payment Extension',due_date=current_date,
      workflow_kind='extension_customer_confirmation',priority='High',
      note='Customer requested '||to_char(r.requested_until,'DD Mon YYYY')||
           '; Management approved until '||to_char(p_approved_until,'DD Mon YYYY')||'. '||
           coalesce(nullif(btrim(p_note),''),''),
      updated_at=v_now where id=t.id;
  end if;
  insert into public.payment_extension_request_events(request_id,event_type,notes,actor_id,details)
  values(r.id,'management_'||v_decision,nullif(btrim(coalesce(p_note,'')),''),v_owner,
    jsonb_build_object('requested_until',r.requested_until,'approved_until',p_approved_until,
      'approved_by',p_approved_by,'approval_reference',p_approval_reference,'penalty_basis',p_penalty_basis));
  return jsonb_build_object('request_id',r.id,'task_id',t.id,'decision',v_decision,
     'next_action',case when v_decision='clarification' then 'Obtain Clarification'
                       when v_decision='rejected' then 'Inform Customer'
                       else 'Confirm with Customer' end);
end;$function$;

create or replace function public.crm_submit_extension_clarification(
  p_task_id bigint,p_note text
)
returns jsonb language plpgsql security definer set search_path=public as $function$
declare
 t public.scheduled_actions%rowtype;
 r public.payment_extension_requests%rowtype;
 v_owner uuid:=auth.uid();
begin
 if not exists(select 1 from public.profiles p where p.id=v_owner and p.role::text in ('crm_officer','manager'))
   then raise exception 'Not authorized.';end if;
 if nullif(btrim(coalesce(p_note,'')),'') is null then raise exception 'Enter the clarification obtained.';end if;
 select * into t from public.scheduled_actions where id=p_task_id for update;
 if not found or t.status<>'pending' or t.workflow_kind<>'extension_clarification' then
   raise exception 'Active clarification task not found.';end if;
 select * into r from public.payment_extension_requests where id=t.extension_request_id for update;
 if not found or r.status<>'clarification' then raise exception 'Request no longer needs clarification.';end if;
 update public.payment_extension_requests set status='pending', updated_at=now() where id=r.id;
 update public.scheduled_actions set action_label='Management Re-approval — Extension',
   workflow_kind='extension_approval',due_date=current_date,priority='High',
   note='Clarification received: '||btrim(p_note),updated_at=now() where id=t.id;
 insert into public.payment_extension_request_events(request_id,event_type,notes,actor_id)
 values(r.id,'clarification_received',btrim(p_note),v_owner);
 return jsonb_build_object('request_id',r.id,'task_id',t.id,'next_action','Management Re-approval');
end;$function$;

create or replace function public.crm_record_extension_customer_response(
  p_task_id bigint,
  p_outcome text,
  p_note text default null,
  p_requested_until date default null,
  p_next_date date default null
)
returns jsonb language plpgsql security definer set search_path=public as $function$
declare
 t public.scheduled_actions%rowtype;
 r public.payment_extension_requests%rowtype;
 s public.payment_schedule%rowtype;
 v_owner uuid:=auth.uid();
 v_now timestamptz:=now();
 v_outcome text:=lower(btrim(coalesce(p_outcome,'')));
 v_old_active_id bigint;
 v_new_request_id bigint;
 v_credit numeric:=0;
 v_balance numeric:=0;
 v_next text;
begin
 if not exists(select 1 from public.profiles p where p.id=v_owner and p.role::text in ('crm_officer','manager'))
   then raise exception 'Not authorized to record customer response.';end if;
 select * into t from public.scheduled_actions where id=p_task_id for update;
 if not found or t.status<>'pending' or t.workflow_kind<>'extension_customer_confirmation' then
  raise exception 'Customer confirmation task is no longer pending.';end if;
 select * into r from public.payment_extension_requests where id=t.extension_request_id for update;
 if not found or r.status not in ('offered','rejected') then
  raise exception 'No current management decision to confirm.';end if;
 select * into s from public.payment_schedule where id=r.payment_schedule_id for update;
 if not found then raise exception 'Linked installment not found.';end if;
 select id into v_old_active_id from public.payment_extensions
  where payment_schedule_id=s.id and status='active' order by id desc limit 1 for update;
 if v_outcome='rerequest' then
    if p_requested_until is null or p_requested_until<=s.due_date then
      raise exception 'Enter a requested date later than the original contractual due date.';end if;
    if nullif(btrim(coalesce(p_note,'')),'') is null then raise exception 'Enter reason for the customer re-request.';end if;
    -- Preserve the offered/rejected decision in the history. An accepted old extension is not touched.
    if r.status='offered' then
      update public.payment_extension_requests set status='superseded',
        customer_response='rerequest',customer_response_note=btrim(p_note),
        customer_responded_at=v_now,updated_at=v_now where id=r.id;
    else
      update public.payment_extension_requests set
        customer_response='rerequest',customer_response_note=btrim(p_note),
        customer_responded_at=v_now,updated_at=v_now where id=r.id;
    end if;
    insert into public.payment_extension_requests(
      customer_id,unit_id,payment_schedule_id,source_task_id,original_due_date,
      requested_until,reason,status,requested_by,previous_request_id,revision_no
    ) values(s.customer_id,r.unit_id,s.id,t.id,s.due_date,p_requested_until,
       btrim(p_note),'pending',v_owner,r.id,r.revision_no+1)
    returning id into v_new_request_id;
    update public.scheduled_actions set
       action_label='Management Re-approval — Payment Extension',workflow_kind='extension_approval',
       extension_request_id=v_new_request_id,due_date=current_date,priority='High',
       note='Customer re-requested '||to_char(p_requested_until,'DD Mon YYYY')||
       '. Previous decision: '||coalesce(to_char(r.approved_until,'DD Mon YYYY'),'rejected')||'. '||btrim(p_note),
       updated_at=v_now where id=t.id;
    insert into public.payment_extension_request_events(request_id,event_type,notes,actor_id,details)
    values(v_new_request_id,'rerequested',btrim(p_note),v_owner,
       jsonb_build_object('previous_request_id',r.id,'requested_until',p_requested_until,
       'previous_approved_until',r.approved_until));
    v_next:='Management Re-approval';
 elsif v_outcome='no_response' then
    if p_next_date is null then raise exception 'Select the next customer follow-up date.';end if;
    update public.scheduled_actions set
      action_label='Follow up — Extension Customer Confirmation',
      due_date=p_next_date,priority='High',
      note=coalesce(nullif(btrim(coalesce(p_note,'')),''),'Customer has not responded to extension decision.'),
      updated_at=v_now where id=t.id;
    insert into public.payment_extension_request_events(request_id,event_type,notes,actor_id,details)
    values(r.id,'customer_no_response',p_note,v_owner,jsonb_build_object('next_follow_up',p_next_date));
    v_next:='Follow up with Customer';
 elsif v_outcome='accepted' then
    if r.status<>'offered' or r.approved_until is null then
       raise exception 'There is no approved offer for the customer to accept.';end if;
    select coalesce(sum(amount),0) into v_credit from public.credit_notes where payment_schedule_id=s.id;
    v_balance:=greatest(0,coalesce(s.due_amount,0)-coalesce(s.paid_amount,0)-v_credit);
    if v_balance>0.01 then
       if v_old_active_id is not null then
         update public.payment_extensions set status='cancelled',cancelled_at=v_now,
          cancellation_reason='Superseded by accepted extension request #'||r.id,
          updated_at=v_now where id=v_old_active_id;
       end if;
       insert into public.payment_extensions(
         customer_id,unit_id,payment_schedule_id,original_due_date,extended_due_date,
         approved_on,approved_by,approval_reference,reason,penalty_basis,status,
         created_by,created_at,updated_at
       ) values(s.customer_id,r.unit_id,s.id,s.due_date,r.approved_until,
         coalesce(r.decision_at::date,current_date),r.approved_by,r.approval_reference,
         coalesce(nullif(btrim(coalesce(p_note,'')),''),r.reason),
         coalesce(r.penalty_basis,'not_specified'),'active',v_owner,v_now,v_now);
    end if;
    update public.payment_extension_requests set
      status='approved',customer_response='accepted',
      customer_responded_at=v_now,customer_response_note=nullif(btrim(coalesce(p_note,'')),''),
      updated_at=v_now where id=r.id;
    update public.scheduled_actions set
      status='completed',completed_at=v_now,
      completion_note=coalesce(nullif(btrim(coalesce(p_note,'')),''),'Customer accepted approved extension.'),
      updated_at=v_now where id=t.id;
    insert into public.payment_extension_request_events(request_id,event_type,notes,actor_id,details)
    values(r.id,'customer_accepted',p_note,v_owner,
      jsonb_build_object('approved_until',r.approved_until,'previous_active_extension_id',v_old_active_id));
    v_next:=case when v_balance<=0.01 then 'Installment Settled' else 'Track Extension Payment' end;
 elsif v_outcome in ('declined','withdrawn','acknowledged') then
    if r.status='offered' then
      update public.payment_extension_requests set status='cancelled',
        customer_response=v_outcome,customer_responded_at=v_now,customer_response_note=p_note,
        updated_at=v_now where id=r.id;
    else
      update public.payment_extension_requests set customer_response=v_outcome,
        customer_responded_at=v_now,customer_response_note=p_note,updated_at=v_now where id=r.id;
    end if;
    if v_old_active_id is not null then
      update public.scheduled_actions set
         status='completed',completed_at=v_now,
         completion_note='Previous approved extension remains effective. '||coalesce(p_note,''),
         updated_at=v_now where id=t.id;
      v_next:='Previous Extension Remains Active';
    else
      update public.scheduled_actions set
         action_label='Payment Follow-up with Customer',workflow_kind='payment_follow_up',
         due_date=current_date,priority='High',
         note='Extension not accepted or rejected. '||coalesce(p_note,''),
         updated_at=v_now where id=t.id;
      v_next:='Payment Follow-up with Customer';
    end if;
    insert into public.payment_extension_request_events(request_id,event_type,notes,actor_id)
    values(r.id,'customer_'||v_outcome,p_note,v_owner);
 else
    raise exception 'Select a valid customer response.';
 end if;
 return jsonb_build_object('request_id',coalesce(v_new_request_id,r.id),
   'task_id',t.id,'outcome',v_outcome,'next_action',v_next);
end;$function$;

grant execute on function public.crm_create_payment_extension_request(bigint,bigint,date,text) to authenticated;
grant execute on function public.crm_resolve_payment_extension_request(bigint,text,date,text,text,text,text) to authenticated;
grant execute on function public.crm_submit_extension_clarification(bigint,text) to authenticated;
grant execute on function public.crm_record_extension_customer_response(bigint,text,text,date,date) to authenticated;
