create table if not exists public.scheduled_actions (
  id bigint generated by default as identity primary key,
  unit_id bigint not null references public.units(id),
  action_label text not null check (char_length(btrim(action_label)) between 2 and 120),
  due_date date not null,
  priority text not null default 'Medium' check (priority in ('High','Medium','Low')),
  note text,
  status text not null default 'pending' check (status in ('pending','completed','cancelled')),
  owner_id uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  completion_note text,
  cancelled_at timestamptz
);

create index if not exists scheduled_actions_owner_status_due_idx
  on public.scheduled_actions(owner_id,status,due_date,id);
create index if not exists scheduled_actions_unit_owner_status_idx
  on public.scheduled_actions(unit_id,owner_id,status,due_date);

alter table public.scheduled_actions enable row level security;

drop policy if exists scheduled_actions_select_own on public.scheduled_actions;
create policy scheduled_actions_select_own
on public.scheduled_actions
for select
to authenticated
using ((select auth.uid()) = owner_id);

drop policy if exists scheduled_actions_insert_own on public.scheduled_actions;
create policy scheduled_actions_insert_own
on public.scheduled_actions
for insert
to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists scheduled_actions_update_own on public.scheduled_actions;
create policy scheduled_actions_update_own
on public.scheduled_actions
for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

revoke all on table public.scheduled_actions from anon;
grant select, insert, update on table public.scheduled_actions to authenticated;
grant usage, select on sequence public.scheduled_actions_id_seq to authenticated;
