-- Customer-requested payment extension approval workflow.

create table if not exists public.payment_extension_requests (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete set null,
  unit_id bigint not null references public.units(id) on delete cascade,
  payment_schedule_id bigint not null references public.payment_schedule(id) on delete cascade,
  source_task_id bigint references public.scheduled_actions(id) on delete set null,
  original_due_date date not null,
  requested_until date not null,
  reason text,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected','cancelled')),
  requested_by uuid references public.profiles(id),
  requested_at timestamptz not null default now(),
  decision_at timestamptz,
  decision_by uuid references public.profiles(id),
  decision_note text,
  approved_until date,
  approved_by text,
  approval_reference text,
  penalty_basis text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.scheduled_actions
  add column if not exists extension_request_id bigint
  references public.payment_extension_requests(id) on delete set null;

create index if not exists payment_extension_requests_schedule_idx
  on public.payment_extension_requests(payment_schedule_id,status);

create index if not exists scheduled_actions_extension_request_idx
  on public.scheduled_actions(extension_request_id);

alter table public.scheduled_actions
  drop constraint if exists scheduled_actions_workflow_kind_check;

alter table public.scheduled_actions
  add constraint scheduled_actions_workflow_kind_check
  check (
    workflow_kind is null or workflow_kind in (
      'accounts_confirmation',
      'cheque_clearance',
      'payment_receipt',
      'promise_follow_up',
      'payment_query',
      'payment_follow_up',
      'payment_review',
      'partial_payment_commitment',
      'payment_reported',
      'extension_approval'
    )
  );

alter table public.payment_extension_requests enable row level security;

create or replace function public.crm_create_payment_extension_request(
  p_unit_id bigint,
  p_schedule_id bigint,
  p_requested_until date,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_schedule public.payment_schedule%rowtype;
  v_task_id bigint;
  v_request_id bigint;
  v_owner uuid := auth.uid();
  v_now timestamptz := now();
  v_credit numeric := 0;
  v_outstanding numeric := 0;
  v_note text;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid()
      and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to create an extension request.';
  end if;

  if p_requested_until is null then
    raise exception 'Select the requested extension date.';
  end if;

  select * into v_schedule
  from public.payment_schedule
  where id=p_schedule_id
    and unit_id=p_unit_id
  for update;

  if not found then
    raise exception 'The selected installment was not found for this customer.';
  end if;

  if v_schedule.due_date is null then
    raise exception 'This installment has no contractual due date and cannot use the extension workflow.';
  end if;

  if p_requested_until <= v_schedule.due_date then
    raise exception 'Requested extension date must be later than the contractual due date.';
  end if;

  if exists (
    select 1 from public.payment_extensions e
    where e.payment_schedule_id=p_schedule_id
      and e.status='active'
  ) then
    raise exception 'This installment already has an active payment extension.';
  end if;

  if exists (
    select 1 from public.payment_extension_requests r
    where r.payment_schedule_id=p_schedule_id
      and r.status='pending'
  ) then
    raise exception 'An extension request for this installment is already awaiting approval.';
  end if;

  select coalesce(sum(c.amount),0)
    into v_credit
  from public.credit_notes c
  where c.payment_schedule_id=p_schedule_id;

  v_outstanding := greatest(
    0,
    coalesce(v_schedule.due_amount,0)
      - coalesce(v_schedule.paid_amount,0)
      - coalesce(v_credit,0)
  );

  if v_outstanding <= 0.01 then
    raise exception 'This installment is already settled.';
  end if;

  -- Reuse the current collection task for this exact installment when possible.
  select a.id into v_task_id
  from public.scheduled_actions a
  where a.unit_id=p_unit_id
    and a.status='pending'
    and (
      a.schedule_id=p_schedule_id
      or a.auto_key like '%|schedule:'||p_schedule_id::text||'%'
      or a.auto_key like '%|schedules:%'||p_schedule_id::text||'%'
    )
    and (
      a.auto_kind in ('demand_letter','gentle_reminder','overdue_follow_up','extension_residual_overdue','extension_uncovered_overdue')
      or a.workflow_kind in ('promise_follow_up','payment_query','payment_follow_up','payment_review','partial_payment_commitment','payment_reported')
      or (
        a.source='manual'
        and lower(coalesce(a.action_label,'')) ~ '(payment|installment|demand|reminder|outstanding|overdue|collection)'
      )
    )
  order by
    case when a.source='manual' then 0 else 1 end,
    a.id desc
  limit 1
  for update;

  if v_task_id is null then
    insert into public.scheduled_actions(
      unit_id,action_label,due_date,priority,note,status,owner_id,
      source,auto_kind,auto_key,schedule_id,transaction_id,workflow_kind,
      commitment_part_id,created_at,updated_at
    ) values (
      p_unit_id,
      'Management Approval — Payment Extension',
      current_date,
      'High',
      null,
      'pending',
      v_owner,
      'manual',
      null,
      'manual_payment|unit:'||p_unit_id::text||'|schedule:'||p_schedule_id::text,
      p_schedule_id,
      null,
      'extension_approval',
      null,
      v_now,
      v_now
    )
    returning id into v_task_id;
  end if;

  insert into public.payment_extension_requests(
    customer_id,unit_id,payment_schedule_id,source_task_id,
    original_due_date,requested_until,reason,status,requested_by,
    requested_at,created_at,updated_at
  ) values (
    v_schedule.customer_id,p_unit_id,p_schedule_id,v_task_id,
    v_schedule.due_date,p_requested_until,
    nullif(btrim(coalesce(p_reason,'')),''),
    'pending',v_owner,v_now,v_now,v_now
  )
  returning id into v_request_id;

  v_note := 'Customer requested payment extension from ' ||
    to_char(v_schedule.due_date,'DD Mon YYYY') ||
    ' to ' || to_char(p_requested_until,'DD Mon YYYY') || '.';
  if nullif(btrim(coalesce(p_reason,'')),'') is not null then
    v_note := v_note || ' ' || btrim(p_reason);
  end if;

  update public.scheduled_actions
     set action_label='Management Approval — Payment Extension',
         due_date=current_date,
         priority='High',
         note=v_note,
         status='pending',
         owner_id=coalesce(owner_id,v_owner),
         source='manual',
         auto_kind=null,
         auto_key='manual_payment|unit:'||p_unit_id::text||'|schedule:'||p_schedule_id::text,
         schedule_id=p_schedule_id,
         transaction_id=null,
         workflow_kind='extension_approval',
         commitment_part_id=null,
         extension_request_id=v_request_id,
         completed_at=null,
         completion_note=null,
         cancelled_at=null,
         updated_at=v_now
   where id=v_task_id;

  -- One collection action for the installment while approval is pending.
  update public.scheduled_actions
     set status='cancelled',cancelled_at=v_now,updated_at=v_now
   where unit_id=p_unit_id
     and status='pending'
     and id<>v_task_id
     and (
       schedule_id=p_schedule_id
       or auto_key like '%|schedule:'||p_schedule_id::text||'%'
       or auto_key like '%|schedules:%'||p_schedule_id::text||'%'
     )
     and (
       auto_kind in ('demand_letter','gentle_reminder','overdue_follow_up','extension_residual_overdue','extension_uncovered_overdue')
       or workflow_kind in ('promise_follow_up','payment_query','payment_follow_up','payment_review','partial_payment_commitment','payment_reported')
     );

  -- A new extension request replaces an earlier split-payment promise for this installment.
  update public.partial_payment_plans
     set status='cancelled',updated_at=v_now
   where payment_schedule_id=p_schedule_id
     and status='active';

  return jsonb_build_object(
    'request_id',v_request_id,
    'task_id',v_task_id,
    'schedule_id',p_schedule_id,
    'requested_until',p_requested_until,
    'next_action','Management Approval — Payment Extension'
  );
end;
$function$;

create or replace function public.crm_resolve_payment_extension_request(
  p_task_id bigint,
  p_decision text,
  p_approved_until date default null,
  p_approved_by text default null,
  p_approval_reference text default null,
  p_penalty_basis text default 'not_specified',
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_task public.scheduled_actions%rowtype;
  v_request public.payment_extension_requests%rowtype;
  v_schedule public.payment_schedule%rowtype;
  v_owner uuid := auth.uid();
  v_now timestamptz := now();
  v_extension_id bigint;
  v_note text;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid()
      and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to resolve this extension request.';
  end if;

  if p_decision not in ('approved','rejected') then
    raise exception 'Select Approved or Rejected.';
  end if;

  select * into v_task
  from public.scheduled_actions
  where id=p_task_id
  for update;

  if not found or v_task.status<>'pending' or v_task.workflow_kind<>'extension_approval' then
    raise exception 'Pending extension approval task not found.';
  end if;

  if v_task.extension_request_id is null then
    raise exception 'This approval task is not linked to an extension request.';
  end if;

  select * into v_request
  from public.payment_extension_requests
  where id=v_task.extension_request_id
  for update;

  if not found or v_request.status<>'pending' then
    raise exception 'Pending extension request not found.';
  end if;

  select * into v_schedule
  from public.payment_schedule
  where id=v_request.payment_schedule_id
  for update;

  if not found then
    raise exception 'Linked installment not found.';
  end if;

  if p_decision='rejected' then
    update public.payment_extension_requests
       set status='rejected',
           decision_at=v_now,
           decision_by=v_owner,
           decision_note=nullif(btrim(coalesce(p_note,'')),''),
           updated_at=v_now
     where id=v_request.id;

    v_note := 'Payment extension request rejected. Original contractual due date remains ' ||
      to_char(v_request.original_due_date,'DD Mon YYYY') || '.';
    if nullif(btrim(coalesce(p_note,'')),'') is not null then
      v_note := v_note || ' ' || btrim(p_note);
    end if;

    update public.scheduled_actions
       set action_label='Payment Follow-up with Customer',
           due_date=current_date,
           priority='High',
           note=v_note,
           source='manual',
           auto_kind=null,
           auto_key='manual_payment|unit:'||v_request.unit_id::text||'|schedule:'||v_request.payment_schedule_id::text,
           schedule_id=v_request.payment_schedule_id,
           transaction_id=null,
           workflow_kind='payment_follow_up',
           commitment_part_id=null,
           extension_request_id=v_request.id,
           status='pending',
           completed_at=null,
           completion_note=null,
           cancelled_at=null,
           updated_at=v_now
     where id=v_task.id;

    return jsonb_build_object(
      'request_id',v_request.id,
      'task_id',v_task.id,
      'decision','rejected',
      'next_action','Payment Follow-up with Customer'
    );
  end if;

  if p_approved_until is null then
    raise exception 'Select the approved extension date.';
  end if;
  if p_approved_until <= v_request.original_due_date then
    raise exception 'Approved extension date must be later than the contractual due date.';
  end if;
  if char_length(btrim(coalesce(p_approved_by,''))) < 2 then
    raise exception 'Enter who approved the extension.';
  end if;
  if p_penalty_basis not in ('not_specified','original_due_date','extended_due_date','waived_until_extension','no_late_charges') then
    raise exception 'Select a valid late-charge treatment.';
  end if;

  if exists (
    select 1 from public.payment_extensions e
    where e.payment_schedule_id=v_request.payment_schedule_id
      and e.status='active'
  ) then
    raise exception 'This installment already has an active payment extension.';
  end if;

  insert into public.payment_extensions(
    customer_id,unit_id,payment_schedule_id,
    original_due_date,extended_due_date,approved_on,approved_by,
    approval_reference,reason,penalty_basis,status,created_by,created_at,updated_at
  ) values (
    v_schedule.customer_id,v_request.unit_id,v_request.payment_schedule_id,
    v_request.original_due_date,p_approved_until,current_date,btrim(p_approved_by),
    nullif(btrim(coalesce(p_approval_reference,'')),''),
    coalesce(nullif(btrim(coalesce(p_note,'')),''),v_request.reason),
    p_penalty_basis,'active',v_owner,v_now,v_now
  )
  returning id into v_extension_id;

  update public.payment_extension_requests
     set status='approved',
         decision_at=v_now,
         decision_by=v_owner,
         decision_note=nullif(btrim(coalesce(p_note,'')),''),
         approved_until=p_approved_until,
         approved_by=btrim(p_approved_by),
         approval_reference=nullif(btrim(coalesce(p_approval_reference,'')),''),
         penalty_basis=p_penalty_basis,
         updated_at=v_now
   where id=v_request.id;

  update public.scheduled_actions
     set status='completed',
         completed_at=v_now,
         completion_note='Extension approved until '||to_char(p_approved_until,'DD Mon YYYY')||'.',
         updated_at=v_now
   where id=v_task.id;

  -- Approved extension replaces collection activity until the extension engine creates its extension task.
  update public.scheduled_actions
     set status='cancelled',cancelled_at=v_now,updated_at=v_now
   where unit_id=v_request.unit_id
     and status='pending'
     and id<>v_task.id
     and (
       schedule_id=v_request.payment_schedule_id
       or auto_key like '%|schedule:'||v_request.payment_schedule_id::text||'%'
       or auto_key like '%|schedules:%'||v_request.payment_schedule_id::text||'%'
     )
     and auto_kind<>'extension_active';

  return jsonb_build_object(
    'request_id',v_request.id,
    'task_id',v_task.id,
    'extension_id',v_extension_id,
    'decision','approved',
    'approved_until',p_approved_until,
    'next_action','Extension Active'
  );
end;
$function$;

grant execute on function public.crm_create_payment_extension_request(bigint,bigint,date,text) to authenticated;
grant execute on function public.crm_resolve_payment_extension_request(bigint,text,date,text,text,text,text) to authenticated;
