-- Partial Payment Commitment workflow.
-- Keeps the contractual installment unchanged and tracks customer-promised split payments underneath it.

create table if not exists public.partial_payment_plans (
  id bigint generated by default as identity primary key,
  unit_id bigint not null references public.units(id) on delete cascade,
  payment_schedule_id bigint not null references public.payment_schedule(id) on delete cascade,
  source_task_id bigint references public.scheduled_actions(id) on delete set null,
  status text not null default 'active' check (status in ('active','completed','cancelled')),
  note text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.partial_payment_plan_parts (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.partial_payment_plans(id) on delete cascade,
  sequence_no integer not null check (sequence_no > 0),
  amount numeric(14,2) not null check (amount > 0),
  commitment_date date not null,
  paid_amount numeric(14,2) not null default 0 check (paid_amount >= 0),
  status text not null default 'pending' check (status in ('pending','paid','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(plan_id, sequence_no)
);

alter table public.scheduled_actions
  add column if not exists commitment_part_id bigint references public.partial_payment_plan_parts(id) on delete set null;

alter table public.payment_transactions
  add column if not exists commitment_part_id bigint references public.partial_payment_plan_parts(id) on delete set null;

create index if not exists partial_payment_plans_schedule_idx
  on public.partial_payment_plans(payment_schedule_id, status);

create index if not exists partial_payment_plan_parts_plan_idx
  on public.partial_payment_plan_parts(plan_id, sequence_no);

create index if not exists scheduled_actions_commitment_part_idx
  on public.scheduled_actions(commitment_part_id);

create index if not exists payment_transactions_commitment_part_idx
  on public.payment_transactions(commitment_part_id);

alter table public.scheduled_actions
  drop constraint if exists scheduled_actions_workflow_kind_check;

alter table public.scheduled_actions
  add constraint scheduled_actions_workflow_kind_check
  check (
    workflow_kind is null or workflow_kind in (
      'accounts_confirmation',
      'cheque_clearance',
      'payment_receipt',
      'promise_follow_up',
      'payment_query',
      'payment_follow_up',
      'payment_review',
      'partial_payment_commitment'
    )
  );

alter table public.partial_payment_plans enable row level security;
alter table public.partial_payment_plan_parts enable row level security;

create or replace function public.crm_create_partial_payment_commitment(
  p_task_id bigint,
  p_parts jsonb,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_task public.scheduled_actions%rowtype;
  v_schedule public.payment_schedule%rowtype;
  v_plan_id bigint;
  v_part_id bigint;
  v_first_id bigint;
  v_first_amount numeric;
  v_first_date date;
  v_total numeric := 0;
  v_outstanding numeric := 0;
  v_credit numeric := 0;
  v_count integer := 0;
  v_idx integer := 0;
  v_item jsonb;
  v_amount numeric;
  v_date date;
  v_owner uuid := auth.uid();
  v_note text;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to create a partial payment commitment.';
  end if;

  select * into v_task
  from public.scheduled_actions
  where id = p_task_id
  for update;

  if not found or v_task.status <> 'pending' then
    raise exception 'Pending collection task not found.';
  end if;

  if v_task.schedule_id is null then
    raise exception 'This collection task is not linked to a single installment.';
  end if;

  select * into v_schedule
  from public.payment_schedule
  where id = v_task.schedule_id
  for update;

  if not found then
    raise exception 'Linked installment not found.';
  end if;

  if jsonb_typeof(p_parts) <> 'array' then
    raise exception 'Add at least two committed payment parts.';
  end if;

  v_count := jsonb_array_length(p_parts);
  if v_count < 2 then
    raise exception 'Add at least two committed payment parts.';
  end if;

  select coalesce(sum(c.amount),0)
    into v_credit
  from public.credit_notes c
  where c.payment_schedule_id = v_schedule.id;

  v_outstanding := greatest(0,
    coalesce(v_schedule.due_amount,0)
    - coalesce(v_schedule.paid_amount,0)
    - coalesce(v_credit,0)
  );

  for v_item in select value from jsonb_array_elements(p_parts)
  loop
    v_idx := v_idx + 1;
    begin
      v_amount := round((v_item->>'amount')::numeric,2);
      v_date := (v_item->>'date')::date;
    exception when others then
      raise exception 'Check the amount and date for payment part %.', v_idx;
    end;

    if v_amount is null or v_amount <= 0 then
      raise exception 'Payment part % must have an amount above zero.', v_idx;
    end if;
    if v_date is null then
      raise exception 'Payment part % must have a commitment date.', v_idx;
    end if;
    if v_date < current_date then
      raise exception 'Payment part % cannot be scheduled in the past.', v_idx;
    end if;

    v_total := v_total + v_amount;
  end loop;

  if v_total > v_outstanding + 0.01 then
    raise exception 'Committed amount (AED %) is more than the current outstanding amount (AED %).',
      trim(to_char(v_total,'FM999G999G999G990D00')),
      trim(to_char(v_outstanding,'FM999G999G999G990D00'));
  end if;

  update public.partial_payment_plans
     set status='cancelled', updated_at=now()
   where payment_schedule_id=v_schedule.id
     and status='active';

  insert into public.partial_payment_plans(
    unit_id,payment_schedule_id,source_task_id,status,note,created_by,created_at,updated_at
  ) values (
    v_task.unit_id,v_schedule.id,v_task.id,'active',
    nullif(btrim(coalesce(p_note,'')),''),
    v_owner,now(),now()
  )
  returning id into v_plan_id;

  v_idx := 0;
  for v_item in select value from jsonb_array_elements(p_parts)
  loop
    v_idx := v_idx + 1;
    v_amount := round((v_item->>'amount')::numeric,2);
    v_date := (v_item->>'date')::date;

    insert into public.partial_payment_plan_parts(
      plan_id,sequence_no,amount,commitment_date,paid_amount,status,created_at,updated_at
    ) values (
      v_plan_id,v_idx,v_amount,v_date,0,'pending',now(),now()
    )
    returning id into v_part_id;

    if v_idx = 1 then
      v_first_id := v_part_id;
      v_first_amount := v_amount;
      v_first_date := v_date;
    end if;
  end loop;

  v_note := 'Customer committed AED ' ||
    trim(to_char(v_first_amount,'FM999G999G999G990D00')) ||
    ' on ' || to_char(v_first_date,'DD Mon YYYY') ||
    ' · Part 1 of ' || v_count::text || '.';
  if nullif(btrim(coalesce(p_note,'')),'') is not null then
    v_note := v_note || ' ' || btrim(p_note);
  end if;

  update public.scheduled_actions
     set action_label='Follow up for Partial Payment',
         due_date=v_first_date,
         priority='Medium',
         note=v_note,
         source='manual',
         auto_kind=null,
         workflow_kind='partial_payment_commitment',
         commitment_part_id=v_first_id,
         transaction_id=null,
         status='pending',
         completed_at=null,
         completion_note=null,
         cancelled_at=null,
         updated_at=now()
   where id=v_task.id;

  return jsonb_build_object(
    'plan_id',v_plan_id,
    'task_id',v_task.id,
    'first_part_id',v_first_id,
    'parts',v_count,
    'committed_amount',v_total,
    'outstanding_amount',v_outstanding,
    'next_action','Follow up for Partial Payment'
  );
end;
$function$;

create or replace function public.crm_get_partial_payment_commitment_part(
  p_part_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_result jsonb;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to view payment commitments.';
  end if;

  select jsonb_build_object(
    'part_id',pp.id,
    'plan_id',pp.plan_id,
    'schedule_id',pl.payment_schedule_id,
    'sequence_no',pp.sequence_no,
    'part_count',(select count(*) from public.partial_payment_plan_parts x where x.plan_id=pp.plan_id and x.status<>'cancelled'),
    'amount',pp.amount,
    'paid_amount',pp.paid_amount,
    'remaining_amount',greatest(0,pp.amount-pp.paid_amount),
    'commitment_date',pp.commitment_date,
    'status',pp.status
  )
  into v_result
  from public.partial_payment_plan_parts pp
  join public.partial_payment_plans pl on pl.id=pp.plan_id
  where pp.id=p_part_id;

  if v_result is null then
    raise exception 'Partial payment commitment part not found.';
  end if;

  return v_result;
end;
$function$;

create or replace function public.crm_link_payment_commitment_part(
  p_transaction_id bigint,
  p_commitment_part_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_tx public.payment_transactions%rowtype;
  v_part public.partial_payment_plan_parts%rowtype;
  v_plan public.partial_payment_plans%rowtype;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role::text in ('crm_officer','manager')
  ) then
    raise exception 'You are not authorized to link this payment commitment.';
  end if;

  select * into v_tx
  from public.payment_transactions
  where id=p_transaction_id
  for update;

  if not found then
    raise exception 'Payment transaction not found.';
  end if;

  select * into v_part
  from public.partial_payment_plan_parts
  where id=p_commitment_part_id
  for update;

  if not found then
    raise exception 'Partial payment commitment part not found.';
  end if;

  select * into v_plan
  from public.partial_payment_plans
  where id=v_part.plan_id;

  if v_plan.payment_schedule_id is distinct from v_tx.payment_schedule_id
     or v_plan.unit_id is distinct from v_tx.unit_id then
    raise exception 'This payment does not match the committed installment.';
  end if;

  update public.payment_transactions
     set commitment_part_id=p_commitment_part_id
   where id=p_transaction_id;

  return jsonb_build_object(
    'transaction_id',p_transaction_id,
    'commitment_part_id',p_commitment_part_id
  );
end;
$function$;

create or replace function public.crm_advance_payment_confirmation_task()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_amount numeric;
  v_type text;
  v_amount_text text;
  v_commitment_part_id bigint;
  v_part public.partial_payment_plan_parts%rowtype;
  v_plan public.partial_payment_plans%rowtype;
  v_next public.partial_payment_plan_parts%rowtype;
  v_new_paid numeric;
  v_remaining numeric;
  v_part_count integer;
begin
  if old.status <> 'pending'
     or new.status <> 'completed'
     or old.workflow_kind is null
     or old.transaction_id is null then
    return new;
  end if;

  select amount, payment_type, commitment_part_id
    into v_amount, v_type, v_commitment_part_id
  from public.payment_transactions
  where id = old.transaction_id;

  if not found then
    return new;
  end if;

  v_amount_text := trim(to_char(round(coalesce(v_amount,0),2),'FM999G999G999G990D00'));

  if old.workflow_kind in ('accounts_confirmation','cheque_clearance') then
    update public.payment_transactions
       set accounts_confirmation_status = 'confirmed',
           accounts_confirmed_at = now(),
           accounts_confirmed_by = coalesce(auth.uid(), old.owner_id),
           accounts_confirmation_note = nullif(btrim(coalesce(new.completion_note,'')),''),
           payment_workflow_status = 'receipt_pending',
           payment_verification_issue = null
     where id = old.transaction_id;

    new.action_label := 'Send Payment Receipt';
    new.due_date := current_date;
    new.priority := 'Medium';
    new.note := 'Accounts confirmed AED ' || v_amount_text ||
      case when nullif(btrim(coalesce(v_type,'')),'') is not null
        then ' · ' || btrim(v_type) else '' end ||
      '. Send the official payment receipt to the customer.';
    new.status := 'pending';
    new.completed_at := null;
    new.completion_note := null;
    new.cancelled_at := null;
    new.workflow_kind := 'payment_receipt';
    new.source := 'manual';
    new.auto_kind := null;
    new.updated_at := now();

    return new;
  end if;

  if old.workflow_kind = 'payment_receipt' then
    update public.payment_transactions
       set receipt_sent_at = coalesce(receipt_sent_at, now()),
           receipt_sent_by = coalesce(receipt_sent_by, auth.uid(), old.owner_id),
           receipt_send_note = coalesce(
             nullif(btrim(coalesce(new.completion_note,'')),''),
             receipt_send_note
           ),
           payment_workflow_status = 'receipt_sent'
     where id = old.transaction_id;

    if v_commitment_part_id is not null then
      select * into v_part
      from public.partial_payment_plan_parts
      where id=v_commitment_part_id
      for update;

      if found and v_part.status='pending' then
        select * into v_plan
        from public.partial_payment_plans
        where id=v_part.plan_id
        for update;

        v_new_paid := least(v_part.amount, coalesce(v_part.paid_amount,0) + greatest(0,coalesce(v_amount,0)));

        update public.partial_payment_plan_parts
           set paid_amount=v_new_paid,
               status=case when v_new_paid >= amount-0.01 then 'paid' else 'pending' end,
               updated_at=now()
         where id=v_part.id;

        if v_new_paid < v_part.amount-0.01 then
          v_remaining := greatest(0,v_part.amount-v_new_paid);
          select count(*) into v_part_count
          from public.partial_payment_plan_parts
          where plan_id=v_part.plan_id and status<>'cancelled';

          new.action_label := 'Follow up for Remaining Partial Payment';
          new.due_date := greatest(v_part.commitment_date,current_date);
          new.priority := 'High';
          new.note := 'AED ' || trim(to_char(v_remaining,'FM999G999G999G990D00')) ||
            ' remains from Part ' || v_part.sequence_no::text || ' of ' || v_part_count::text ||
            ' · originally committed for ' || to_char(v_part.commitment_date,'DD Mon YYYY') || '.';
          new.status := 'pending';
          new.completed_at := null;
          new.completion_note := null;
          new.cancelled_at := null;
          new.workflow_kind := 'partial_payment_commitment';
          new.transaction_id := null;
          new.commitment_part_id := v_part.id;
          new.schedule_id := v_plan.payment_schedule_id;
          new.source := 'manual';
          new.auto_kind := null;
          new.updated_at := now();
          return new;
        end if;

        select * into v_next
        from public.partial_payment_plan_parts
        where plan_id=v_part.plan_id
          and status='pending'
          and sequence_no>v_part.sequence_no
        order by sequence_no
        limit 1
        for update;

        if found then
          select count(*) into v_part_count
          from public.partial_payment_plan_parts
          where plan_id=v_part.plan_id and status<>'cancelled';

          new.action_label := 'Follow up for Partial Payment';
          new.due_date := v_next.commitment_date;
          new.priority := 'Medium';
          new.note := 'Customer committed AED ' ||
            trim(to_char(v_next.amount,'FM999G999G999G990D00')) ||
            ' on ' || to_char(v_next.commitment_date,'DD Mon YYYY') ||
            ' · Part ' || v_next.sequence_no::text || ' of ' || v_part_count::text || '.';
          new.status := 'pending';
          new.completed_at := null;
          new.completion_note := null;
          new.cancelled_at := null;
          new.workflow_kind := 'partial_payment_commitment';
          new.transaction_id := null;
          new.commitment_part_id := v_next.id;
          new.schedule_id := v_plan.payment_schedule_id;
          new.source := 'manual';
          new.auto_kind := null;
          new.updated_at := now();
          return new;
        else
          update public.partial_payment_plans
             set status='completed', updated_at=now()
           where id=v_part.plan_id;
        end if;
      end if;
    end if;
  end if;

  return new;
end;
$function$;

grant execute on function public.crm_create_partial_payment_commitment(bigint,jsonb,text) to authenticated;
grant execute on function public.crm_get_partial_payment_commitment_part(bigint) to authenticated;
grant execute on function public.crm_link_payment_commitment_part(bigint,bigint) to authenticated;
